"""Histogram figures for the univariate-review chapter of the PID book.

Five committed PNGs, replacing images previously generated by base-R
scripts (``histogram-children-by-gender.R``, ``histogram-package-mass.R``,
``frequency-histogram.R``, ``histogram-70-30.R``, ``histogram-4-cuts.R``):

- ``histogram-children-by-gender.png``: frequency distribution of a
  categorical variable; the counts (1420 male, 1319 female, N = 2739)
  are the ones quoted in the chapter prose.
- ``histogram-package-mass.png``: histogram of a continuous variable,
  the mass of 500 cartons of 1 kg flour, with the nominal 1 kg fill
  marked so the overfill the prose discusses is visible.
- ``frequency-histogram.png``: the same 1000 standard-normal values
  shown as a frequency histogram (counts) and as a relative-density
  histogram (area = 1), side by side.
- ``histogram-70-30.png``: a two-category bar plot with a 70/30 split
  (used in the binary-distribution section).
- ``histogram-4-cuts.png``: counts of four roughly equally likely
  defect types (used in the uniform-distribution section).
- ``frequency-distribution-four-cases.png``: the four worked examples
  A, B, C and D from the "steps to creating a frequency distribution"
  recipe, showing how the resolution chosen for the measurement axis
  changes the plot: two categories, four ordered grades, integer
  percentages, and 5 K bins of a continuous measurement.

All random data are seeded so the committed images regenerate exactly.

Usage
-----
    uv run --with numpy --with matplotlib python histogram_chapter_figures.py [output_dir]

Writes the six PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np

# Okabe-Ito colourblind-safe palette entries used in these figures.
BLUE = "#0072B2"
VERMILLION = "#D55E00"
GRID = "#DDDDDD"

DPI = 300

# Font sizes match the pixel height of the labels in the base-R
# originals (pointsize 14 with cex 1.5-2 at the same DPI).
mpl.rcParams.update(
    {
        "font.size": 18,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 21,
        "axes.labelsize": 21,
        "xtick.labelsize": 19,
        "ytick.labelsize": 19,
        "axes.axisbelow": True,
    }
)


def new_axes(figsize):
    fig, ax = plt.subplots(figsize=figsize)
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    return fig, ax


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def children_by_gender(outdir: pathlib.Path) -> None:
    # Counts quoted in the chapter: 2739 births, 1420 male and 1319 female.
    counts = {"Male": 1420, "Female": 1319}
    # Wide enough for the axis label: at this font size the label is
    # longer than a square panel, and would otherwise run off the edge.
    fig, ax = new_axes((8.5, 7))
    bars = ax.bar(list(counts), list(counts.values()), width=0.6, color=BLUE)
    ax.bar_label(bars, padding=4)
    ax.set_ylabel(f"Number of children (N = {sum(counts.values())})")
    # The two tick labels already say the split is by sex.
    ax.set_xlabel("Children born in Hamilton, April 2009")
    ax.set_ylim(0, 1500)
    ax.set_yticks([0, 500, 1000, 1500])
    save(fig, outdir, "histogram-children-by-gender.png")


def package_mass(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(11)
    N = 500
    mass = rng.normal(loc=1100, scale=50, size=N)
    fig, ax = new_axes((10, 7))
    ax.hist(mass, bins=np.arange(950, 1275, 20), color=BLUE, edgecolor="white")
    ax.axvline(1000, color=VERMILLION, linestyle="--", linewidth=2)
    ax.text(
        1004, ax.get_ylim()[1] * 0.95, "1 kg nominal fill",
        color=VERMILLION, ha="left", va="top",
    )
    ax.set_xlabel("Mass [g] of each package")
    ax.set_ylabel(f"Number of packages (N = {N})")
    save(fig, outdir, "histogram-package-mass.png")


def frequency_histogram(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(3)
    N = 1000
    values = rng.normal(size=N)
    bins = np.arange(-3.5, 4.01, 0.5)
    fig, axes = plt.subplots(1, 2, figsize=(15, 7), sharex=True)
    for ax, density, ylabel in (
        (axes[0], False, f"Frequency (N = {N})"),
        (axes[1], True, "Relative density"),
    ):
        ax.grid(axis="y", color=GRID, linewidth=0.8)
        ax.hist(values, bins=bins, density=density, color=BLUE, edgecolor="white")
        ax.set_xlabel("Random values")
        ax.set_ylabel(ylabel)
    axes[0].set_title("Frequency histogram (counts)")
    axes[1].set_title("Relative-density histogram (area = 1)")
    save(fig, outdir, "frequency-histogram.png")


def histogram_70_30(outdir: pathlib.Path) -> None:
    fig, ax = new_axes((7, 7))
    bars = ax.bar(["Pass", "Fail"], [70, 30], width=0.6, color=BLUE)
    ax.bar_label(bars, fmt="%.0f%%", padding=4)
    ax.set_ylabel("Percentage of tablets")
    ax.set_ylim(0, 100)
    ax.set_yticks([0, 25, 50, 75, 100])
    save(fig, outdir, "histogram-70-30.png")


def histogram_4_cuts(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(2)
    N = 1000
    counts = np.bincount(rng.integers(0, 4, size=N), minlength=4)
    fig, ax = new_axes((7, 7))
    bars = ax.bar(["A", "B", "C", "D"], counts, width=0.6, color=BLUE)
    ax.bar_label(bars, padding=4)
    ax.set_xlabel("Defect type")
    ax.set_ylabel(f"Number of defects (N = {N})")
    ax.set_ylim(0, 0.3 * N)
    ax.set_yticks([0, 100, 200, 300])
    save(fig, outdir, "histogram-4-cuts.png")


def frequency_distribution_four_cases(outdir: pathlib.Path) -> None:
    """The four worked examples in the frequency-distribution recipe.

    Each panel uses a different resolution on the measurement axis,
    which is the point the recipe makes: A is a yes/no code, B is a
    four-level grade, C is quantized to whole percent, and D is a
    continuous measurement collected into 5 K bins.
    """
    rng = np.random.default_rng(19)

    fig, axes = plt.subplots(2, 2, figsize=(15, 12))
    for ax in axes.flat:
        ax.grid(axis="y", color=GRID, linewidth=0.8)

    # A: acceptable or unacceptable metal appearance, coded 1 or 0.
    appearance = rng.random(400) < 0.86
    counts = [int((~appearance).sum()), int(appearance.sum())]
    bars = axes[0, 0].bar(["Unacceptable (0)", "Acceptable (1)"], counts,
                          width=0.55, color=BLUE)
    axes[0, 0].bar_label(bars, padding=4)
    axes[0, 0].set_title("A: metal appearance, yes or no")
    axes[0, 0].set_xlabel("Appearance code")
    axes[0, 0].set_ylabel(f"Number of pieces (N = {len(appearance)})")
    axes[0, 0].set_ylim(0, 420)

    # B: number of defects on a metal sheet, graded 1 to 4.
    grade = rng.choice([1, 2, 3, 4], size=400, p=[0.46, 0.30, 0.17, 0.07])
    counts = np.bincount(grade, minlength=5)[1:]
    bars = axes[0, 1].bar(["1\nnone", "2\nlow", "3\nmedium", "4\nhigh"], counts,
                          width=0.55, color=BLUE)
    axes[0, 1].bar_label(bars, padding=4)
    axes[0, 1].set_title("B: defects on a metal sheet, four grades")
    axes[0, 1].set_xlabel("Defect grade")
    axes[0, 1].set_ylabel(f"Number of sheets (N = {len(grade)})")
    axes[0, 1].set_ylim(0, 220)

    # C: batch yield, reported to the nearest whole percent.
    yields = np.round(rng.normal(loc=80, scale=4.5, size=300)).astype(int)
    edges = np.arange(yields.min() - 0.5, yields.max() + 1.5, 1.0)
    axes[1, 0].hist(yields, bins=edges, color=BLUE, edgecolor="white")
    axes[1, 0].set_title("C: batch yield, rounded to 1%")
    axes[1, 0].set_xlabel("Yield [%]")
    axes[1, 0].set_ylabel(f"Number of batches (N = {len(yields)})")

    # D: ambient temperature, measured to 0.05 K but binned every 5 K.
    temperature = rng.normal(loc=284, scale=9, size=365)
    edges = np.arange(255, 316, 5)
    axes[1, 1].hist(temperature, bins=edges, color=BLUE, edgecolor="white")
    axes[1, 1].set_title("D: daily temperature, binned every 5 K")
    axes[1, 1].set_xlabel("Ambient temperature [K]")
    axes[1, 1].set_ylabel(f"Number of days (N = {len(temperature)})")

    save(fig, outdir, "frequency-distribution-four-cases.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    children_by_gender(outdir)
    package_mass(outdir)
    frequency_histogram(outdir)
    histogram_70_30(outdir)
    histogram_4_cuts(outdir)
    frequency_distribution_four_cases(outdir)
