"""Normal-distribution figures for the univariate-review chapter of the PID book.

Eight committed PNGs, replacing images previously generated by base-R
scripts (``simulate-dice-CLT.R``, ``normal-distribution-standardized.R``,
``show-pnorm-and-qnorm.R``, ``qqplot-derivation.R``, ``qqplot-comparison.R``,
``explain-confidence-interval.R``):

- ``simulate-CLT.png``: six histograms of the average of M dice throws
  (M = 1, 2, 4, 6, 8, 10), matching the chapter's inline code (N = 500).
- ``normal-distribution-standardized.png``: the standard normal density
  with the 1, 2, and 3 sigma distances marked from the centre.
- ``show-pnorm-and-qnorm.png``: the cumulative distribution, with one
  arrow tracing z -> area (``pnorm`` in R, ``norm.cdf`` in Python) and
  one tracing area -> z (``qnorm`` / ``norm.ppf``).
- ``qqplot-derivation.png``: the hand-constructed q-q plot of the ten
  batch yields used in the chapter, on the standardized scale.
- ``qqplot-from-R.png``: the same ten yields in a basic q-q plot (in the
  original units, with the quartile reference line), and next to it the
  version with a 95% confidence envelope. The filename is historical:
  the chapter shows how to draw both versions in R and in Python.
- ``qqplot-comparison.png``: 2000 samples from an F(200, 150)
  distribution; the histogram looks normal, the q-q plot shows the
  heavy right tail.
- ``explain-confidence-interval.png`` and
  ``explain-confidence-interval-normalized.png``: the raw-data
  distribution against the (narrower) distribution of the sample mean,
  for n = 5, in original units and standardized, the latter with the
  95% area between the two critical values marked.

The ten yield values (86.2, 85.7, ..., 78.4) are the ones printed in the
chapter text; all random data are seeded so the committed images
regenerate exactly.

Usage
-----
    uv run --with numpy --with scipy --with matplotlib python normal_distribution_figures.py [output_dir]

Writes the eight PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

# Okabe-Ito colourblind-safe palette entries used in these figures.
BLUE = "#0072B2"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300

# The ten batch yields quoted in the chapter (mean 80.0, std dev 8.35).
YIELDS = np.array([86.2, 85.7, 71.9, 95.3, 77.1, 71.4, 68.9, 78.9, 86.9, 78.4])

# Font sizes match the pixel height of the labels in the base-R
# originals (pointsize 14 with cex 1.5-1.8 at the same DPI). The
# six-panel CLT figure overrides these with smaller per-panel sizes,
# because its original used the un-scaled R default.
mpl.rcParams.update(
    {
        "font.size": 18,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 22,
        "axes.labelsize": 22,
        "xtick.labelsize": 19,
        "ytick.labelsize": 19,
        "legend.fontsize": 18,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def simulate_clt(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(2026)
    N = 500
    throws = rng.integers(1, 7, size=(10, N))
    groupings = [
        (1, "One throw", np.arange(0.5, 7, 1.0)),
        (2, "Average of two throws", 8),
        (4, "Average of 4 throws", 8),
        (6, "Average of 6 throws", 8),
        (8, "Average of 8 throws", 12),
        (10, "Average of 10 throws", 12),
    ]
    fig, axes = plt.subplots(2, 3, figsize=(10, 7))
    for ax, (m, label, bins) in zip(axes.flat, groupings):
        averages = throws[:m].mean(axis=0)
        ax.grid(axis="y", color=GRID, linewidth=0.8)
        ax.hist(averages, bins=bins, color=BLUE, edgecolor="white")
        ax.set_xlabel(label, fontsize=15)
        ax.set_xlim(0.5, 6.5)
        ax.set_xticks([1, 2, 3, 4, 5, 6])
        ax.tick_params(labelsize=13)
    for ax in axes[:, 0]:
        ax.set_ylabel(f"Frequency (N = {N})", fontsize=15)
    save(fig, outdir, "simulate-CLT.png")


def standardized_normal(outdir: pathlib.Path) -> None:
    x = np.linspace(-3.8, 3.8, 761)
    px = stats.norm.pdf(x)
    fig, ax = plt.subplots(figsize=(14, 7))
    ax.plot(x, px, color=BLUE, linewidth=2.5)
    ax.axvline(0, color="black", linewidth=1)
    for k in (1, 2, 3):
        y = stats.norm.pdf(k)
        ax.axvline(k, color=GRID, linewidth=1)
        ax.annotate(
            "", xy=(k, y), xytext=(0, y),
            arrowprops=dict(arrowstyle="<->", color=GREY, linewidth=1.5),
        )
        ax.text(k / 2, y + 0.012, rf"${k if k > 1 else ''}\sigma$",
                ha="center", fontsize=24)
    ax.set_xlabel("$x$")
    ax.set_ylabel("$p(x)$")
    ax.set_title(r"Normal distribution when $\mu=0$ and $\sigma=1$")
    ax.set_ylim(0, 0.42)
    ax.set_yticks([0, 0.1, 0.2, 0.3, 0.4])
    save(fig, outdir, "normal-distribution-standardized.png")


def show_pnorm_and_qnorm(outdir: pathlib.Path) -> None:
    z = np.linspace(-4, 4, 801)
    fig, ax = plt.subplots(figsize=(10, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(z, stats.norm.cdf(z), color=BLUE, linewidth=3)
    ax.axvline(0, color=GREY, linestyle=":", linewidth=1)

    # z -> cumulative area: pnorm(...) in R, norm.cdf(...) in Python.
    z1 = -0.5
    a1 = stats.norm.cdf(z1)
    ax.plot([z1, z1], [0, a1], color=VERMILLION, linewidth=2)
    ax.annotate(
        "", xy=(-4, a1), xytext=(z1, a1),
        arrowprops=dict(arrowstyle="->", color=VERMILLION, linewidth=2),
    )
    ax.plot(z1, a1, "o", color=VERMILLION, markersize=9)
    ax.text(-2.35, a1 + 0.06, "start with $z$, read off the\narea: pnorm(...)\nor norm.cdf(...)",
            color=VERMILLION, ha="center", fontsize=17)

    # Cumulative area -> z: qnorm(...) in R, norm.ppf(...) in Python.
    a2 = 0.8413
    z2 = stats.norm.ppf(a2)
    ax.plot([-4, z2], [a2, a2], color=ORANGE, linewidth=2)
    ax.annotate(
        "", xy=(z2, 0), xytext=(z2, a2),
        arrowprops=dict(arrowstyle="->", color=ORANGE, linewidth=2),
    )
    ax.plot(z2, a2, "o", color=ORANGE, markersize=9)
    ax.text(2.35, 0.42, "start with the area,\nread off $z$: qnorm(...)\nor norm.ppf(...)",
            color="#9A6A00", ha="center", fontsize=17)

    ax.set_xlabel("$z$")
    ax.set_ylabel("Cumulative area under normal distribution", fontsize=18)
    ax.set_ylim(0, 1.0)
    ax.set_xlim(-4, 4)
    ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    save(fig, outdir, "show-pnorm-and-qnorm.png")


def qq_derivation(outdir: pathlib.Path) -> None:
    N = len(YIELDS)
    P = (np.arange(1, N + 1) - 0.5) / N
    theoretical = stats.norm.ppf(P)
    z_sorted = np.sort((YIELDS - YIELDS.mean()) / YIELDS.std(ddof=1))

    fig, ax = plt.subplots(figsize=(7, 7))
    ax.grid(color=GRID, linewidth=0.8)
    lims = (-2.1, 2.1)
    ax.plot(lims, lims, color=GREY, linestyle="--", linewidth=1.5,
            label="45 degree line")
    ax.plot(theoretical, z_sorted, "o", color=BLUE, markersize=9)
    ax.set_xlabel("Theoretical quantile from the normal distribution")
    ax.set_ylabel("Standardized, sorted yield values")
    ax.set_xlim(lims)
    ax.set_ylim(lims)
    ax.set_aspect("equal")
    ax.legend(loc="upper left", frameon=False)
    save(fig, outdir, "qqplot-derivation.png")


def _qq_points(values: np.ndarray):
    """Return (theoretical quantiles, sorted values) for a normal q-q plot."""
    n = len(values)
    P = (np.arange(1, n + 1) - 0.5) / n
    return stats.norm.ppf(P), np.sort(values)


def _quartile_line(theoretical, ordered):
    """Slope/intercept of the line through the quartile pairs (R's qqline)."""
    x25, x75 = np.percentile(theoretical, [25, 75])
    y25, y75 = np.percentile(ordered, [25, 75])
    slope = (y75 - y25) / (x75 - x25)
    return slope, y25 - slope * x25


def _envelope(theoretical, slope, intercept, n, conf=0.95):
    """Pointwise confidence envelope around the quartile line (car::qqPlot)."""
    P = stats.norm.cdf(theoretical)
    se = (slope / stats.norm.pdf(theoretical)) * np.sqrt(P * (1 - P) / n)
    fit = intercept + slope * theoretical
    zc = stats.norm.ppf(1 - (1 - conf) / 2)
    return fit - zc * se, fit + zc * se


def qq_basic_and_envelope(outdir: pathlib.Path) -> None:
    theo, ordered = _qq_points(YIELDS)
    slope, intercept = _quartile_line(theo, ordered)

    fig, axes = plt.subplots(1, 2, figsize=(14, 7), sharey=True, sharex=True)
    for ax in axes:
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(theo, intercept + slope * theo, color=GREY, linewidth=1.5)
        ax.plot(theo, ordered, "o", color=BLUE, markersize=9)
        ax.set_xlabel("Theoretical quantile")
    axes[0].set_ylabel("Yield values [%]")
    axes[0].set_title("Basic q-q plot, in the original units")

    lower, upper = _envelope(theo, slope, intercept, len(YIELDS))
    axes[1].plot(theo, lower, color=VERMILLION, linestyle="--", linewidth=1.5)
    axes[1].plot(theo, upper, color=VERMILLION, linestyle="--", linewidth=1.5)
    axes[1].set_title("With a 95% confidence envelope")
    save(fig, outdir, "qqplot-from-R.png")


def qq_comparison(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(7)
    rand_f = stats.f.rvs(dfn=200, dfd=150, size=2000, random_state=rng)

    fig, axes = plt.subplots(1, 2, figsize=(14, 7))
    ax = axes[0]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.hist(rand_f, bins=30, density=True, color=BLUE, edgecolor="white")
    kde = stats.gaussian_kde(rand_f)
    grid = np.linspace(rand_f.min(), rand_f.max(), 400)
    ax.plot(grid, kde(grid), color="black", linewidth=1.5)
    ax.set_title("Are these data from a normal distribution?")
    ax.set_xlabel("2000 samples from an F(200, 150) distribution")
    ax.set_ylabel("Relative density")

    ax = axes[1]
    ax.grid(color=GRID, linewidth=0.8)
    theo, ordered = _qq_points(rand_f)
    slope, intercept = _quartile_line(theo, ordered)
    lower, upper = _envelope(theo, slope, intercept, len(rand_f))
    ax.plot(theo, intercept + slope * theo, color=GREY, linewidth=1.5)
    ax.plot(theo, lower, color=VERMILLION, linestyle="--", linewidth=1.5)
    ax.plot(theo, upper, color=VERMILLION, linestyle="--", linewidth=1.5)
    ax.plot(theo, ordered, "o", color=BLUE, markersize=4, alpha=0.6)
    ax.annotate(
        "heavy right tail",
        xy=(theo[-8], ordered[-8]), xytext=(1.0, ordered[-1]),
        arrowprops=dict(arrowstyle="->", color="black"), ha="left",
    )
    ax.set_title("q-q plot against the normal distribution")
    ax.set_xlabel("Theoretical quantile")
    ax.set_ylabel("Sample values")
    save(fig, outdir, "qqplot-comparison.png")


def _two_distributions(ax, x, base_mean, base_sd, n, legend_loc="upper left"):
    raw = stats.norm.pdf(x, loc=base_mean, scale=base_sd)
    sample = stats.norm.pdf(x, loc=base_mean, scale=base_sd / np.sqrt(n))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, sample, color=BLUE, linewidth=3.5,
            label="Sample mean's distribution")
    ax.plot(x, raw, color=GREY, linewidth=1.5, label="Raw data's distribution")
    ax.axvline(base_mean, color="black", linewidth=1)
    ax.legend(loc=legend_loc, frameon=False, fontsize=16)


def explain_confidence_interval(outdir: pathlib.Path) -> None:
    n = 5
    base_mean, base_sd = 700, 50
    x = np.linspace(base_mean - 3.5 * base_sd, base_mean + 3.5 * base_sd, 701)

    fig, ax = plt.subplots(figsize=(10, 7))
    _two_distributions(ax, x, base_mean, base_sd, n)
    ax.text(base_mean - 2 * base_sd, 0.010, f"Sample size, n = {n}", ha="center")
    ax.set_xlabel(r"$x$ (thin), or $\bar{x}$ (thick)")
    ax.set_ylabel("Probability density")
    ax.set_title("Raw data distribution, and sample mean distribution")
    ax.set_yticks([0, 0.005, 0.010, 0.015])
    save(fig, outdir, "explain-confidence-interval.png")

    # Standardized version, with the 95% area between the critical values.
    fig, ax = plt.subplots(figsize=(10, 7))
    x = np.linspace(-3.5, 3.5, 701)
    _two_distributions(ax, x, 0, 1, n, legend_loc="center right")
    ax.text(-2.2, 0.4, f"Sample size, n = {n}", ha="center")
    upper = stats.norm.ppf(0.975) / np.sqrt(n)
    for v in (-upper, upper):
        ax.axvline(v, color=VERMILLION, linestyle="--", linewidth=2)
    y_arrow = 0.92
    ax.annotate(
        "", xy=(-upper, y_arrow), xytext=(upper, y_arrow),
        arrowprops=dict(arrowstyle="<->", color=VERMILLION, linewidth=2),
    )
    ax.text(0, 0.95, "95% area", ha="center", fontweight="bold",
            bbox=dict(facecolor="white", edgecolor="none", pad=2))
    ax.set_ylim(0, 1.0)
    ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    ax.set_xlabel("$z$")
    ax.set_ylabel("Probability density")
    ax.set_title("Raw data distribution, and sample mean distribution")
    save(fig, outdir, "explain-confidence-interval-normalized.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    simulate_clt(outdir)
    standardized_normal(outdir)
    show_pnorm_and_qnorm(outdir)
    qq_derivation(outdir)
    qq_basic_and_envelope(outdir)
    qq_comparison(outdir)
    explain_confidence_interval(outdir)
