"""System-comparison figures for the univariate-review chapter of the PID book.

Three committed PNGs, replacing images previously generated by the
base-R script ``system-comparison.R``:

- ``system-comparison-boxplot-plots.png``: box plots of the ten batch
  yields under feedback-control system A and system B, next to the two
  sequences plotted in run order with their means marked.
- ``system-comparison-dotplot-grouped.png``: the dot plot of the 281
  differences between means of two adjacent groups of 10 batches,
  computed from the 300-batch historical reference set, with the
  observed difference of 3.04 marked.
- ``system-comparison-autocorrelation-scatterplot.png``: yield of batch
  k against batch k+1 for the historical reference set, with a LOWESS
  trend line showing the negative autocorrelation.

Inputs: ``system-comparison.csv`` (the ten A and ten B yields printed in
the chapter) and ``system-comparison-historical-data.csv`` (the same 300
values as https://openmv.net/info/batch-yields), both in this directory.

The script prints the verification numbers quoted in the prose: the
difference in means (3.04) and the count of historical differences at or
beyond it (31 of 281, about 11%).

Usage
-----
    uv run --with numpy --with pandas --with scipy --with matplotlib python system_comparison_figures.py [output_dir]

Writes the three PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

BLUE = "#0072B2"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 250
HERE = pathlib.Path(__file__).parent

mpl.rcParams.update(
    {
        "font.size": 13,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 14,
        "axes.labelsize": 13,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def load_data():
    comparison = pd.read_csv(HERE / "system-comparison.csv", skipinitialspace=True)
    comparison.columns = [c.strip() for c in comparison.columns]
    A = comparison.loc[comparison["method"].str.strip() == "A", "obs"].to_numpy()
    B = comparison.loc[comparison["method"].str.strip() == "B", "obs"].to_numpy()
    historical = pd.read_csv(
        HERE / "system-comparison-historical-data.csv", header=None
    )[0].to_numpy()
    return A, B, historical


def boxplot_and_sequences(A, B, outdir: pathlib.Path) -> None:
    limits = (min(A.min(), B.min()) - 1.5, max(A.max(), B.max()) + 1.5)
    fig, axes = plt.subplots(
        1, 3, figsize=(12, 7), width_ratios=[2, 1, 1], sharey=True
    )

    ax = axes[0]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    box = ax.boxplot(
        [A, B], tick_labels=["A", "B"], widths=0.5, patch_artist=True,
        medianprops=dict(color="black", linewidth=2),
    )
    for patch in box["boxes"]:
        patch.set(facecolor="#B3D4EA", edgecolor=BLUE, linewidth=1.5)
    for part in ("whiskers", "caps"):
        plt.setp(box[part], color=BLUE, linewidth=1.5)
    ax.set_title("Batch yield [%] for two trials")
    ax.set_ylabel("Yield [%]")

    for ax, series, label in ((axes[1], A, "A"), (axes[2], B, "B")):
        ax.grid(axis="y", color=GRID, linewidth=0.8)
        ax.plot(np.arange(1, 11), series, "o", color=BLUE, markersize=7)
        ax.axhline(series.mean(), color=VERMILLION, linewidth=2.5)
        ax.set_title(f"{label} (mean = {series.mean():.2f})")
        ax.set_xlabel("Run order")
        ax.set_xticks([2, 4, 6, 8, 10])
    ax.set_ylim(limits)
    save(fig, outdir, "system-comparison-boxplot-plots.png")


def dotplot_grouped(A, B, historical, outdir: pathlib.Path) -> None:
    delta = 10
    n = len(historical)
    means = np.array([historical[i : i + delta].mean() for i in range(n - delta + 1)])
    diffs = means[delta:] - means[:-delta]
    difference = B.mean() - A.mean()

    beyond = int((diffs >= difference).sum())
    print(
        f"difference in means: {difference:.2f}; "
        f"{beyond} of {len(diffs)} historical differences >= that "
        f"({100 * beyond / len(diffs):.0f}%)"
    )

    # Stack the dots in bins, dot-plot style.
    binwidth = 0.25
    bins = np.round(diffs / binwidth) * binwidth
    fig, ax = plt.subplots(figsize=(12.5, 4))
    for value in np.unique(bins):
        count = int((bins == value).sum())
        shaded = value >= difference
        ax.plot(
            [value] * count, np.arange(1, count + 1),
            "o", color=VERMILLION if shaded else BLUE,
            markersize=5, alpha=0.9,
        )
    ax.axvline(difference, color="black", linewidth=1.5)
    top = ax.get_ylim()[1]
    ax.annotate(
        f"{difference:.2f}", xy=(difference, top * 0.97),
        xytext=(difference + 1.3, top * 0.97),
        arrowprops=dict(arrowstyle="<-", color="black"), va="center",
    )
    ax.text(
        6.2, top * 0.75,
        f"{beyond} of {len(diffs)} differences\nare at 3.04 or beyond (11%)",
        ha="center", fontsize=11,
    )
    ax.set_xlim(-10, 10)
    ax.set_xlabel("Difference between means of 2 adjacent groups (10 batches per group)")
    ax.set_yticks([])
    ax.spines["left"].set_visible(False)
    save(fig, outdir, "system-comparison-dotplot-grouped.png")


def _lowess(x: np.ndarray, y: np.ndarray, frac: float = 0.5, gridsize: int = 60):
    """Plain tricube-weighted local linear smoother (LOWESS, one pass)."""
    order = np.argsort(x)
    xs, ys = x[order], y[order]
    span = max(2, int(frac * len(xs)))
    grid = np.linspace(xs.min(), xs.max(), gridsize)
    fitted = np.empty_like(grid)
    for i, x0 in enumerate(grid):
        distance = np.abs(xs - x0)
        cutoff = np.sort(distance)[span - 1]
        w = np.clip(1 - (distance / max(cutoff, 1e-12)) ** 3, 0, None) ** 3
        W = np.sum(w)
        xm = np.sum(w * xs) / W
        ym = np.sum(w * ys) / W
        b = np.sum(w * (xs - xm) * (ys - ym)) / max(np.sum(w * (xs - xm) ** 2), 1e-12)
        fitted[i] = ym + b * (x0 - xm)
    return grid, fitted


def autocorrelation_scatter(historical, outdir: pathlib.Path) -> None:
    x_k = historical[:-1]
    x_next = historical[1:]
    fig, ax = plt.subplots(figsize=(7, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x_k, x_next, "o", color=BLUE, markersize=5, alpha=0.65)
    grid, fitted = _lowess(x_k, x_next)
    ax.plot(grid, fitted, color=VERMILLION, linewidth=2.5, label="LOWESS trend")
    ax.set_xlabel("Yield of batch $k$ [%]")
    ax.set_ylabel("Yield of batch $k+1$ [%]")
    ax.set_title("Autocorrelation between successive batch yields")
    ax.set_xlim(60, 100)
    ax.set_ylim(60, 100)
    ax.set_aspect("equal")
    ax.legend(loc="upper right", frameon=False)
    save(fig, outdir, "system-comparison-autocorrelation-scatterplot.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    A, B, historical = load_data()
    boxplot_and_sequences(A, B, outdir)
    dotplot_grouped(A, B, historical, outdir)
    autocorrelation_scatter(historical, outdir)
