"""t-distribution and Poisson figures for the univariate-review chapter.

Two committed PNGs, replacing images previously generated by base-R
scripts (``t-distribution-comparison.R``, ``poisson-distribution.R``):

- ``t-distribution-comparison.png``: the standard normal density
  overlaid with the t-distribution (8 degrees of freedom). The two
  curves are drawn in distinct colours, with a zoomed inset of the
  right tail, so the lower peak and the broader tails the prose
  describes are both visible.
- ``poisson-distribution.png``: the Poisson probability mass function
  for a rate parameter of 4, markers at the integers with a light
  connecting guide line (the distribution is defined only at the
  integers, as the caption notes).

Usage
-----
    uv run --with numpy --with scipy --with matplotlib python t_and_poisson_figures.py [output_dir]

Writes the two PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

# Okabe-Ito colourblind-safe palette entries used in these figures.
BLUE = "#0072B2"
ORANGE = "#E69F00"
GRID = "#DDDDDD"

DPI = 250

mpl.rcParams.update(
    {
        "font.size": 13,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 14,
        "axes.labelsize": 13,
        "axes.axisbelow": True,
    }
)


def t_comparison(outdir: pathlib.Path, dof: int = 8) -> None:
    x = np.linspace(-4, 4, 801)
    fig, ax = plt.subplots(figsize=(14, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, stats.norm.pdf(x), color=BLUE, linewidth=3,
            label="Normal distribution")
    ax.plot(x, stats.t.pdf(x, df=dof), color=ORANGE, linewidth=2.5,
            label=f"$t$-distribution ({dof} degrees of freedom)")
    ax.axvline(0, color="black", linewidth=0.8)
    ax.set_xlabel("$z$")
    ax.set_ylabel("$p(z)$")
    ax.legend(loc="upper left", frameon=False)

    # Inset: zoom into the right tail, where the t-distribution sits
    # above the normal distribution.
    inset = ax.inset_axes([0.66, 0.35, 0.32, 0.42])
    xt = np.linspace(2, 4, 201)
    inset.plot(xt, stats.norm.pdf(xt), color=BLUE, linewidth=2.5)
    inset.plot(xt, stats.t.pdf(xt, df=dof), color=ORANGE, linewidth=2)
    inset.set_title("Zoom of the right tail", fontsize=11)
    inset.tick_params(labelsize=10)
    inset.grid(color=GRID, linewidth=0.6)
    save(fig, outdir, "t-distribution-comparison.png")


def poisson(outdir: pathlib.Path, eta: float = 4) -> None:
    x = np.arange(0, 16)
    px = stats.poisson.pmf(x, mu=eta)
    fig, ax = plt.subplots(figsize=(10, 7))
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.plot(x, px, color=GRID, linewidth=1.5, zorder=1)
    markers, stems, _ = ax.stem(x, px, basefmt=" ")
    plt.setp(stems, color=BLUE, linewidth=1.5)
    plt.setp(markers, color=BLUE, markersize=8)
    ax.set_xlabel("$x$ = number of events")
    ax.set_ylabel("$p(x)$")
    ax.set_title(rf"$\eta = {eta:.0f}$")
    ax.set_ylim(0, 0.21)
    save(fig, outdir, "poisson-distribution.png", dpi=200)


def save(fig, outdir: pathlib.Path, name: str, dpi: int = DPI) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=dpi)
    plt.close(fig)
    print(f"wrote {outdir / name}")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    t_comparison(outdir)
    poisson(outdir)
