"""Group-comparison exercise figures for the univariate-review chapter.

Six committed PNGs, replacing images previously generated by base-R
scripts (``bulb-energy-assignment3-2010.R``,
``brittleness-comparison-assignment3-2010.R``,
``website-visits-univariate.R``, ``BOD-data-assignment3-2010.R``,
``t-distribution-normal-comparison-assignment3-2010.R``,
``overlaid-distributions-normal-and-t.R``). These serve the "compare two
groups" and "t-distribution" questions in
``univariate-review/univariate-exercises.rst``:

- ``bulb-energy-barplot.png``: the supplier's histogram of the energy
  drawn by 50 light fixtures over 24 hours, given only as bin centres
  and counts.
- ``brittleness-boxplot.png``: brittleness index for the three reactors
  in https://openmv.net/info/brittleness-index, which have unequal
  numbers of measurements.
- ``Website-traffic-TS.png``: daily visits from
  https://openmv.net/info/website-traffic, June to December, used as
  context for the Friday-versus-Saturday comparison. This replaces a
  661 by 122 pixel screenshot of a web analytics dashboard.
- ``BOD-comparison-plot.png``: the difference between the dilution and
  manometric methods for the eleven split samples printed in the
  exercise, with the single positive difference marked.
- ``normal-t-comparison.png``: cumulative normal and t-distributions at
  6 and 35 degrees of freedom. The R original was labelled
  ``t-distribution (df=8)`` in the left panel's legend while plotting
  and titling 6 degrees of freedom; the legend now says 6, matching the
  question.
- ``overlaid-distributions-normal-and-t.png``: the two densities for a
  sample of 7 (so 6 degrees of freedom). Previously stored with a
  ``.jpg`` extension despite holding PNG bytes, and with
  "t-distribtion" misspelled in the legend.

Values printed in the exercise text are embedded as literals here so the
figures reproduce exactly; the brittleness and website-traffic data come
from openmv.net, with a local CSV of the same name next to this script
used as a fallback when offline.

The script prints the statistics quoted in the exercise solutions so
they are re-verified on every run.

Usage
-----
    uv run --with numpy --with pandas --with scipy --with matplotlib python univariate_comparison_figures.py [output_dir]

Writes the six PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

BLUE = "#0072B2"
BLUE_FILL = "#B3D4EA"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 250
HERE = pathlib.Path(__file__).parent

# Font sizes match the pixel height of the labels in the base-R
# originals (pointsize 14 at the same DPI), slightly boosted.
mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)

# The supplier reported only the binned histogram, not the 50 raw
# values, which is the point of the exercise.
BULB_CENTRES = [4025, 4075, 4125, 4175, 4225, 4275, 4325, 4375]
BULB_COUNTS = [4, 19, 14, 5, 4, 1, 2, 1]
BULB_N = 50

# Biochemical oxygen demand, mg/L, on eleven split samples, as printed
# in the exercise table.
DILUTION = [11, 26, 18, 16, 20, 12, 8, 26, 12, 17, 14]
MANOMETRIC = [25, 3, 27, 30, 33, 16, 28, 27, 12, 32, 16]


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def fetch(name: str) -> pd.DataFrame:
    try:
        return pd.read_csv(f"https://openmv.net/file/{name}")
    except Exception:
        return pd.read_csv(HERE / name)


def styled_boxplot(ax, data, labels):
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    box = ax.boxplot(
        data, tick_labels=labels, widths=0.6, patch_artist=True,
        medianprops=dict(color="black", linewidth=2),
        flierprops=dict(marker="o", markersize=6, markerfacecolor="none",
                        markeredgecolor=VERMILLION, markeredgewidth=1.8),
    )
    for patch in box["boxes"]:
        patch.set(facecolor=BLUE_FILL, edgecolor=BLUE, linewidth=1.5)
    for part in ("whiskers", "caps"):
        plt.setp(box[part], color=BLUE, linewidth=1.5)


def bulb_energy(outdir: pathlib.Path) -> None:
    centres = np.array(BULB_CENTRES, dtype=float)
    counts = np.array(BULB_COUNTS, dtype=float)
    mean = float((centres * counts).sum() / BULB_N)
    sd = float(np.sqrt((counts * (centres - mean) ** 2).sum() / (BULB_N - 1)))
    print(f"bulb energy: mean {mean:.0f}, sd {sd:.1f}")

    fig, ax = plt.subplots(figsize=(8, 6.5))
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.bar(centres, counts, width=46, color=BLUE_FILL, edgecolor=BLUE,
           linewidth=1.8)
    ax.set_xlabel("Energy required over 24 hours (W.h)")
    ax.set_ylabel(f"Number of bulbs (N={BULB_N})")
    ax.set_ylim(0, 20)
    ax.set_xticks(centres)
    ax.tick_params(axis="x", labelsize=13)
    save(fig, outdir, "bulb-energy-barplot.png")


def brittleness(outdir: pathlib.Path) -> None:
    brittle = fetch("brittleness-index.csv")
    columns = ["TK104", "TK105", "TK107"]
    groups = [brittle[c].dropna().to_numpy(dtype=float) for c in columns]
    print(
        "brittleness: n "
        + ", ".join(f"{c} {len(g)}" for c, g in zip(columns, groups))
    )
    # The exercise compares each pair with a pooled variance.
    for (a, name_a), (b, name_b) in (
        ((groups[0], "TK104"), (groups[1], "TK105")),
        ((groups[0], "TK104"), (groups[2], "TK107")),
        ((groups[1], "TK105"), (groups[2], "TK107")),
    ):
        dof = len(a) - 1 + len(b) - 1
        pooled = ((len(a) - 1) * a.var(ddof=1) + (len(b) - 1) * b.var(ddof=1)) / dof
        z = (b.mean() - a.mean()) / np.sqrt(pooled * (1 / len(a) + 1 / len(b)))
        print(f"  {name_a} vs {name_b}: z {z:.3f}")

    fig, ax = plt.subplots(figsize=(7, 6.5))
    styled_boxplot(ax, groups, columns)
    ax.set_ylabel("Brittleness index")
    save(fig, outdir, "brittleness-boxplot.png")


def website_traffic_series(outdir: pathlib.Path) -> None:
    web = fetch("website-traffic.csv")
    when = pd.to_datetime(
        web["MonthDay"].str.strip() + " " + web["Year"].astype(str),
        format="%B %d %Y",
    )
    web = web.assign(When=when).sort_values("When")
    visits = web["Visits"].to_numpy(dtype=float)
    print(
        f"website traffic: n {len(visits)}, mean {visits.mean():.2f}, "
        f"sd {visits.std(ddof=1):.2f}, "
        f"P(10 to 30) {stats.norm.cdf((30 - visits.mean()) / visits.std(ddof=1)) - stats.norm.cdf((10 - visits.mean()) / visits.std(ddof=1)):.3f}"
    )

    fig, ax = plt.subplots(figsize=(14, 3.4))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(web["When"], visits, color=BLUE, linewidth=1.6)
    ax.set_ylabel("Visits")
    ax.set_yticks([0, 25, 50])
    ax.set_ylim(0, 52)
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b"))
    ax.set_xlim(web["When"].min(), web["When"].max())
    save(fig, outdir, "Website-traffic-TS.png")


def bod_comparison(outdir: pathlib.Path) -> None:
    dilution = np.array(DILUTION, dtype=float)
    manometric = np.array(MANOMETRIC, dtype=float)
    difference = dilution - manometric
    sample = np.arange(1, len(dilution) + 1)
    outlier = difference > 0
    print(
        f"BOD: mean dilution {dilution.mean():.1f}, "
        f"mean manometric {manometric.mean():.1f}, "
        f"mean difference {difference.mean():.2f}"
    )

    fig, ax = plt.subplots(figsize=(7, 6.5))
    ax.grid(color=GRID, linewidth=0.8)
    ax.axhline(0, color=GREY, linewidth=1.8)
    ax.plot(sample[~outlier], difference[~outlier], "o", color=BLUE,
            markersize=11, markerfacecolor="none", markeredgewidth=2)
    ax.plot(sample[outlier], difference[outlier], "o", color=VERMILLION,
            markersize=12, markerfacecolor="none", markeredgewidth=2.4)
    ax.set_xlabel("Sample number")
    ax.set_ylabel("Dilution - Manometric")
    ax.set_xticks([2, 4, 6, 8, 10])
    save(fig, outdir, "BOD-comparison-plot.png")


def normal_versus_t(outdir: pathlib.Path) -> None:
    z = np.arange(-5, 5.001, 0.1)
    normal = stats.norm.cdf(z)

    fig, axes = plt.subplots(1, 2, figsize=(12, 6), sharey=True)
    for ax, dof in zip(axes, (6, 35)):
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(z, normal, ".", color=GREY, markersize=9,
                label="Normal distribution")
        ax.plot(z, stats.t.cdf(z, df=dof), color=BLUE, linewidth=2.5,
                label=f"$t$-distribution (df={dof})")
        ax.set_title(f"Normal and $t$-distribution (df={dof})")
        ax.set_xlabel("$z$")
        ax.legend(loc="upper left", frameon=False, fontsize=14)
    axes[0].set_ylabel("Cumulative probability")
    save(fig, outdir, "normal-t-comparison.png")


def overlaid_normal_and_t(outdir: pathlib.Path) -> None:
    n = 7
    z = np.arange(-5, 5.001, 0.01)

    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(z, stats.norm.pdf(z), color=BLUE, linewidth=2.5,
            label="Normal distribution")
    ax.plot(z, stats.t.pdf(z, df=n - 1), "--", color=VERMILLION, linewidth=2.5,
            label=f"$t$-distribution (df={n - 1})")
    ax.set_xlabel("$z$")
    ax.set_ylabel("Normal and $t$-distributions")
    ax.legend(loc="upper right", frameon=False)
    save(fig, outdir, "overlaid-distributions-normal-and-t.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    bulb_energy(outdir)
    brittleness(outdir)
    website_traffic_series(outdir)
    bod_comparison(outdir)
    normal_versus_t(outdir)
    overlaid_normal_and_t(outdir)
