"""Exercise figures for the univariate-review chapter of the PID book.

Eleven committed PNGs, replacing images previously generated by base-R
scripts (``soy-salt-content.R``, ``raw-materials-univariate-checks.R``,
``hamilton-weather-data.R``, ``show-confidence-interval.R``,
``batch-yields.R``). These serve the "describe a distribution" and
"check for normality" questions in ``univariate-review/univariate-exercises.rst``:

- ``soy-salt-content.png``: box plot of the salt content of 13 soy
  sauces, the data printed in the exercise itself.
- ``size1.png``, ``size2.png``, ``size3.png``, ``density1.png``,
  ``density2.png``, ``density3.png``: index plots of the six powder
  properties in https://openmv.net/info/raw-material-properties. The R
  original used ``identify()``, so the labelled points were chosen by
  clicking on them; those same sample names are listed in
  ``IDENTIFIED`` below so the redrawn figures carry the same labels.
  The y-axis of the three density plots read "Particle density: density
  N" while the code shown to the reader says "level N"; all six now say
  "level N".
- ``snowfall-data.png``, ``temperature-data.png``: annual snowfall and
  mean temperature at HAMILTON A, 2000 to 2008, against the 1971 to 2000
  long-term averages.
- ``show-confidence-interval.png``: the standard normal density with the
  central region between -c and +c shaded, used to set up the
  confidence-interval derivation.
- ``batch-yields-qqplot.png``: normal q-q plot of the 300 bioreactor
  yields in https://openmv.net/info/batch-yields, with a 95% pointwise
  envelope, replacing R's ``car::qqPlot`` output.

Data sources: values printed in the exercise text are embedded as
literals here so the figures reproduce exactly; the raw-material
properties come from openmv.net (a local CSV of the same name next to
this script is used as a fallback when offline), and the batch yields
are read from the committed ``batch-yields.csv``.

The script prints the statistics quoted in the exercise solutions so
they are re-verified on every run.

Usage
-----
    uv run --with numpy --with pandas --with scipy --with matplotlib python univariate_exercise_figures.py [output_dir]

Writes the eleven PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

BLUE = "#0072B2"
BLUE_FILL = "#B3D4EA"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 250
HERE = pathlib.Path(__file__).parent

# Font sizes match the pixel height of the labels in the base-R
# originals (pointsize 14 at the same DPI), slightly boosted.
mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)

# Salt content of 13 soy sauces, mg per 15 mL serving, as printed in the
# exercise (Globe and Mail, 24 September 2009).
SALT = [460, 520, 580, 700, 760, 770, 890, 910, 920, 940, 960, 1060, 1100]

# HAMILTON A, Environment Canada. Total annual snowfall (cm) and average
# of the monthly mean temperature (degrees C), 2000 to 2008, with the
# 1971 to 2000 normals.
YEARS = np.arange(2000, 2009)
SNOWFALL = [170.9, 94.1, 138.0, 166.2, 175.8, 218.4, 56.6, 182.4, 243.2]
TEMPERATURE = [7.6, 8.8, 8.8, 7.3, 7.7, 8.2, 9.1, 8.2, 7.7]
SNOWFALL_NORMAL = 161.8
TEMPERATURE_NORMAL = 7.6

# The points labelled in the original figures, which were picked out one
# at a time with R's interactive identify() function. Keeping the list
# here reproduces the same annotations without an interactive session.
IDENTIFIED = {
    "size1": ["X15468", "X54272"],
    "size2": ["X12558", "X15468", "X24055", "X54272"],
    "size3": ["X12558", "X24055", "X40503", "X54272", "X61888"],
    "density1": ["X12558", "X24905", "X56952", "X72736"],
    "density2": ["X12558", "X24905", "X56952", "X72736"],
    "density3": ["X53925", "X54272"],
}


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def fetch(name: str) -> pd.DataFrame:
    try:
        return pd.read_csv(f"https://openmv.net/file/{name}")
    except Exception:
        return pd.read_csv(HERE / name)


def spread_labels_apart(fig, ax, texts) -> None:
    """Nudge annotation text upwards until no two labels overlap.

    Several of the raw-material properties flag points that sit at
    almost the same height, so labels placed beside their markers would
    otherwise run into each other.
    """
    fig.canvas.draw()
    renderer = fig.canvas.get_renderer()
    inverse = ax.transData.inverted()
    (_, base), (_, one_pixel_up) = inverse.transform([(0, 0), (0, 1)])
    step = 4 * (one_pixel_up - base)

    placed: list = []
    for text in sorted(texts, key=lambda t: -t.get_position()[1]):
        for _ in range(60):
            box = text.get_window_extent(renderer)
            if not any(box.overlaps(other) for other in placed):
                break
            x, y = text.get_position()
            text.set_position((x, y + step))
            fig.canvas.draw()
        placed.append(text.get_window_extent(renderer))

    # Make room for any label that was pushed above the data.
    top = max(t.get_position()[1] for t in texts) if texts else None
    if top is not None:
        low, high = ax.get_ylim()
        ax.set_ylim(low, max(high, top + 1.5 * step))


def styled_boxplot(ax, data, labels):
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    box = ax.boxplot(
        data, tick_labels=labels, widths=0.6, patch_artist=True,
        medianprops=dict(color="black", linewidth=2),
        flierprops=dict(marker="o", markersize=5, markerfacecolor="none",
                        markeredgecolor=VERMILLION),
    )
    for patch in box["boxes"]:
        patch.set(facecolor=BLUE_FILL, edgecolor=BLUE, linewidth=1.5)
    for part in ("whiskers", "caps"):
        plt.setp(box[part], color=BLUE, linewidth=1.5)


def soy_salt(outdir: pathlib.Path) -> None:
    salt = np.array(SALT, dtype=float)
    q1, q3 = np.percentile(salt, [25, 75])
    mad = 1.4826 * np.median(np.abs(salt - np.median(salt)))
    print(
        f"soy salt: mean {salt.mean():.1f}, median {np.median(salt):.0f}, "
        f"sd {salt.std(ddof=1):.1f}, MAD {mad:.1f}, IQR {q3 - q1:.0f}"
    )

    fig, ax = plt.subplots(figsize=(6, 6))
    styled_boxplot(ax, [salt], [""])
    ax.set_ylabel("Salt content (mg / 15mL serving)")
    ax.set_xticks([])
    save(fig, outdir, "soy-salt-content.png")


def raw_material_index_plots(outdir: pathlib.Path) -> None:
    raw = fetch("raw-material-properties.csv")
    print(f"raw materials: {raw.shape[0]} rows, {raw.shape[1]} columns")

    labels = {
        "size1": "Particle size: level 1",
        "size2": "Particle size: level 2",
        "size3": "Particle size: level 3",
        "density1": "Particle density: level 1",
        "density2": "Particle density: level 2",
        "density3": "Particle density: level 3",
    }
    for column, identified in IDENTIFIED.items():
        values = raw[column].to_numpy(dtype=float)
        index = np.arange(1, len(values) + 1)
        flagged = raw["Sample"].isin(identified).to_numpy()
        print(f"  {column}: labelled {list(raw.loc[flagged, 'Sample'])}")

        fig, ax = plt.subplots(figsize=(7, 6.5))
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(index[~flagged], values[~flagged], "o", color=BLUE,
                markersize=8, markerfacecolor="none", markeredgewidth=1.6)
        ax.plot(index[flagged], values[flagged], "o", color=VERMILLION,
                markersize=9, markerfacecolor="none", markeredgewidth=2.2)
        # Label the flagged points, nudging the text away from the plot
        # edge so it does not run off the right-hand side. Several of
        # the six properties have missing values, so the span has to
        # ignore them.
        span = np.nanmax(values) - np.nanmin(values)
        texts = []
        for i, value, name in zip(index[flagged], values[flagged],
                                  raw.loc[flagged, "Sample"]):
            right = i < 0.72 * len(values)
            texts.append(
                ax.annotate(
                    name,
                    xy=(i, value),
                    xytext=(i + (1.4 if right else -1.4), value + 0.02 * span),
                    ha="left" if right else "right",
                    va="bottom",
                    color=VERMILLION,
                    fontsize=15,
                )
            )
        spread_labels_apart(fig, ax, texts)
        ax.set_xlabel("Index")
        ax.set_ylabel(labels[column])
        save(fig, outdir, f"{column}.png")


def hamilton_weather(outdir: pathlib.Path) -> None:
    for values, normal, ylabel, note, name in (
        (SNOWFALL, SNOWFALL_NORMAL, "Snowfall (cm)",
         "Total annual snowfall, averaged over 1971 to 2000 data",
         "snowfall-data.png"),
        (TEMPERATURE, TEMPERATURE_NORMAL,
         "Average annual temperature (°C)",
         "Average annual temperature, averaged over 1971 to 2000 data",
         "temperature-data.png"),
    ):
        fig, ax = plt.subplots(figsize=(12, 6))
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(YEARS, values, "-o", color=BLUE, linewidth=2, markersize=9)
        ax.axhline(normal, color=GREY, linewidth=2)
        ax.annotate(
            note,
            xy=(YEARS[-1], normal),
            xytext=(YEARS[-1], normal - 0.035 * (max(values) - min(values))),
            ha="right",
            va="top",
            color=GREY,
            fontsize=15,
        )
        ax.set_xlabel("Year")
        ax.set_ylabel(ylabel)
        ax.set_xticks(YEARS[::2])
        save(fig, outdir, name)


def confidence_interval_sketch(outdir: pathlib.Path) -> None:
    c = 1.96
    z = np.linspace(-4, 4, 801)
    density = stats.norm.pdf(z)

    fig, ax = plt.subplots(figsize=(12, 5.5))
    inside = (z >= -c) & (z <= c)
    ax.fill_between(z[inside], density[inside], color=BLUE_FILL)
    ax.plot(z, density, color=BLUE, linewidth=3)
    for bound in (-c, c):
        ax.axvline(bound, color=GREY, linewidth=1.5)
    ax.axhline(0, color="black", linewidth=1)
    ax.set_xticks([-c, c])
    ax.set_xticklabels(["$-c$", "$+c$"])
    ax.set_xlabel("$z$")
    ax.set_ylabel("$p(z)$")
    ax.set_xlim(-4, 4)
    ax.set_ylim(0, 0.42)
    save(fig, outdir, "show-confidence-interval.png")


def batch_yield_qqplot(outdir: pathlib.Path) -> None:
    yields = pd.read_csv(HERE / "batch-yields.csv")["Yield"].to_numpy(dtype=float)
    n = len(yields)
    # The exercise says to treat these 300 values as the whole
    # population, so the spread divides by n, not n - 1.
    mean, sd = yields.mean(), yields.std(ddof=0)
    z_bound = (60 - mean) / sd
    print(
        f"batch yields: n {n}, mean {mean:.3f}, sd {sd:.3f}, "
        f"z_bound {z_bound:.3f}, P {stats.norm.cdf(z_bound):.4f}"
    )

    ordered = np.sort(yields)
    # Blom plotting positions, as used by R's qqnorm().
    quantiles = stats.norm.ppf((np.arange(1, n + 1) - 0.375) / (n + 0.25))
    # Robust reference line through the first and third quartiles, which
    # is what car::qqPlot draws.
    q_data = np.percentile(yields, [25, 75])
    q_norm = stats.norm.ppf([0.25, 0.75])
    slope = (q_data[1] - q_data[0]) / (q_norm[1] - q_norm[0])
    intercept = q_data[0] - slope * q_norm[0]

    # Pointwise 95% envelope from the standard error of the order
    # statistics: se = (slope / density) * sqrt(p (1 - p) / n).
    p = stats.norm.cdf(quantiles)
    se = (slope / stats.norm.pdf(quantiles)) * np.sqrt(p * (1 - p) / n)
    fit = intercept + slope * quantiles

    fig, ax = plt.subplots(figsize=(7.5, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(quantiles, ordered, "o", color=BLUE, markersize=6,
            markerfacecolor="none", markeredgewidth=1.4)
    ax.plot(quantiles, fit, color=VERMILLION, linewidth=2.5,
            label="Reference line")
    ax.plot(quantiles, fit + 1.96 * se, "--", color=VERMILLION, linewidth=1.8,
            label="95% pointwise envelope")
    ax.plot(quantiles, fit - 1.96 * se, "--", color=VERMILLION, linewidth=1.8)
    ax.set_xlabel("Normal quantiles")
    ax.set_ylabel("Yield [%]")
    ax.legend(loc="upper left", frameon=False, fontsize=14)
    save(fig, outdir, "batch-yields-qqplot.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    soy_salt(outdir)
    raw_material_index_plots(outdir)
    hamilton_weather(outdir)
    confidence_interval_sketch(outdir)
    batch_yield_qqplot(outdir)
