"""The Dofasco breakout-economics figure for the process-monitoring chapter.

One committed PNG, replacing an image previously generated by the base-R
script ``breakouts-dofasco.R``, which wrote to a hard-coded path on the
author's laptop:

- ``breakouts-dofasco-economics.png``: breakouts per year at the Dofasco
  steel plant, 1988 to 2006, with 1997 marked. It supports the claim in
  ``process-monitoring/the-industrial-practice-of-process-monitoring.rst``
  that multivariate monitoring cut breakouts substantially from 1997.

Data: the nineteen counts are the ones in ``breakouts-dofasco.R``, taken
from slides provided by John MacGregor on 21 January 2010 and used with
permission. They are embedded here so the figure reproduces exactly.

Usage
-----
    uv run --with numpy --with matplotlib python dofasco_breakouts_figure.py [output_dir]

Writes the PNG into ``output_dir`` (default: this script's own
directory), refreshing the committed image in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np

BLUE = "#0072B2"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300

YEARS = np.arange(1988, 2007)
BREAKOUTS = [8, 17, 23, 8, 12, 11, 17, 18, 18, 8, 9, 4, 4, 4, 7, 4, 2, 3, 2]
MONITORING_FROM = 1997

mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.labelsize": 18,
        "xtick.labelsize": 14,
        "ytick.labelsize": 16,
        "axes.axisbelow": True,
    }
)


def main(outdir: pathlib.Path) -> None:
    before = np.array(BREAKOUTS)[YEARS < MONITORING_FROM].mean()
    after = np.array(BREAKOUTS)[YEARS >= MONITORING_FROM].mean()
    print(f"breakouts per year: {before:.1f} before {MONITORING_FROM}, "
          f"{after:.1f} from {MONITORING_FROM} onwards")

    fig, ax = plt.subplots(figsize=(12, 5))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(YEARS, BREAKOUTS, "-o", color=BLUE, linewidth=2, markersize=7)
    ax.axvline(MONITORING_FROM, color=VERMILLION, linewidth=2)
    ax.annotate(
        f"Multivariate monitoring\nfrom {MONITORING_FROM}",
        xy=(MONITORING_FROM, 23), xytext=(MONITORING_FROM + 0.4, 23),
        ha="left", va="top", color=VERMILLION, fontsize=15,
    )
    ax.set_xlabel("Year")
    ax.set_ylabel("Breakouts per year")
    ax.set_ylim(0, 25)
    ax.set_xticks(YEARS)
    ax.tick_params(axis="x", rotation=90)
    fig.tight_layout()
    fig.savefig(outdir / "breakouts-dofasco-economics.png", dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / 'breakouts-dofasco-economics.png'}")


if __name__ == "__main__":
    main(pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent)
