"""Room-temperature exercise figures for the PID book.

Two committed PNGs, replacing images previously generated by base-R
scripts (``room-temperature-plots.R``,
``room-temperature-sparklines.R``). They answer the exercise in
``data-visualization/data-visualization-exercises.rst`` that asks for
four temperature trajectories on one axis and then again as sparklines:

- ``room-temperatures.png``: the four corner temperatures of a room,
  plotted in sequence order on a single axis.
- ``room-temperature-sparklines.png``: the same four series stacked as
  sparklines, each on its own axis and named on the left. The R original
  printed a tick ladder beside each strip and no series names.

The four features the solution asks the reader to find are all still
visible: the roughly 48-sample daily cycle, the four series moving
together, the break in the two front temperatures around samples 50 to
60, and the spike in the back left temperature around sample 135.

Data: ``room-temperature.csv`` in this directory, four columns of
temperature in kelvin, one row per half-hour reading.

Usage
-----
    uv run --with numpy --with pandas --with matplotlib python room_temperature_figures.py [output_dir]

Writes the two PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

BLUE = "#0072B2"
ORANGE = "#E69F00"
GREEN = "#009E73"
BLACK = "#333333"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

# The four series overlap for most of the record, so each one carries a
# dash pattern as well as a colour: where two traces cross, or where a
# reader is working from a greyscale print, the pattern is what tells
# them apart. The colours are four widely separated hues from the
# Okabe-Ito set, which stay distinct under the common forms of colour
# blindness.
SERIES = {
    "FrontLeft": ("Front left", BLUE, "solid"),
    "FrontRight": ("Front right", ORANGE, (0, (6, 2))),
    "BackLeft": ("Back left", GREEN, (0, (7, 2, 1.5, 2))),
    "BackRight": ("Back right", BLACK, (0, (1.5, 1.6))),
}

mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)


def load() -> pd.DataFrame:
    return pd.read_csv(HERE / "room-temperature.csv")


def all_on_one_axis(temperatures: pd.DataFrame, outdir: pathlib.Path) -> None:
    order = np.arange(1, len(temperatures) + 1)
    fig, ax = plt.subplots(figsize=(14, 7))
    ax.grid(color=GRID, linewidth=0.8)
    for column, (label, colour, dashes) in SERIES.items():
        ax.plot(order, temperatures[column], color=colour, linewidth=1.5,
                linestyle=dashes, label=label)
    ax.set_xlabel("Sequence order")
    ax.set_ylabel("Room temperature [K]")
    ax.set_xlim(0, len(temperatures) + 1)
    ax.set_ylim(290, 300)
    ax.legend(loc="lower right", frameon=False, ncols=2)
    fig.tight_layout()
    fig.savefig(outdir / "room-temperatures.png", dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / 'room-temperatures.png'}")


def sparklines(temperatures: pd.DataFrame, outdir: pathlib.Path) -> None:
    order = np.arange(1, len(temperatures) + 1)
    fig, axes = plt.subplots(len(SERIES), 1, figsize=(11, 3.4), sharex=True)
    for ax, (column, (label, colour, _)) in zip(axes, SERIES.items()):
        # Each strip stands alone here, so the dash patterns used on the
        # combined axis are not needed; the colours carry over so the
        # two figures can be read against each other.
        ax.plot(order, temperatures[column], color=colour, linewidth=1.1)
        ax.set_ylim(290, 300)
        ax.set_xlim(0, len(temperatures) + 1)
        ax.set_xticks([])
        # A sparkline carries no axes; the range is stated once, on the
        # left, so the four strips can still be compared.
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_visible(False)
        ax.set_ylabel(label, rotation=0, ha="right", va="center", fontsize=14)
    axes[0].set_title("Room temperature, 290 to 300 K on every strip",
                      fontsize=15)
    fig.tight_layout(h_pad=0.4)
    fig.savefig(outdir / "room-temperature-sparklines.png", dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / 'room-temperature-sparklines.png'}")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    temperatures = load()
    print(f"{len(temperatures)} readings, "
          f"{temperatures.min().min():.1f} to {temperatures.max().max():.1f} K")
    all_on_one_axis(temperatures, outdir)
    sparklines(temperatures, outdir)
