"""Anscombe-example and outlier-diagnostic figures for the least-squares chapter.

Seven committed PNGs, replacing images previously generated by base-R
scripts (``show-anscombe-problem.R``, ``outlier-illustrations.R``):

- ``show-anscombe-problem-1.png``: the 11-point example data (the first
  Anscombe set), plotted before any model is fit.
- ``show-anscome-solution-marked.png``: the least squares fit with the
  slope drawn at its lower and upper confidence bound, both passing
  through (x-bar, y-bar). The historical filename spelling is kept.
- ``show-anscome-solution-with-yhat-bounds.png``: the fit with the
  prediction interval for y-hat at every x.
- ``influence-of-outliers.png``: models A, B and C, each with one
  square point that is discrepant (A), influential (B), or high
  leverage but not discrepant (C); solid line fits all points, dashed
  line omits the square point.
- ``hatvalue-of-outliers.png``: hat values for model A and for models
  B and C (identical x values, so identical hat values), with the
  1, 2 and 3 times average-hat-value lines.
- ``studentized-residuals.png``: externally studentized residuals for
  the three models.
- ``cooks-distance.png``: Cook's D for the three models. The seed is
  chosen so that, in model C, a point other than the square point has
  the largest influence, as the prose notes.

The 11-point x and y values are the ones printed in the chapter; the
A/B/C data are seeded so the committed images regenerate exactly.

Usage
-----
    uv run --with numpy --with scipy --with matplotlib python anscombe_outlier_figures.py [output_dir]
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

BLUE = "#0072B2"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300

X11 = np.array([10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5], dtype=float)
Y11 = np.array([8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68])

mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 19,
        "axes.labelsize": 19,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 13,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def _diagnostics(x, y):
    """Return fit, hat values, externally studentized residuals, Cook's D."""
    n, k = len(x), 2
    slope, intercept = np.polyfit(x, y, 1)
    e = y - (intercept + slope * x)
    ssx = np.sum((x - x.mean()) ** 2)
    h = 1 / n + (x - x.mean()) ** 2 / ssx
    rss = np.sum(e ** 2)
    se2 = rss / (n - k)
    student = e * np.sqrt((n - k - 1) / (rss * (1 - h) - e ** 2))
    cooks = (e ** 2 / (k * se2)) * (h / (1 - h) ** 2)
    return slope, intercept, h, student, cooks


def anscombe_figures(outdir: pathlib.Path) -> None:
    x, y = X11, Y11
    n, k = len(x), 2
    slope, intercept, h, student, cooks = _diagnostics(x, y)
    e = y - (intercept + slope * x)
    ssx = np.sum((x - x.mean()) ** 2)
    se = np.sqrt(np.sum(e ** 2) / (n - k))
    se_b1 = np.sqrt(se ** 2 / ssx)
    tcrit = stats.t.ppf(0.975, n - k)
    b1_lo, b1_hi = slope - tcrit * se_b1, slope + tcrit * se_b1

    def base_axes():
        fig, ax = plt.subplots(figsize=(7, 7))
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(x, y, "o", color=BLUE, markersize=9)
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        return fig, ax

    fig, ax = base_axes()
    save(fig, outdir, "show-anscombe-problem-1.png")

    fig, ax = base_axes()
    xr = np.array([0, 14])
    ax.plot(xr, intercept + slope * xr, color=VERMILLION, linewidth=2,
            label="Least squares fit")
    for b1, style, label in ((b1_lo, ":", "$b_1$ at its lower bound"),
                             (b1_hi, "--", "$b_1$ at its upper bound")):
        ax.plot(xr, y.mean() + b1 * (xr - x.mean()), color=GREY,
                linestyle=style, linewidth=2, label=label)
    ax.plot(x.mean(), y.mean(), "*", color="black", markersize=16)
    ax.set_xlim(0, 14)
    ax.set_ylim(0, 12)
    ax.legend(loc="upper left", frameon=False)
    save(fig, outdir, "show-anscome-solution-marked.png")

    fig, ax = base_axes()
    xn = np.linspace(2, 15, 300)
    yn = intercept + slope * xn
    delta = tcrit * se * np.sqrt(1 + 1 / n + (xn - x.mean()) ** 2 / ssx)
    ax.plot(xn, yn, color=VERMILLION, linewidth=2, label="Least squares fit")
    ax.plot(xn, yn + delta, color=GREY, linewidth=1.8,
            label="Bounds on the prediction, $\\hat{y}$")
    ax.plot(xn, yn - delta, color=GREY, linewidth=1.8)
    ax.plot(x.mean(), y.mean(), "*", color="black", markersize=16)
    ax.set_ylim(1, 12)
    ax.legend(loc="lower right", frameon=False)
    save(fig, outdir, "show-anscome-solution-with-yhat-bounds.png")


def _abc_models(seed: int):
    rng = np.random.default_rng(seed)
    N = 25
    x = rng.normal(10, 4, N)
    y = 4 * x - 6 + np.log(np.clip(x, 0.5, None)) + rng.normal(0, 3, N)
    slope, intercept = np.polyfit(x, y, 1)

    xa = np.append(x, x.mean())
    ya = np.append(y, intercept + slope * x.mean() + 30)
    xb = np.append(x, 25.0)
    yb = np.append(y, y.mean())
    xc = np.append(x, 25.0)
    yc = np.append(y, intercept + slope * 25.0 + rng.normal(0, 4))
    return (xa, ya), (xb, yb), (xc, yc)


def _pick_seed() -> int:
    # The prose notes that in model C a point OTHER than the square
    # point has the largest Cook's D; search for a seed where that
    # holds while B's square point clearly dominates its panel.
    for seed in range(200):
        (_, _), (xb, yb), (xc, yc) = _abc_models(seed)
        _, _, _, _, cooks_b = _diagnostics(xb, yb)
        _, _, _, _, cooks_c = _diagnostics(xc, yc)
        if np.argmax(cooks_b) == len(xb) - 1 and np.argmax(cooks_c) != len(xc) - 1:
            return seed
    raise RuntimeError("no suitable seed found")


def outlier_figures(outdir: pathlib.Path) -> None:
    seed = _pick_seed()
    print(f"model A/B/C seed: {seed}")
    models = _abc_models(seed)
    titles = ["Model A", "Model B", "Model C"]

    fig, axes = plt.subplots(1, 3, figsize=(16, 5.3), sharey=False)
    for ax, (xm, ym), title in zip(axes, models, titles):
        keep = np.arange(len(xm) - 1)
        full = np.polyfit(xm, ym, 1)
        part = np.polyfit(xm[keep], ym[keep], 1)
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(xm[keep], ym[keep], "o", color=BLUE, markersize=6, alpha=0.8)
        ax.plot(xm[-1], ym[-1], "s", color=VERMILLION, markersize=10,
                markerfacecolor="none", markeredgewidth=2.5)
        xr = np.array([xm.min() - 0.5, xm.max() + 0.5])
        ax.plot(xr, np.polyval(full, xr), color="black", linewidth=1.8,
                label="Model using all data")
        ax.plot(xr, np.polyval(part, xr), color="black", linewidth=1.8,
                linestyle="--", label="Model omitting the square point")
        ax.set_title(title, fontsize=18)
        ax.set_xlabel("x", fontsize=17)
        ax.set_ylabel("y", fontsize=17)
        ax.tick_params(labelsize=15)
        ax.legend(loc="upper left", frameon=False, fontsize=12)
    save(fig, outdir, "influence-of-outliers.png")

    # Hat values: models B and C share the same x values.
    (xa, ya), (xb, yb), _ = models
    fig, axes = plt.subplots(1, 2, figsize=(16, 5.3), sharey=True)
    for ax, xm, ym, title in ((axes[0], xa, ya, "Model A"),
                              (axes[1], xb, yb, "Models B and C (the same values)")):
        _, _, h, _, _ = _diagnostics(xm, ym)
        hbar = 2 / len(xm)
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(np.arange(1, len(xm)), h[:-1], "o", color=BLUE, markersize=7,
                alpha=0.8)
        ax.plot(len(xm), h[-1], "s", color=VERMILLION, markersize=10,
                markerfacecolor="none", markeredgewidth=2.5)
        for mult, colour in ((1, "black"), (2, ORANGE), (3, VERMILLION)):
            ax.axhline(mult * hbar, color=colour, linestyle="--", linewidth=1.5)
            ax.text(1.5, mult * hbar + 0.005,
                    rf"${mult}\times\bar{{h}}$" if mult > 1 else r"$\bar{h}$",
                    fontsize=14)
        ax.set_title(title, fontsize=18)
        ax.set_xlabel("Order of the x-data", fontsize=17)
        ax.tick_params(labelsize=15)
    axes[0].set_ylabel("Hat value, $h_i$", fontsize=17)
    save(fig, outdir, "hatvalue-of-outliers.png")

    for name, index, ylabel in (
        ("studentized-residuals.png", 3, "Studentized residual, $e_i^*$"),
        ("cooks-distance.png", 4, "Cook's D, $D_i$"),
    ):
        fig, axes = plt.subplots(1, 3, figsize=(16, 5.3), sharey=True)
        for ax, (xm, ym), title in zip(axes, models, titles):
            values = _diagnostics(xm, ym)[index]
            ax.grid(color=GRID, linewidth=0.8)
            ax.plot(np.arange(1, len(xm)), values[:-1], "o", color=BLUE,
                    markersize=7, alpha=0.8)
            ax.plot(len(xm), values[-1], "s", color=VERMILLION, markersize=10,
                    markerfacecolor="none", markeredgewidth=2.5)
            ax.axhline(0, color="black", linewidth=1)
            ax.set_title(title, fontsize=18)
            ax.set_xlabel("Order of the x-data", fontsize=17)
            ax.tick_params(labelsize=15)
        axes[0].set_ylabel(ylabel, fontsize=17)
        save(fig, outdir, name)


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    anscombe_figures(outdir)
    outlier_figures(outdir)
