"""LDPE question figures for the least-squares chapter of the PID book.

Nine committed PNGs, replacing images previously generated by the base-R
script ``LDPE-question.R``. They work through building and criticising a
one-variable model of short-chain branching (SCB) on the reactor zone-2
conversion (z2), for the low-density polyethylene reactor described at
https://openmv.net/info/ldpe:

- ``ldpe-scatterplot-matrix.png``: the five variables the question uses
  (Tmax1, Tmax2, z1, z2, SCB).
- ``ldpe-z2-SCB-raw-data-identify.png``: SCB against z2 with the least
  squares line, and the four high-leverage observations named.
- ``ldpe-z2-SCB-resids-qqplot.png``: a normal q-q plot of the residuals.
- ``ldpe-z2-SCB-raw-resids-in-order.png``: the residuals in run order.
- ``ldpe-z2-SCB-predictions-vs-residuals.png``: predictions against
  residuals, where the structure the question asks about shows up.
- ``ldpe-z2-SCB-predictions-vs-actual.png``: predicted against observed
  SCB, with the 45-degree line.
- ``ldpe-z2-SCB-hat-values.png``: leverage of each observation, with the
  2 h-bar and 3 h-bar guides.
- ``ldpe-z2-SCB-hats-again.png``: the same leverages after the four
  high-leverage observations are removed.
- ``ldpe-z2-SCB-iip-before.png`` and ``ldpe-z2-SCB-iip-after.png``: the
  influence index plots (studentized residual, hat value and Cook's
  distance) before and after that removal.

Four of the originals were stored with a ``.jpg`` extension. The
``identify()`` calls in the R script required the reader to click on
points; the observations they named (51, 52, 53, 54, and 27 in the
updated model) are listed in ``FLAGGED`` so the same annotations appear
without an interactive session.

Data is fetched from openmv.net; a local ``LDPE.csv`` next to this
script is used as a fallback when offline. The script prints the model
coefficients, R2 and leverage cut-offs.

Usage
-----
    uv run --with numpy --with pandas --with scipy --with matplotlib python ldpe_question_figures.py [output_dir]

Writes the nine PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

BLUE = "#0072B2"
BLUE_FILL = "#B3D4EA"
GREEN = "#009E73"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

COLUMNS = ["Tmax1", "Tmax2", "z1", "z2", "SCB"]
# Observations the R script's identify() calls picked out, one-based.
FLAGGED = [51, 52, 53, 54]
# The three the original names once 51 to 54 are gone: 27 stands above
# 3h-bar, and 38 and 41 are the next two along.
FLAGGED_AFTER = [27, 38, 41]
# The points the original named on the raw-data plot. R's identify()
# labels whatever is clicked, so the set is recorded here rather than
# recomputed; it is the ring of points furthest from the fitted line.
IDENTIFIED_RAW = [4, 7, 8, 16, 19, 21, 26, 33, 35, 36, 49, 52, 53, 54]

mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 15,
        "ytick.labelsize": 15,
        "legend.fontsize": 14,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def fetch() -> pd.DataFrame:
    try:
        return pd.read_csv("https://openmv.net/file/LDPE.csv")
    except Exception:
        return pd.read_csv(HERE / "LDPE.csv")


class SimpleModel:
    """Least squares fit of y on a single x, with the usual diagnostics."""

    def __init__(self, x: np.ndarray, y: np.ndarray) -> None:
        self.x, self.y = np.asarray(x, float), np.asarray(y, float)
        self.n = len(self.x)
        self.slope, self.intercept = np.polyfit(self.x, self.y, 1)
        self.fitted = self.intercept + self.slope * self.x
        self.residuals = self.y - self.fitted
        self.dof = self.n - 2
        self.se = np.sqrt((self.residuals ** 2).sum() / self.dof)
        centred = self.x - self.x.mean()
        # Leverage for a straight-line fit.
        self.hat = 1 / self.n + centred ** 2 / (centred ** 2).sum()
        self.r2 = 1 - (self.residuals ** 2).sum() / ((self.y - self.y.mean()) ** 2).sum()

    @property
    def studentized(self) -> np.ndarray:
        """Externally studentized residuals."""
        internal = self.residuals / (self.se * np.sqrt(1 - self.hat))
        return internal * np.sqrt((self.dof - 1) / (self.dof - internal ** 2))

    @property
    def cooks(self) -> np.ndarray:
        internal = self.residuals / (self.se * np.sqrt(1 - self.hat))
        return internal ** 2 / 2 * self.hat / (1 - self.hat)

    def describe(self, label: str) -> None:
        print(f"  {label}: n {self.n}, SCB = {self.intercept:.2f} + "
              f"{self.slope:.3f} z2, R2 {self.r2:.3f}, S_E {self.se:.4f}")


def robust_line(x: np.ndarray, y: np.ndarray, tuning: float = 1.345,
                iterations: int = 50) -> tuple[float, float]:
    """Huber M-estimate of intercept and slope, as ``MASS::rlm`` gives.

    ``car::qqPlot`` applied to a fitted model draws its reference line
    this way (``line = "robust"``), not through the quartiles, which is
    the default only when ``qqPlot`` is handed a bare vector. The
    difference is not cosmetic: the quartiles of a studentized-residual
    sample sit wider than the reference distribution's, so a quartile
    line comes out steeper, and the confidence envelope, which is scaled
    by that slope, comes out wider with it.
    """
    slope, intercept = np.polyfit(x, y, 1)
    for _ in range(iterations):
        residual = y - (intercept + slope * x)
        spread = np.median(np.abs(residual - np.median(residual))) / 0.6745
        if spread <= 0:
            break
        scaled = residual / spread
        weight = np.where(np.abs(scaled) <= tuning, 1.0,
                          tuning / np.maximum(np.abs(scaled), 1e-12))
        design = np.column_stack([np.ones_like(x), x])
        weighted = design * weight[:, None]
        intercept, slope = np.linalg.solve(design.T @ weighted, weighted.T @ y)
    return float(intercept), float(slope)


def label_points(ax, x, y, which, colour=VERMILLION, dy=0.0):
    for index in which:
        i = index - 1
        ax.plot(x[i], y[i], "o", color=colour, markersize=9,
                markerfacecolor="none", markeredgewidth=2.2)
        ax.annotate(f"{index}", xy=(x[i], y[i]), xytext=(x[i], y[i] + dy),
                    color=colour, fontsize=14, ha="center", va="bottom")


def scatterplot_matrix(frame: pd.DataFrame, outdir: pathlib.Path) -> None:
    n = len(COLUMNS)
    fig, axes = plt.subplots(n, n, figsize=(13, 13))
    for row, y_name in enumerate(COLUMNS):
        for col, x_name in enumerate(COLUMNS):
            ax = axes[row, col]
            if row == col:
                # R's pairs() puts the variable's name on the diagonal.
                ax.text(0.5, 0.5, x_name, transform=ax.transAxes,
                        ha="center", va="center", fontsize=20)
                ax.set_xticks([])
                ax.set_yticks([])
                continue
            ax.grid(color=GRID, linewidth=0.6)
            ax.plot(frame[x_name], frame[y_name], "o", color=BLUE,
                    markersize=3.5, markerfacecolor="none",
                    markeredgewidth=0.9)
            if row != n - 1:
                ax.set_xticklabels([])
            if col != 0:
                ax.set_yticklabels([])
            ax.tick_params(labelsize=11)
    save(fig, outdir, "ldpe-scatterplot-matrix.png")


def influence_index_plot(model: SimpleModel, flagged, outdir, name, title):
    """The four panels of ``car::influenceIndexPlot``, in its order.

    Cook's distance, studentized residual, Bonferroni p-value, hat
    value. The Bonferroni panel is the outlier test: the two-sided
    p-value for each studentized residual, multiplied by the number of
    observations, since every point is being tested. It is included
    because the exercise text tells the reader they may ignore it, which
    only makes sense if it is on the page.

    Each panel is drawn as a stem, a vertical drop to the baseline under
    every observation, which is how the original reads the index off the
    x-axis.
    """
    index = np.arange(1, model.n + 1)
    outlier_p = 2 * stats.t.sf(np.abs(model.studentized), df=model.n - 3)
    bonferroni = np.minimum(1.0, model.n * outlier_p)
    panels = [
        (model.cooks, "Cook's distance", 0.0),
        (model.studentized, "Studentized residuals", 0.0),
        (bonferroni, "Bonferroni p-value", 1.0),
        (model.hat, "hat-values", 0.0),
    ]
    fig, axes = plt.subplots(4, 1, figsize=(10, 12), sharex=True)
    for ax, (values, label, baseline) in zip(axes, panels):
        ax.grid(color=GRID, linewidth=0.8)
        ax.vlines(index, baseline, values, color=BLUE, linewidth=1.0)
        ax.plot(index, values, "o", color=BLUE, markersize=5,
                markerfacecolor="none", markeredgewidth=1.2)
        ax.axhline(baseline, color=GREY, linewidth=1)
        ax.set_ylabel(label, fontsize=15)
        label_points(ax, index, values, flagged,
                     dy=0.05 * (np.nanmax(values) - np.nanmin(values)))
    axes[0].set_title(title)
    axes[-1].set_xlabel("Observation number")
    save(fig, outdir, name)


def main(outdir: pathlib.Path) -> None:
    ldpe = fetch()
    frame = ldpe[COLUMNS]
    z2 = frame["z2"].to_numpy(dtype=float)
    scb = frame["SCB"].to_numpy(dtype=float)
    print(f"LDPE: {len(frame)} observations")

    model = SimpleModel(z2, scb)
    model.describe("SCB on z2, all data")
    index = np.arange(1, model.n + 1)

    scatterplot_matrix(frame, outdir)

    # 1. Raw data with the least squares line, high-leverage points named.
    fig, ax = plt.subplots(figsize=(8, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(z2, scb, "o", color=BLUE, markersize=6, markerfacecolor="none",
            markeredgewidth=1.4)
    edge = np.array([z2.min(), z2.max()])
    ax.plot(edge, model.intercept + model.slope * edge, color=VERMILLION,
            linewidth=2.5)
    label_points(ax, z2, scb, IDENTIFIED_RAW, dy=0.02 * np.ptp(scb))
    ax.set_xlabel("Conversion in zone 2, z2")
    ax.set_ylabel("Short-chain branching, SCB")
    save(fig, outdir, "ldpe-z2-SCB-raw-data-identify.png")

    # 2. Normal q-q plot. The solution text calls these the studentized
    # residuals, which is also what car::qqPlot draws for a model object.
    # car::qqPlot draws studentized residuals against t quantiles, with
    # a reference line through the quartiles and the 95% pointwise
    # envelope around it. The envelope is what says whether the tails
    # have strayed far enough to matter.
    # The reference line is the robust fit, which is what
    # ``car::qqPlot`` uses on a model object. Fitting it through the
    # quartiles instead gives a slope of 1.155 here rather than 1.014,
    # and since the envelope is scaled by the slope, it comes out wider
    # with it.
    studentized = model.studentized
    ordered = np.sort(studentized)
    tdist = stats.t(df=model.n - 3)
    probability = (np.arange(1, model.n + 1) - 0.5) / model.n
    quantiles = tdist.ppf(probability)
    intercept, slope = robust_line(quantiles, ordered)
    print(f"  q-q reference line: slope {slope:.3f}, intercept {intercept:+.3f}")
    reference = intercept + slope * quantiles
    half_width = stats.norm.ppf(0.975) * (slope / tdist.pdf(quantiles)) * np.sqrt(
        probability * (1 - probability) / model.n)
    fig, ax = plt.subplots(figsize=(8, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(quantiles, reference, color=VERMILLION, linewidth=2.5)
    ax.plot(quantiles, reference - half_width, "--", color=VERMILLION, linewidth=1.5)
    ax.plot(quantiles, reference + half_width, "--", color=VERMILLION, linewidth=1.5)
    ax.plot(quantiles, ordered, "o", color=BLUE, markersize=6,
            markerfacecolor="none", markeredgewidth=1.4)
    pad = 0.08 * np.ptp(ordered)
    ax.set_ylim(ordered.min() - pad, ordered.max() + pad)
    ax.set_xlabel("t quantiles")
    ax.set_ylabel("Studentized residuals")
    save(fig, outdir, "ldpe-z2-SCB-resids-qqplot.png")

    # 3. Residuals in run order.
    fig, ax = plt.subplots(figsize=(9, 6))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(index, model.residuals, "-o", color=BLUE, markersize=5, linewidth=0.9)
    ax.axhline(0, color=GREY, linewidth=1.5)
    ax.set_xlabel("Observation number")
    ax.set_ylabel("Residuals")
    save(fig, outdir, "ldpe-z2-SCB-raw-resids-in-order.png")

    # 4. Predictions against residuals: the structure the question is after.
    fig, ax = plt.subplots(figsize=(8, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(model.fitted, model.residuals, "o", color=BLUE, markersize=6,
            markerfacecolor="none", markeredgewidth=1.4)
    ax.axhline(0, color=GREY, linewidth=1.5)
    ax.set_xlabel("Predicted SCB")
    ax.set_ylabel("Residuals")
    save(fig, outdir, "ldpe-z2-SCB-predictions-vs-residuals.png")

    # 5. Predicted against observed.
    fig, ax = plt.subplots(figsize=(8, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(scb, model.fitted, "o", color=BLUE, markersize=6,
            markerfacecolor="none", markeredgewidth=1.4)
    span = np.array([min(scb.min(), model.fitted.min()),
                     max(scb.max(), model.fitted.max())])
    ax.plot(span, span, color=VERMILLION, linewidth=2)
    ax.set_xlabel("Observed SCB")
    ax.set_ylabel("Predicted SCB")
    ax.set_aspect("equal")
    save(fig, outdir, "ldpe-z2-SCB-predictions-vs-actual.png")

    # 6 and 7. Leverage, before and after removing the four points.
    for values, flagged, name, title in (
        (model, FLAGGED, "ldpe-z2-SCB-hat-values.png", "All observations"),
        (SimpleModel(np.delete(z2, [i - 1 for i in FLAGGED]),
                     np.delete(scb, [i - 1 for i in FLAGGED])),
         FLAGGED_AFTER, "ldpe-z2-SCB-hats-again.png",
         "After removing observations 51 to 54"),
    ):
        average = 2 / values.n
        idx = np.arange(1, values.n + 1)
        fig, ax = plt.subplots(figsize=(9, 6))
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(idx, values.hat, "o", color=BLUE, markersize=6,
                markerfacecolor="none", markeredgewidth=1.4)
        ax.axhline(2 * average, color=GREEN, linewidth=2)
        ax.axhline(3 * average, color=VERMILLION, linewidth=2)
        ax.text(1, 2 * average, r" $2\bar{h}$", color=GREEN, va="bottom")
        ax.text(1, 3 * average, r" $3\bar{h}$", color=VERMILLION, va="bottom")
        label_points(ax, idx, values.hat, flagged, dy=0.02 * np.ptp(values.hat))
        ax.set_title(title)
        ax.set_xlabel("Observation number")
        ax.set_ylabel("Hat value (leverage)")
        save(fig, outdir, name)
        print(f"  {title}: h-bar {average:.4f}, "
              f"{(values.hat > 3 * average).sum()} points beyond 3 h-bar")

    # 8 and 9. Influence index plots.
    influence_index_plot(model, FLAGGED, outdir, "ldpe-z2-SCB-iip-before.png",
                         "Influence index plot: all observations")
    updated = SimpleModel(np.delete(z2, [i - 1 for i in FLAGGED]),
                          np.delete(scb, [i - 1 for i in FLAGGED]))
    updated.describe("SCB on z2, without 51 to 54")
    influence_index_plot(updated, FLAGGED_AFTER, outdir,
                         "ldpe-z2-SCB-iip-after.png",
                         "Influence index plot: after removing 51 to 54")


if __name__ == "__main__":
    main(pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE)
