"""Exercise figures for the least-squares chapter of the PID book.

Twelve committed PNGs, replacing images previously generated by base-R
scripts (``distillation-column-questions.R``,
``distillation-least-squares.R``, ``kappa-number-autocorrelation.R``,
``bioreactor-regression-assignment.R``, ``bioreactor-ML-regression.R``,
``CO2-gas-furnace-question.R``, ``cheddar-cheese.R``). These serve
``least-squares-modelling/least-squares-exercises.rst``:

- ``distillation-least-squares.png``: vapour pressure against tray
  temperature with the least squares line and its prediction interval.
- ``distillation-prediction-interval.png``: the same fit with the
  prediction intervals drawn at three new temperatures, 430, 480 and
  520 degrees F.
- ``distillation-prediction-inverted-temperature.png``: vapour pressure
  against the reciprocal of temperature, which is what the underlying
  physics suggests.
- ``distillation-prediction-qqplots.png``: normal q-q plots of the two
  models' residuals, side by side.
- ``distillation-influence-plot.png``: studentized residual against
  leverage, with Cook's distance shown by marker area.
- ``kappa-number-autocorrelation.png``: the autocorrelation function of
  the Kappa number, raw and after subsampling every fifth value.
- ``kappa-number-autocorrelation-scatterplots.png``: the same series
  plotted against itself at lags 0 to 5.
- ``bioreactor-scatterplot-matrix.png``: the five bioreactor variables.
- ``bioreactor-residuals-qq-plot.png``: residuals from the model that
  uses temperature, speed and baffles together.
- ``CO2-gas-furnace-raw-data.png``: carbon dioxide against gas flow
  rate, with a smoother and the least squares line.
- ``CO2-gas-furnace-residuals.png``: a normal q-q plot of that model's
  residuals.
- ``cheese-data-correlation.png``: the four cheddar-cheese variables.

All datasets are fetched from openmv.net; a local CSV of the same name
next to this script is used as a fallback when offline. The script
prints the coefficients, standard errors and correlations that the
solutions quote.

Usage
-----
    uv run --with numpy --with pandas --with scipy --with matplotlib python least_squares_exercise_figures.py [output_dir]

Writes the twelve PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

BLUE = "#0072B2"
BLUE_FILL = "#B3D4EA"
GREEN = "#009E73"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 15,
        "ytick.labelsize": 15,
        "legend.fontsize": 14,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def fetch(name: str) -> pd.DataFrame:
    try:
        return pd.read_csv(f"https://openmv.net/file/{name}")
    except Exception:
        return pd.read_csv(HERE / name)


class Fit:
    """Straight-line least squares fit with the usual diagnostics."""

    def __init__(self, x, y) -> None:
        self.x, self.y = np.asarray(x, float), np.asarray(y, float)
        self.n = len(self.x)
        self.slope, self.intercept = np.polyfit(self.x, self.y, 1)
        self.fitted = self.intercept + self.slope * self.x
        self.residuals = self.y - self.fitted
        self.dof = self.n - 2
        self.se = np.sqrt((self.residuals ** 2).sum() / self.dof)
        self.centred = self.x - self.x.mean()
        self.sxx = (self.centred ** 2).sum()
        self.hat = 1 / self.n + self.centred ** 2 / self.sxx
        self.r2 = 1 - (self.residuals ** 2).sum() / ((self.y - self.y.mean()) ** 2).sum()

    def prediction_interval(self, x_new, level: float = 0.95):
        x_new = np.asarray(x_new, float)
        fit = self.intercept + self.slope * x_new
        spread = self.se * np.sqrt(1 + 1 / self.n + (x_new - self.x.mean()) ** 2 / self.sxx)
        critical = stats.t.ppf(0.5 + level / 2, df=self.dof)
        return fit, fit - critical * spread, fit + critical * spread

    @property
    def studentized(self):
        internal = self.residuals / (self.se * np.sqrt(1 - self.hat))
        return internal * np.sqrt((self.dof - 1) / (self.dof - internal ** 2))

    @property
    def cooks(self):
        internal = self.residuals / (self.se * np.sqrt(1 - self.hat))
        return internal ** 2 / 2 * self.hat / (1 - self.hat)


def qq_panel(ax, values, label: str) -> None:
    ordered = np.sort(values)
    n = len(ordered)
    quantiles = stats.norm.ppf((np.arange(1, n + 1) - 0.375) / (n + 0.25))
    q_data = np.percentile(values, [25, 75])
    q_norm = stats.norm.ppf([0.25, 0.75])
    slope = (q_data[1] - q_data[0]) / (q_norm[1] - q_norm[0])
    intercept = q_data[0] - slope * q_norm[0]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(quantiles, ordered, "o", color=BLUE, markersize=5,
            markerfacecolor="none", markeredgewidth=1.3)
    ax.plot(quantiles, intercept + slope * quantiles, color=VERMILLION,
            linewidth=2.5)
    ax.set_xlabel("Normal quantiles")
    ax.set_ylabel(label)


def pairs_plot(frame: pd.DataFrame, outdir: pathlib.Path, name: str,
               size: float = 12) -> None:
    columns = list(frame.columns)
    n = len(columns)
    fig, axes = plt.subplots(n, n, figsize=(size, size))
    for row, y_name in enumerate(columns):
        for col, x_name in enumerate(columns):
            ax = axes[row, col]
            ax.grid(color=GRID, linewidth=0.6)
            if row == col:
                ax.hist(frame[x_name], bins=12, color=BLUE_FILL,
                        edgecolor=BLUE, linewidth=1.0)
            else:
                ax.plot(frame[x_name], frame[y_name], "o", color=BLUE,
                        markersize=3.5, markerfacecolor="none",
                        markeredgewidth=0.9)
            if row == 0:
                ax.set_title(x_name)
            if col == 0:
                ax.set_ylabel(y_name)
            if row != n - 1:
                ax.set_xticklabels([])
            if col != 0 or row == col:
                ax.set_yticklabels([])
            ax.tick_params(labelsize=11)
    save(fig, outdir, name)


def lowess(x, y, frac: float = 0.5, gridsize: int = 80):
    order = np.argsort(x)
    xs, ys = np.asarray(x, float)[order], np.asarray(y, float)[order]
    span = max(2, int(frac * len(xs)))
    grid = np.linspace(xs.min(), xs.max(), gridsize)
    fitted = np.empty_like(grid)
    for i, x0 in enumerate(grid):
        distance = np.abs(xs - x0)
        cutoff = np.sort(distance)[span - 1]
        w = np.clip(1 - (distance / max(cutoff, 1e-12)) ** 3, 0, None) ** 3
        total = w.sum()
        xm, ym = (w * xs).sum() / total, (w * ys).sum() / total
        slope = (w * (xs - xm) * (ys - ym)).sum() / max((w * (xs - xm) ** 2).sum(), 1e-12)
        fitted[i] = ym + slope * (x0 - xm)
    return grid, fitted


# --------------------------------------------------------------------
def distillation(outdir: pathlib.Path) -> None:
    tower = fetch("distillation-tower.csv")
    temperature = tower["TempC2"].to_numpy(dtype=float)
    pressure = tower["VapourPressure"].to_numpy(dtype=float)
    model = Fit(temperature, pressure)
    print(f"distillation: n {model.n}, VP = {model.intercept:.1f} "
          f"{model.slope:+.4f} T, R2 {model.r2:.3f}, S_E {model.se:.3f}")

    # 1. Raw data, least squares line, prediction interval band.
    grid = np.linspace(temperature.min(), temperature.max(), 200)
    fit, low, high = model.prediction_interval(grid, level=0.99)
    fig, ax = plt.subplots(figsize=(9, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(temperature, pressure, "o", color=BLUE, markersize=5,
            markerfacecolor="none", markeredgewidth=1.2)
    ax.plot(grid, fit, color=VERMILLION, linewidth=2.5, label="Least squares fit")
    ax.plot(grid, low, "--", color=VERMILLION, linewidth=1.8,
            label="99% prediction interval")
    ax.plot(grid, high, "--", color=VERMILLION, linewidth=1.8)
    ax.set_xlabel("Tray temperature [°F]")
    ax.set_ylabel("Vapour pressure [kPa]")
    ax.legend(loc="upper right", frameon=False)
    save(fig, outdir, "distillation-least-squares.png")

    # 2. Prediction intervals at three new temperatures.
    new = np.array([430.0, 480.0, 520.0])
    fit_new, low_new, high_new = model.prediction_interval(new)
    for t, f, lo, hi in zip(new, fit_new, low_new, high_new):
        print(f"  T = {t:.0f}: fit {f:.2f}, 95% PI {lo:.2f} to {hi:.2f}")
    fig, ax = plt.subplots(figsize=(9, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(temperature, pressure, "o", color=BLUE, markersize=5,
            markerfacecolor="none", markeredgewidth=1.2)
    edge = np.array([temperature.min(), temperature.max()])
    ax.plot(edge, model.intercept + model.slope * edge, color=VERMILLION,
            linewidth=2.5)
    ax.errorbar(new, fit_new, yerr=[fit_new - low_new, high_new - fit_new],
                fmt="o", color=ORANGE, markersize=9, capsize=8, elinewidth=2.5,
                capthick=2.5, zorder=5)
    ax.set_title("Visualizing the prediction intervals")
    ax.set_xlabel("Tray temperature [°F]")
    ax.set_ylabel("Vapour pressure [kPa]")
    ax.set_ylim(17, 65)
    save(fig, outdir, "distillation-prediction-interval.png")

    # 3. Vapour pressure against the reciprocal of temperature.
    inverse = 1 / temperature
    model_inv = Fit(inverse, pressure)
    print(f"  inverted model: R2 {model_inv.r2:.3f}, S_E {model_inv.se:.3f}")
    fig, ax = plt.subplots(figsize=(9, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(inverse, pressure, "o", color=BLUE, markersize=5,
            markerfacecolor="none", markeredgewidth=1.2)
    edge = np.array([inverse.min(), inverse.max()])
    ax.plot(edge, model_inv.intercept + model_inv.slope * edge, color=VERMILLION,
            linewidth=2.5, label="Least squares fit")
    smooth_x, smooth_y = lowess(inverse, pressure, frac=0.4)
    ax.plot(smooth_x, smooth_y, "--", color=GREEN, linewidth=2.2,
            label="LOESS smoother")
    ax.set_xlabel("1 / temperature [1/°F]")
    ax.set_ylabel("Vapour pressure [kPa]")
    ax.legend(loc="upper left", frameon=False)
    save(fig, outdir, "distillation-prediction-inverted-temperature.png")

    # 4. The two q-q plots side by side.
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    qq_panel(axes[0], model.studentized, "Studentized residuals")
    axes[0].set_title("Model with temperature")
    qq_panel(axes[1], model_inv.studentized, "Studentized residuals")
    axes[1].set_title("Model with inverted temperature")
    save(fig, outdir, "distillation-prediction-qqplots.png")

    # 5. Influence plot for the model built on the first 159 samples.
    build = slice(0, 159)
    model_sub = Fit(temperature[build], pressure[build])
    area = 60 + 3000 * model_sub.cooks
    fig, ax = plt.subplots(figsize=(9, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.scatter(model_sub.hat, model_sub.studentized, s=area, facecolors="none",
               edgecolors=BLUE, linewidths=1.6)
    ax.axhline(0, color=GREY, linewidth=1.2)
    for level, colour in ((2, GREEN), (3, VERMILLION)):
        ax.axhline(level, color=colour, linestyle="--", linewidth=1.5)
        ax.axhline(-level, color=colour, linestyle="--", linewidth=1.5)
    ax.axvline(2 * 2 / model_sub.n, color=GREEN, linestyle="--", linewidth=1.5)
    ax.axvline(3 * 2 / model_sub.n, color=VERMILLION, linestyle="--", linewidth=1.5)
    # Name the observations the solution removes.
    for index in (38, 53, 84, 101):
        i = index - 1
        ax.annotate(f"{index}", xy=(model_sub.hat[i], model_sub.studentized[i]),
                    xytext=(model_sub.hat[i], model_sub.studentized[i] + 0.28),
                    ha="center", color=VERMILLION, fontsize=14)
    ax.set_title("Marker area is proportional to Cook's distance")
    ax.set_xlabel("Hat value (leverage)")
    ax.set_ylabel("Studentized residuals")
    save(fig, outdir, "distillation-influence-plot.png")


def kappa_autocorrelation(outdir: pathlib.Path) -> None:
    kappa = fetch("kappa-number.csv")["Kappa"].to_numpy(dtype=float)
    jumps = 5
    subsampled = kappa[::jumps]

    def acf(series, lags: int = 50):
        centred = series - series.mean()
        denominator = (centred ** 2).sum()
        return np.array([1.0] + [float((centred[:-k] * centred[k:]).sum() / denominator)
                                 for k in range(1, lags + 1)])

    full, thinned = acf(kappa), acf(subsampled)
    band = 1.96 / np.sqrt(len(kappa))
    print(f"kappa: lag-1 autocorrelation {full[1]:.3f} raw, "
          f"{thinned[1]:.3f} after subsampling every {jumps}th value")

    fig, axes = plt.subplots(2, 1, figsize=(12, 10))
    for ax, values, title, n in (
        (axes[0], full, "Autocorrelation for the Kappa number variable", len(kappa)),
        (axes[1], thinned,
         f"Autocorrelation after subsampling every {jumps}th value", len(subsampled)),
    ):
        lags = np.arange(len(values))
        ax.grid(color=GRID, linewidth=0.8)
        ax.vlines(lags, 0, values, color=BLUE, linewidth=2)
        ax.axhline(0, color="black", linewidth=1)
        for sign in (1, -1):
            ax.axhline(sign * 1.96 / np.sqrt(n), color=VERMILLION,
                       linestyle="--", linewidth=1.5)
        ax.set_title(title)
        ax.set_ylabel("Autocorrelation")
        ax.set_ylim(-0.25, 1.05)
    axes[-1].set_xlabel("Lag")
    save(fig, outdir, "kappa-number-autocorrelation.png")

    # The same series against itself, at lags 0 to 5.
    fig, axes = plt.subplots(1, jumps + 1, figsize=(20, 4.2))
    for lag, ax in enumerate(axes):
        left = kappa[: len(kappa) - lag] if lag else kappa
        right = kappa[lag:] if lag else kappa
        correlation = float(np.corrcoef(left, right)[0, 1])
        ax.grid(color=GRID, linewidth=0.6)
        ax.plot(left, right, "o", color=BLUE, markersize=2, alpha=0.35)
        grid, fitted = lowess(left, right, frac=0.4, gridsize=40)
        ax.plot(grid, fitted, color=VERMILLION, linewidth=2)
        ax.set_title(f"Lag {lag}: r = {correlation:.2f}", fontsize=15)
        ax.set_xlabel("Kappa$_k$", fontsize=14)
        if lag == 0:
            ax.set_ylabel("Kappa$_{k+\\mathrm{lag}}$", fontsize=14)
        ax.tick_params(labelsize=12)
    save(fig, outdir, "kappa-number-autocorrelation-scatterplots.png")


def bioreactor(outdir: pathlib.Path) -> None:
    bio = fetch("bioreactor-yields.csv")
    numeric = bio.copy()
    # "baffles" is Yes/No; code it so it can go into the model and the plot.
    numeric["baffles"] = (numeric["baffles"].str.strip().str.lower() == "yes").astype(float)
    pairs_plot(numeric, outdir, "bioreactor-scatterplot-matrix.png", size=12)

    predictors = numeric[["temperature", "speed", "baffles"]].to_numpy(dtype=float)
    y = numeric["yield"].to_numpy(dtype=float)
    design = np.column_stack([np.ones(len(y)), predictors])
    coefficients, *_ = np.linalg.lstsq(design, y, rcond=None)
    residuals = y - design @ coefficients
    print("bioreactor: yield = "
          f"{coefficients[0]:.2f} + {coefficients[1]:.3f} temperature "
          f"+ {coefficients[2]:.5f} speed + {coefficients[3]:.2f} baffles")

    fig, ax = plt.subplots(figsize=(8, 7))
    qq_panel(ax, residuals, "Residuals")
    save(fig, outdir, "bioreactor-residuals-qq-plot.png")


def gas_furnace(outdir: pathlib.Path) -> None:
    gas = fetch("gas-furnace.csv")
    rate = gas["InputGasRate"].to_numpy(dtype=float)
    co2 = gas["CO2"].to_numpy(dtype=float)
    model = Fit(rate, co2)
    print(f"gas furnace: CO2 = {model.intercept:.2f} {model.slope:+.3f} rate, "
          f"R2 {model.r2:.4f}, correlation {np.corrcoef(rate, co2)[0, 1]:.3f}")

    fig, ax = plt.subplots(figsize=(8, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(rate, co2, "o", color=BLUE, markersize=5, markerfacecolor="none",
            markeredgewidth=1.2)
    edge = np.array([rate.min(), rate.max()])
    ax.plot(edge, model.intercept + model.slope * edge, color=VERMILLION,
            linewidth=2.5, label="Least squares fit")
    grid, fitted = lowess(rate, co2, frac=0.4)
    ax.plot(grid, fitted, "--", color=GREEN, linewidth=2.2, label="LOESS smoother")
    ax.set_title("Scatter plot with a smoother and the least squares line")
    ax.set_xlabel("Gas flow rate")
    ax.set_ylabel("CO$_2$")
    ax.legend(loc="upper right", frameon=False)
    save(fig, outdir, "CO2-gas-furnace-raw-data.png")

    fig, ax = plt.subplots(figsize=(8, 7))
    qq_panel(ax, model.studentized, "Studentized residuals")
    save(fig, outdir, "CO2-gas-furnace-residuals.png")


def cheese(outdir: pathlib.Path) -> None:
    cheddar = fetch("cheddar-cheese.csv")
    frame = cheddar[["Acetic", "H2S", "Lactic", "Taste"]]
    print("cheese correlations:")
    print(frame.corr().round(2).to_string())
    pairs_plot(frame, outdir, "cheese-data-correlation.png", size=11)


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    distillation(outdir)
    kappa_autocorrelation(outdir)
    bioreactor(outdir)
    gas_furnace(outdir)
    cheese(outdir)
