"""Main-body and enrichment figures for the least-squares chapter.

Three committed PNGs, replacing images previously generated by base-R
scripts (``non-parametric-script.R``, ``bootstrap-example.R``,
``cylinder-case-study.R``):

- ``nonparametric-plots.png``: occupational prestige against average
  income, shown raw and again with a LOESS smoother, the enrichment
  section's example of a non-parametric fit.
- ``bootstrap-example.png``: the radiation survival data with two least
  squares fits (all the data, and without observation 13), next to the
  distribution of 1000 bootstrapped slope coefficients.
- ``cylinder-case-study-objective.png``: the least squares objective
  function of the cylinder case study, swept over the slope
  coefficient, showing the single minimum that the normal equations
  solve for.

Data:

- ``prestige.csv`` in this directory, the Canadian occupational prestige
  data from R's ``carData`` package (102 occupations), committed here so
  the figure does not depend on a third-party mirror.
- ``radiation-survival.csv`` in this directory, the 14-point survival
  data from R's ``boot`` package.
- The cylinder temperatures and pressures are the ten pairs printed in
  the chapter, embedded below.

The bootstrap resampling is seeded, so the committed image regenerates
exactly. The script prints the slope estimates and the bootstrap
interval.

Usage
-----
    uv run --with numpy --with pandas --with scipy --with matplotlib python least_squares_chapter_figures.py [output_dir]

Writes the three PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from mpl_toolkits.axes_grid1 import make_axes_locatable
from scipy import stats

BLUE = "#0072B2"
GREEN = "#009E73"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

# Cylinder case study: temperature [K] and pressure [kPa].
CYLINDER_T = np.array([273, 285, 297, 309, 321, 333, 345, 357, 369, 381], dtype=float)
CYLINDER_P = np.array([1600, 1670, 1730, 1830, 1880, 1920, 2000, 2100, 2170, 2200],
                      dtype=float)

mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def marginal_boxplots(ax, x, y) -> None:
    """Box plots down the left and along the bottom, as R's
    ``car::scatterplot`` draws them."""
    divider = make_axes_locatable(ax)
    left = divider.append_axes("left", size="7%", pad=0.5, sharey=ax)
    bottom = divider.append_axes("bottom", size="7%", pad=0.5, sharex=ax)
    style = dict(
        widths=0.5, patch_artist=True,
        boxprops=dict(facecolor="white", color=GREY, linewidth=1.2),
        medianprops=dict(color=GREY, linewidth=1.6),
        whiskerprops=dict(color=GREY, linewidth=1.2),
        capprops=dict(color=GREY, linewidth=1.2),
        flierprops=dict(marker="o", markersize=3, markerfacecolor="none",
                        markeredgecolor=GREY),
    )
    left.boxplot(np.asarray(y, dtype=float), orientation="vertical", **style)
    bottom.boxplot(np.asarray(x, dtype=float), orientation="horizontal", **style)
    for extra in (left, bottom):
        # Hide the labels with tick_params, not set_xticks: these axes
        # share their scale with the main one, so clearing the ticks
        # would clear them on the scatter plot too.
        extra.tick_params(left=False, labelleft=False,
                          bottom=False, labelbottom=False)
        for spine in extra.spines.values():
            spine.set_visible(False)
    # The axis labels belong outside the box plots, not under them.
    if ax.get_xlabel():
        bottom.set_xlabel(ax.get_xlabel())
        ax.set_xlabel("")
    if ax.get_ylabel():
        left.set_ylabel(ax.get_ylabel())
        ax.set_ylabel("")


def lowess(x, y, frac: float = 0.5, gridsize: int = 100):
    """Tricube-weighted local linear smoother, one pass."""
    order = np.argsort(x)
    xs, ys = np.asarray(x)[order], np.asarray(y)[order]
    span = max(2, int(frac * len(xs)))
    grid = np.linspace(xs.min(), xs.max(), gridsize)
    fitted = np.empty_like(grid)
    for i, x0 in enumerate(grid):
        distance = np.abs(xs - x0)
        cutoff = np.sort(distance)[span - 1]
        w = np.clip(1 - (distance / max(cutoff, 1e-12)) ** 3, 0, None) ** 3
        total = w.sum()
        xm, ym = (w * xs).sum() / total, (w * ys).sum() / total
        slope = (w * (xs - xm) * (ys - ym)).sum() / max((w * (xs - xm) ** 2).sum(), 1e-12)
        fitted[i] = ym + slope * (x0 - xm)
    return grid, fitted


def nonparametric(outdir: pathlib.Path) -> None:
    prestige = pd.read_csv(HERE / "prestige.csv")
    income = prestige["income"].to_numpy(dtype=float)
    score = prestige["prestige"].to_numpy(dtype=float)
    print(f"prestige: {len(income)} occupations, "
          f"correlation {np.corrcoef(income, score)[0, 1]:.2f}")

    fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=True)
    for ax, with_smoother in zip(axes, (False, True)):
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(income, score, "o", color=BLUE, markersize=6,
                markerfacecolor="none", markeredgewidth=1.4)
        if with_smoother:
            grid, fitted = lowess(income, score, frac=0.6)
            ax.plot(grid, fitted, color=VERMILLION, linewidth=2.5,
                    label="LOESS smoother")
            slope, intercept = np.polyfit(income, score, 1)
            edge = np.array([income.min(), income.max()])
            ax.plot(edge, intercept + slope * edge, "--", color=GREY,
                    linewidth=2, label="Least squares line")
            ax.legend(loc="lower right", frameon=False)
        ax.set_xlabel("Average income ($)")
        ax.set_title("With a smoother" if with_smoother else "The raw data")
    axes[0].set_ylabel("Prestige")
    # car::scatterplot puts a box plot on each margin of the right-hand
    # panel. They carry the univariate spread, which the scatter plot on
    # its own does not show.
    marginal_boxplots(axes[1], income, score)
    save(fig, outdir, "nonparametric-plots.png")


def bootstrap(outdir: pathlib.Path) -> None:
    survival = pd.read_csv(HERE / "radiation-survival.csv")
    dose = survival["dose"].to_numpy(dtype=float)
    log_surv = np.log(survival["surv"].to_numpy(dtype=float))
    n = len(dose)
    # Observation 13 in the R data is index 12 here.
    unusual = 12

    slope_all, intercept_all = np.polyfit(dose, log_surv, 1)
    keep = np.arange(n) != unusual
    slope_rm, intercept_rm = np.polyfit(dose[keep], log_surv[keep], 1)

    # The classical interval for the slope, for comparison.
    residuals = log_surv - (intercept_all + slope_all * dose)
    se = np.sqrt((residuals ** 2).sum() / (n - 2))
    se_slope = se / np.sqrt(((dose - dose.mean()) ** 2).sum())
    critical = stats.t.ppf(0.975, df=n - 2)
    print(f"radiation survival: slope {slope_all:.5f} with all {n} points, "
          f"{slope_rm:.5f} without point 13")
    print(f"  classical 95% interval: "
          f"{slope_all - critical * se_slope:.5f} to {slope_all + critical * se_slope:.5f}")

    rng = np.random.default_rng(13)
    draws = 1000
    slopes = np.empty(draws)
    for i in range(draws):
        pick = rng.integers(0, n, size=n)
        slopes[i] = np.polyfit(dose[pick], log_surv[pick], 1)[0]
    low, high = np.percentile(slopes, [2.5, 97.5])
    print(f"  bootstrap 95% interval from {draws} resamples: {low:.5f} to {high:.5f}")

    fig, axes = plt.subplots(1, 2, figsize=(15, 6))

    ax = axes[0]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(dose, log_surv, "o", color=BLUE, markersize=8,
            markerfacecolor="none", markeredgewidth=1.6)
    edge = np.array([dose.min(), dose.max()])
    ax.plot(edge, intercept_all + slope_all * edge, color=VERMILLION,
            linewidth=3, label="Least squares: all data")
    ax.plot(edge, intercept_rm + slope_rm * edge, color=GREEN, linewidth=2,
            label="Least squares: without point 13")
    ax.annotate("Point 13", xy=(dose[unusual], log_surv[unusual]),
                xytext=(dose[unusual] - 40, log_surv[unusual] + 0.35),
                ha="right", color=GREY)
    ax.set_xlabel("Dosage [rads]")
    ax.set_ylabel("log(Survival percentage)")
    ax.legend(loc="upper right", frameon=False, fontsize=14)

    ax = axes[1]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    counts, edges, _ = ax.hist(slopes, bins=40, color=BLUE, edgecolor="white")
    # A density curve over the bars, as the original drew, so the shape
    # of the distribution reads independently of the bin boundaries.
    curve = np.linspace(slopes.min(), slopes.max(), 400)
    density = stats.gaussian_kde(slopes)(curve)
    ax.plot(curve, density * draws * np.diff(edges).mean(), color=GREY,
            linewidth=2)
    # Headroom above the bars for the interval arrow and the three
    # labels, so neither sits on top of the distribution.
    top = float(counts.max())
    ax.set_ylim(0, 1.45 * top)

    # Label the bounds: an unlabelled vertical line does not say which
    # of the three quantities it marks.
    marks = (
        (low, VERMILLION, "CI: lower bound"),
        (slope_rm, GREEN, "Except point 13"),
        (high, VERMILLION, "CI: upper bound"),
    )
    for value, colour, label in marks:
        ax.axvline(value, color=colour, linewidth=2)
        ax.annotate(label, xy=(value, 1.24 * top), xytext=(-4, 0),
                    textcoords="offset points", rotation=90, ha="right",
                    va="top", color=colour, fontsize=13)

    # The width of the interval, drawn as a width. Two vertical lines
    # say where the bounds are; the arrow between them is what shows
    # how wide the interval is, which is the quantity under discussion.
    ax.annotate("", xy=(high, 1.33 * top), xytext=(low, 1.33 * top),
                arrowprops=dict(arrowstyle="<->", color=VERMILLION,
                                linewidth=2, shrinkA=0, shrinkB=0))
    ax.annotate(f"95% confidence interval: {high - low:.4f} wide",
                xy=((low + high) / 2, 1.35 * top), ha="center", va="bottom",
                color=VERMILLION, fontsize=13)

    ax.set_xlabel("Bootstrapped slope coefficient")
    ax.set_ylabel(f"Frequency (N = {draws})")
    ax.set_title("The slope has a distribution of its own")
    # One label every 0.002. The default put nine on this axis and they
    # ran into each other, reading as a single string of digits.
    ax.xaxis.set_major_locator(mpl.ticker.MultipleLocator(0.002))
    ax.xaxis.set_major_formatter(mpl.ticker.FormatStrFormatter("%.3f"))
    save(fig, outdir, "bootstrap-example.png")


def cylinder_objective(outdir: pathlib.Path) -> None:
    # Model without an intercept: p_hat = beta * T, swept over beta.
    # The original evaluated the objective on a coarse grid and plotted
    # the points, which is what the surrounding text describes: you try
    # a value of the slope, you get a number, you try another. A
    # continuous curve would suggest it came out in closed form.
    beta = np.arange(5.3, 6.401, 0.06)
    ssq = np.array([float((((CYLINDER_T * b) - CYLINDER_P) ** 2).sum())
                    for b in beta])
    best = beta[np.argmin(ssq)]
    analytic = float((CYLINDER_T * CYLINDER_P).sum() / (CYLINDER_T ** 2).sum())
    print(f"cylinder: objective minimised at beta = {best:.3f}; "
          f"normal equations give {analytic:.3f}")

    fig, ax = plt.subplots(figsize=(8, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(beta, ssq, "o", color=BLUE, markersize=8, markerfacecolor="none",
            markeredgewidth=1.6)
    ax.plot([analytic], [((CYLINDER_T * analytic - CYLINDER_P) ** 2).sum()], "o",
            color=VERMILLION, markersize=10)
    ax.annotate(rf"minimum at $\beta$ = {analytic:.2f}",
                xy=(analytic, ssq.min()),
                xytext=(analytic + 0.08, ssq.min() + 0.28 * np.ptp(ssq)),
                color=VERMILLION,
                arrowprops=dict(arrowstyle="->", color=VERMILLION, linewidth=2))
    ax.set_xlabel(r"Slope coefficient, $\beta$")
    ax.set_ylabel("Objective function: sum of squared residuals")
    save(fig, outdir, "cylinder-case-study-objective.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    nonparametric(outdir)
    bootstrap(outdir)
    cylinder_objective(outdir)
