"""Diagnostic figures for the least-squares chapter of the PID book.

Ten committed PNGs, replacing images previously generated by base-R
scripts (``correlation-calculation.R``, ``show-residual-patterns.R``,
``demo-autocorrelation.R``, ``nonlinear-linear-region.R``,
``non-normal-errors.R``, ``non-normal-errors-transformation-required.R``,
``logistic-regression-function.R``, and the residual histogram):

- ``correlation-calculation.png``: four scatter panels (strong negative,
  none, moderate positive, and a quadratic relationship with no linear
  correlation), each labelled with its computed r(x, y).
- ``residual-plots.png``: a typical histogram of residuals, centred at
  zero and roughly normally distributed.
- ``residual-pattern-non-contant-error.png``: data with error variance
  growing in x, and the fan-shaped residual pattern it produces.
- ``residual-pattern-unmodelled-dynamics.png``: residuals in time
  order: a slow drift, and rapid criss-crossing of zero.
- ``demonstrate-autocorrelation.png``: three series and their
  autocorrelation functions; the first needs a gap of about 16 samples
  between sub-samples, the other two a gap of 1 (the prose quotes
  these gaps).
- ``nonlinear-linear-region.png`` and ``nonlinear-detection.png``: a
  nonlinear system with a locally linear model region, and the
  residual plots that reveal the nonlinearity when the whole range is
  fit with a straight line.
- ``non-normal-errors-outliers.png``: q-q plots of residuals from a
  price-mileage model, before and after removing a handful of
  collector cars (illustrative simulated stand-in for the original
  cars dataset).
- ``non-normal-errors-transformation-required.png``: residual q-q
  plots before and after a square-root transformation of y.
- ``logistic-regression-function.png``: an S-shaped link function
  bounded by 0 and 1.

All random data are seeded so the committed images regenerate exactly.

Usage
-----
    uv run --with numpy --with scipy --with matplotlib python regression_diagnostics_figures.py [output_dir]
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

BLUE = "#0072B2"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300

mpl.rcParams.update(
    {
        "font.size": 17,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 19,
        "axes.labelsize": 20,
        "xtick.labelsize": 17,
        "ytick.labelsize": 17,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def _fit(x, y):
    slope, intercept = np.polyfit(x, y, 1)
    fitted = intercept + slope * x
    return slope, intercept, fitted, y - fitted


def _lowess(x, y, frac=0.5, gridsize=60):
    """Plain tricube-weighted local linear smoother (LOWESS, one pass)."""
    order = np.argsort(x)
    xs, ys = x[order], y[order]
    span = max(2, int(frac * len(xs)))
    grid = np.linspace(xs.min(), xs.max(), gridsize)
    fitted = np.empty_like(grid)
    for i, x0 in enumerate(grid):
        d = np.abs(xs - x0)
        cutoff = np.sort(d)[span - 1]
        w = np.clip(1 - (d / max(cutoff, 1e-12)) ** 3, 0, None) ** 3
        xm = np.sum(w * xs) / w.sum()
        ym = np.sum(w * ys) / w.sum()
        b = np.sum(w * (xs - xm) * (ys - ym)) / max(np.sum(w * (xs - xm) ** 2), 1e-12)
        fitted[i] = ym + b * (x0 - xm)
    return grid, fitted


def _qq_axes(ax, values, title):
    """A normal q-q plot of `values` with the quartile reference line."""
    n = len(values)
    theo = stats.norm.ppf((np.arange(1, n + 1) - 0.5) / n)
    ordered = np.sort(values)
    x25, x75 = np.percentile(theo, [25, 75])
    y25, y75 = np.percentile(ordered, [25, 75])
    slope = (y75 - y25) / (x75 - x25)
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(theo, y25 - slope * x25 + slope * theo, color=GREY, linewidth=1.5)
    ax.plot(theo, ordered, "o", color=BLUE, markersize=6, alpha=0.75)
    ax.set_title(title)
    ax.set_xlabel("Theoretical quantile")


def correlation_calculation(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(6)
    N = 30
    x1 = rng.normal(12, 4, N)
    panels = [
        (x1, -4.2 * x1 + rng.normal(0, 8, N), "A strong negative correlation"),
        (rng.normal(12, 4, N), rng.normal(0, 8, N), "Essentially no correlation"),
        (rng.normal(0, 9, N), None, "A moderate, positive correlation"),
        (rng.normal(0, 9, N), None, "A relationship, but no correlation"),
    ]
    x3 = panels[2][0]
    panels[2] = (x3, 0.28 * x3 + rng.normal(50, 4, N), panels[2][2])
    x4 = panels[3][0]
    panels[3] = (x4, x4 ** 2 + rng.normal(50, 20, N), panels[3][2])

    fig, axes = plt.subplots(2, 2, figsize=(14, 14))
    for ax, (x, y, title) in zip(axes.flat, panels):
        r = np.corrcoef(x, y)[0, 1]
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(x, y, "o", color=BLUE, markersize=8, alpha=0.8)
        ax.set_title(title)
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.text(
            0.5, 0.06 if r > 0.3 else 0.9, f"r(x, y) = {r:.3f}",
            transform=ax.transAxes, ha="center", fontsize=22,
        )
    save(fig, outdir, "correlation-calculation.png")


def residual_histogram(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(15)
    residuals = rng.normal(0, 1, 500)
    fig, ax = plt.subplots(figsize=(14, 7))
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.hist(residuals, bins=np.arange(-3.25, 3.3, 0.5), color=BLUE,
            edgecolor="white")
    ax.axvline(0, color="black", linewidth=1)
    ax.set_xlabel("Residual value, in units of standard error, $S_E$")
    ax.set_ylabel("Frequency (N = 500 residuals)")
    save(fig, outdir, "residual-plots.png")


def non_constant_error(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(12)
    x = np.arange(5, 10.05, 0.1)
    y = 20 * x + rng.normal(0, 1, x.size) * (x - 4.2) ** 2
    slope, intercept, fitted, residuals = _fit(x, y)

    fig, axes = plt.subplots(1, 2, figsize=(14, 7))
    ax = axes[0]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, y, "o", color=BLUE, markersize=6, alpha=0.8)
    ax.plot(x, fitted, color=VERMILLION, linewidth=2)
    ax.set_title("Raw data with the least squares model")
    ax.set_xlabel("x")
    ax.set_ylabel("y")

    ax = axes[1]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(fitted, residuals, "o", color=BLUE, markersize=6, alpha=0.8)
    ax.axhline(0, color="black", linewidth=1)
    ax.set_title("Fitted values against the residuals")
    ax.set_xlabel(r"Fitted values, $\hat{y}$")
    ax.set_ylabel("Residuals")
    save(fig, outdir, "residual-pattern-non-contant-error.png")


def unmodelled_dynamics(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(4)
    n = 120
    t = np.arange(n)
    drift = np.zeros(n)
    for k in range(1, n):
        drift[k] = 0.92 * drift[k - 1] + rng.normal(0, 0.5)
    crisscross = np.zeros(n)
    for k in range(1, n):
        crisscross[k] = -0.8 * crisscross[k - 1] + rng.normal(0, 0.8)

    fig, axes = plt.subplots(1, 2, figsize=(14, 4.7))
    for ax, series, title in (
        (axes[0], drift, "Residuals with a slow drift"),
        (axes[1], crisscross, "Residuals criss-crossing the zero axis"),
    ):
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(t, series, "o-", color=BLUE, markersize=4, linewidth=1)
        ax.axhline(0, color="black", linewidth=1)
        ax.set_title(title, fontsize=17)
        ax.set_xlabel("Time order of the residuals", fontsize=17)
        ax.tick_params(labelsize=15)
    axes[0].set_ylabel("Residuals", fontsize=17)
    save(fig, outdir, "residual-pattern-unmodelled-dynamics.png")


def _acf(series, nlags):
    centred = series - series.mean()
    denom = np.sum(centred ** 2)
    return np.array([
        np.sum(centred[k:] * centred[: len(series) - k]) / denom
        for k in range(nlags + 1)
    ])


def demonstrate_autocorrelation(outdir: pathlib.Path) -> None:
    # Seed and AR coefficient chosen so the leading run of significant
    # lags is exactly 16, 1 and 1: the gaps the chapter prose quotes.
    rng = np.random.default_rng(31)
    n, nlags = 500, 25
    e = rng.normal(0, 1, (3, n + 1))
    slow = np.zeros(n)
    for k in range(1, n):
        slow[k] = 0.86 * slow[k - 1] + e[0, k]
    ma_pos = e[1, 1:] + 0.9 * e[1, :-1]
    ma_neg = e[2, 1:] - 0.9 * e[2, :-1]

    cases = [
        (slow, "Slowly drifting process"),
        (ma_pos, "Correlated with the\nprevious value only"),
        (ma_neg, "Negatively correlated\nwith the previous value"),
    ]
    bound = 1.96 / np.sqrt(n)
    fig, axes = plt.subplots(2, 3, figsize=(14, 9.3))
    for col, (series, title) in enumerate(cases):
        ax = axes[0, col]
        ax.grid(color=GRID, linewidth=0.6)
        ax.plot(series[:200], color=BLUE, linewidth=0.9)
        ax.set_title(title, fontsize=15)
        ax.set_xlabel("Time order", fontsize=14)
        ax.tick_params(labelsize=13)

        ax = axes[1, col]
        ax.grid(color=GRID, linewidth=0.6)
        acf = _acf(series, nlags)
        markers, stems, base = ax.stem(np.arange(nlags + 1), acf, basefmt="k-")
        plt.setp(stems, color=BLUE, linewidth=1.5)
        plt.setp(markers, color=BLUE, markersize=4)
        for b in (-bound, bound):
            ax.axhline(b, color=VERMILLION, linewidth=1.2, linestyle="--")
        ax.set_xlabel("Lag", fontsize=14)
        ax.set_ylim(-1.05, 1.05)
        ax.tick_params(labelsize=13)
        run = 1
        while run <= nlags and abs(acf[run]) > bound:
            run += 1
        ax.set_title(f"Significant to lag {run - 1}", fontsize=15)
    axes[0, 0].set_ylabel("Value", fontsize=14)
    axes[1, 0].set_ylabel("Autocorrelation", fontsize=14)
    save(fig, outdir, "demonstrate-autocorrelation.png")


def _nonlinear_data():
    rng = np.random.default_rng(42)
    x = np.arange(5, 9.05, 0.1)
    y = (0.4 * x + np.exp(0.6 * x) - 2 + rng.normal(0, 9, x.size)) / 2.3
    return x, y


def nonlinear_linear_region(outdir: pathlib.Path) -> None:
    x, y = _nonlinear_data()
    lo, hi = 6.05, 7.95
    inside = (x > lo) & (x < hi)
    slope, intercept = np.polyfit(x[inside], y[inside], 1)

    fig, ax = plt.subplots(figsize=(7, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x[~inside], y[~inside], "o", color=BLUE, markersize=7, alpha=0.8,
            label="Outside the model region")
    ax.plot(x[inside], y[inside], "^", color=ORANGE, markersize=8,
            label="Used to build the model")
    for v in (lo, hi):
        ax.axvline(v, color=GREY, linestyle="--", linewidth=1.2)
    xr = np.array([lo, hi])
    ax.plot(xr, intercept + slope * xr, color=VERMILLION, linewidth=2.5,
            linestyle="--")
    grid, fitted = _lowess(x, y, frac=0.4)
    ax.plot(grid, fitted, color=GREY, linewidth=1.5, linestyle=":")
    ytext = y.max() * 0.95
    ax.annotate("", xy=(hi, ytext), xytext=(lo, ytext),
                arrowprops=dict(arrowstyle="<->", color="black", linewidth=1.5))
    ax.text((lo + hi) / 2, ytext * 0.955, "Model region", ha="center",
            fontsize=16)
    ax.set_xlabel("x", fontsize=17)
    ax.set_ylabel("y", fontsize=17)
    ax.tick_params(labelsize=15)
    ax.legend(loc="upper left", frameon=False, fontsize=13)
    save(fig, outdir, "nonlinear-linear-region.png")


def nonlinear_detection(outdir: pathlib.Path) -> None:
    x, y = _nonlinear_data()
    slope, intercept, fitted, residuals = _fit(x, y)
    fig, axes = plt.subplots(1, 3, figsize=(16, 5.3))
    panels = [
        (x, y, "x", "y", False),
        (x, residuals, "x", "Residuals", True),
        (fitted, residuals, r"Fitted values, $\hat{y}$", "Residuals", True),
    ]
    for ax, (px, py, xlabel, ylabel, is_resid) in zip(axes, panels):
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(px, py, "o", color=BLUE, markersize=6, alpha=0.8)
        if is_resid:
            ax.axhline(0, color="black", linewidth=1)
            grid, smooth = _lowess(px, py, frac=0.5)
            ax.plot(grid, smooth, color=VERMILLION, linewidth=2, linestyle="--")
        else:
            ax.plot(px, intercept + slope * px, color=VERMILLION, linewidth=2)
        ax.set_xlabel(xlabel, fontsize=18)
        ax.set_ylabel(ylabel, fontsize=18)
        ax.tick_params(labelsize=16)
    save(fig, outdir, "nonlinear-detection.png")


def non_normal_errors(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(9)
    n = 90
    mileage = rng.uniform(20, 120, n)  # thousands of km
    price = 25.0 - 0.12 * mileage + rng.normal(0, 1.6, n)  # thousands
    collectors = rng.choice(n, 4, replace=False)
    price[collectors] += rng.uniform(6, 12, 4)

    _, _, _, resid_all = _fit(mileage, price)
    keep = np.ones(n, dtype=bool)
    keep[collectors] = False
    _, _, _, resid_clean = _fit(mileage[keep], price[keep])

    fig, axes = plt.subplots(1, 2, figsize=(14, 9))
    _qq_axes(axes[0], resid_all, "All data")
    _qq_axes(axes[1], resid_clean, "After removing the 'outlier' cars")
    for ax in axes:
        ax.set_ylabel("Residuals: price ~ mileage", fontsize=18)
    save(fig, outdir, "non-normal-errors-outliers.png")


def transformation_required(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(7)
    n = 60
    x = rng.normal(7, 1.6, n)
    y = (2 * x + rng.normal(0, 1.1, n)) ** 2
    _, _, _, resid_raw = _fit(x, y)
    _, _, _, resid_sqrt = _fit(x, np.sqrt(y))

    fig, axes = plt.subplots(1, 2, figsize=(14, 8))
    _qq_axes(axes[0], resid_raw, "Original data: y ~ x")
    _qq_axes(axes[1], resid_sqrt,
             r"After a square root transformation: $\sqrt{y}$ ~ x")
    axes[0].set_ylabel("Residuals", fontsize=18)
    save(fig, outdir, "non-normal-errors-transformation-required.png")


def logistic_function(outdir: pathlib.Path) -> None:
    z = np.linspace(-4, 4, 801)
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.grid(color=GRID, linewidth=0.8)
    for h in (0, 1):
        ax.axhline(h, color=GREY, linestyle=":", linewidth=1.5)
    ax.plot(z, stats.norm.cdf(z), color=BLUE, linewidth=2.5)
    ax.set_xlabel("Function input", fontsize=14)
    ax.set_ylabel("Function output", fontsize=14)
    ax.tick_params(labelsize=13)
    ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    save(fig, outdir, "logistic-regression-function.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    correlation_calculation(outdir)
    residual_histogram(outdir)
    non_constant_error(outdir)
    unmodelled_dynamics(outdir)
    demonstrate_autocorrelation(outdir)
    nonlinear_linear_region(outdir)
    nonlinear_detection(outdir)
    non_normal_errors(outdir)
    transformation_required(outdir)
    logistic_function(outdir)
