"""Diagnostic figures for the least-squares chapter of the PID book.

Ten committed PNGs, replacing images previously generated by base-R
scripts (``correlation-calculation.R``, ``show-residual-patterns.R``,
``demo-autocorrelation.R``, ``nonlinear-linear-region.R``,
``non-normal-errors.R``, ``non-normal-errors-transformation-required.R``,
``logistic-regression-function.R``, and the residual histogram):

- ``correlation-calculation.png``: four scatter panels (strong negative,
  none, moderate positive, and a quadratic relationship with no linear
  correlation), each labelled with its computed r(x, y).
- ``residual-plots.png``: a typical histogram of residuals, centred at
  zero and roughly normally distributed.
- ``residual-pattern-non-contant-error.png``: data with error variance
  growing in x, and the fan-shaped residual pattern it produces.
- ``residual-pattern-unmodelled-dynamics.png``: residuals in time
  order: a slow drift, and rapid criss-crossing of zero.
- ``demonstrate-autocorrelation.png``: three series and their
  autocorrelation functions; the first needs a gap of about 16 samples
  between sub-samples, the other two a gap of 1 (the prose quotes
  these gaps).
- ``nonlinear-linear-region.png`` and ``nonlinear-detection.png``: a
  nonlinear system with a locally linear model region, and the
  residual plots that reveal the nonlinearity when the whole range is
  fit with a straight line.
- ``non-normal-errors-outliers.png``: q-q plots of the residuals from
  the price-mileage model of the 804-vehicle Kuiper dataset
  (``kuiper.csv``, in this directory), before and after removing the
  ten Cadillac convertibles. The slope and standard error printed on
  each run match the numbers quoted in the chapter (b1 = -0.173 and
  SE = $9789 before; b1 = -0.155 and SE = $8655 after).
- ``non-normal-errors-transformation-required.png``: residual q-q
  plots before and after a square-root transformation of y.
- ``logistic-regression-function.png``: an S-shaped link function
  bounded by 0 and 1.

All random data are seeded so the committed images regenerate exactly.

Usage
-----
    uv run --with numpy --with scipy --with matplotlib python regression_diagnostics_figures.py [output_dir]
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

BLUE = "#0072B2"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300

mpl.rcParams.update(
    {
        "font.size": 17,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 19,
        "axes.labelsize": 20,
        "xtick.labelsize": 17,
        "ytick.labelsize": 17,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def _fit(x, y):
    slope, intercept = np.polyfit(x, y, 1)
    fitted = intercept + slope * x
    return slope, intercept, fitted, y - fitted


def _lowess(x, y, frac=0.5, gridsize=60):
    """Plain tricube-weighted local linear smoother (LOWESS, one pass)."""
    order = np.argsort(x)
    xs, ys = x[order], y[order]
    span = max(2, int(frac * len(xs)))
    grid = np.linspace(xs.min(), xs.max(), gridsize)
    fitted = np.empty_like(grid)
    for i, x0 in enumerate(grid):
        d = np.abs(xs - x0)
        cutoff = np.sort(d)[span - 1]
        w = np.clip(1 - (d / max(cutoff, 1e-12)) ** 3, 0, None) ** 3
        xm = np.sum(w * xs) / w.sum()
        ym = np.sum(w * ys) / w.sum()
        b = np.sum(w * (xs - xm) * (ys - ym)) / max(np.sum(w * (xs - xm) ** 2), 1e-12)
        fitted[i] = ym + b * (x0 - xm)
    return grid, fitted


def _qq_axes(ax, values, title, dist=stats.norm):
    """A q-q plot with the quartile reference line and the 95%
    pointwise confidence envelope, as R's car::qqPlot draws it.
    ``dist`` is the reference distribution (normal by default; pass a
    frozen t-distribution for studentized residuals)."""
    n = len(values)
    P = (np.arange(1, n + 1) - 0.5) / n
    theo = dist.ppf(P)
    ordered = np.sort(values)
    x25, x75 = np.percentile(theo, [25, 75])
    y25, y75 = np.percentile(ordered, [25, 75])
    slope = (y75 - y25) / (x75 - x25)
    intercept = y25 - slope * x25
    fit = intercept + slope * theo
    se = (slope / dist.pdf(theo)) * np.sqrt(P * (1 - P) / n)
    zc = stats.norm.ppf(0.975)
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(theo, fit, color=GREY, linewidth=1.5)
    ax.plot(theo, fit - zc * se, color=VERMILLION, linestyle="--", linewidth=1.5)
    ax.plot(theo, fit + zc * se, color=VERMILLION, linestyle="--", linewidth=1.5)
    ax.plot(theo, ordered, "o", color=BLUE, markersize=6, alpha=0.75)
    ax.set_title(title)
    ax.set_xlabel("Theoretical quantile")


def correlation_calculation(outdir: pathlib.Path) -> None:
    # Seed chosen so the four r values land where the captions need
    # them: strongly negative, near zero, moderate, and near zero for
    # the quadratic relationship.
    rng = np.random.default_rng(15)
    N = 30
    x1 = rng.normal(12, 4, N)
    y1 = -4.2 * x1 + rng.normal(0, 8, N)
    x2 = rng.normal(12, 4, N)
    y2 = rng.normal(0, 8, N)
    x3 = rng.normal(0, 9, N)
    y3 = 0.28 * x3 + rng.normal(50, 4, N)
    x4 = rng.normal(0, 9, N)
    y4 = x4 ** 2 + rng.normal(50, 20, N)
    panels = [
        (x1, y1, "A strong negative correlation"),
        (x2, y2, "Essentially no correlation"),
        (x3, y3, "A moderate, positive correlation"),
        (x4, y4, "A relationship, but no correlation"),
    ]

    # Text positions chosen per panel so the annotation sits in the
    # empty region of that panel's point cloud.
    positions = [(0.72, 0.90), (0.50, 0.03), (0.26, 0.90), (0.50, 0.88)]
    fig, axes = plt.subplots(2, 2, figsize=(14, 14))
    for ax, (x, y, title), pos in zip(axes.flat, panels, positions):
        r = np.corrcoef(x, y)[0, 1]
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(x, y, "o", color=BLUE, markersize=8, alpha=0.8)
        ax.set_title(title)
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.text(
            *pos, f"r(x, y) = {r:.3f}",
            transform=ax.transAxes, ha="center", fontsize=22,
            bbox=dict(facecolor="white", edgecolor="none", alpha=0.85, pad=2),
        )
    save(fig, outdir, "correlation-calculation.png")


def residual_histogram(outdir: pathlib.Path) -> None:
    # As in the original (example-distillation.R): residuals of a
    # vapour-pressure model on the distillation-tower dataset, shown as
    # a histogram next to their q-q plot with a confidence envelope.
    import pandas as pd

    try:
        tower = pd.read_csv("http://openmv.net/file/distillation-tower.csv")
    except Exception:
        tower = pd.read_csv(pathlib.Path(__file__).parent / "distillation-tower.csv")
    inv_temp = 1.0 / tower["TempC2"].to_numpy()
    log_vp = np.log(tower["VapourPressure"].to_numpy())
    _, _, _, residuals = _fit(inv_temp, log_vp)

    fig, axes = plt.subplots(1, 2, figsize=(14, 7))
    ax = axes[0]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.hist(residuals, bins=12, color=BLUE, edgecolor="white")
    ax.set_xlabel("Model residuals")
    ax.set_ylabel(f"Frequency count (N = {len(residuals)})")
    _qq_axes(axes[1], residuals, "")
    axes[1].set_ylabel("Model residuals")
    save(fig, outdir, "residual-plots.png")


def non_constant_error(outdir: pathlib.Path) -> None:
    rng = np.random.default_rng(12)
    x = np.arange(5, 10.05, 0.1)
    y = 20 * x + rng.normal(0, 1, x.size) * (x - 4.2) ** 2
    slope, intercept, fitted, residuals = _fit(x, y)

    fig, axes = plt.subplots(1, 2, figsize=(14, 7))
    ax = axes[0]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, y, "o", color=BLUE, markersize=6, alpha=0.8)
    ax.plot(x, fitted, color=VERMILLION, linewidth=2)
    ax.set_title("Raw data with the least squares model")
    ax.set_xlabel("x")
    ax.set_ylabel("y")

    ax = axes[1]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(fitted, residuals, "o", color=BLUE, markersize=6, alpha=0.8)
    ax.axhline(0, color="black", linewidth=1)
    ax.set_title("Fitted values against the residuals")
    ax.set_xlabel(r"Fitted values, $\hat{y}$")
    ax.set_ylabel("Residuals")
    save(fig, outdir, "residual-pattern-non-contant-error.png")


def unmodelled_dynamics(outdir: pathlib.Path) -> None:
    # Same design and data recipe as the original
    # (detecting-autocorrelation.R): x ~ N(10, 2), an AR(1) disturbance
    # (phi = 0.86, sd = 3), y = -3x + 50 + e; then y in time order, the
    # least squares fit, and the residuals in time order.
    rng = np.random.default_rng(8)
    n = 100
    e = np.zeros(n)
    for k in range(1, n):
        e[k] = 0.86 * e[k - 1] + rng.normal(0, 3)
    x = rng.normal(10, 2, n)
    y = -3 * x + 50 + e
    slope, intercept, fitted, residuals = _fit(x, y)

    fig, axes = plt.subplots(1, 3, figsize=(14, 4.7))
    ax = axes[0]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(y, "o-", color=BLUE, markersize=4, linewidth=1)
    ax.set_title("Time order of the y-variable", fontsize=15)
    ax.set_xlabel("Time order", fontsize=15)
    ax.set_ylabel("y", fontsize=15)

    ax = axes[1]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, y, "o", color=BLUE, markersize=5, alpha=0.8)
    xr = np.array([x.min(), x.max()])
    ax.plot(xr, intercept + slope * xr, color=VERMILLION, linewidth=2)
    ax.set_title("Raw data with the least squares model", fontsize=15)
    ax.set_xlabel("x", fontsize=15)
    ax.set_ylabel("y", fontsize=15)

    ax = axes[2]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(residuals, "o-", color=BLUE, markersize=4, linewidth=1)
    ax.axhline(0, color="black", linewidth=1)
    ax.set_title("Residuals in time order", fontsize=15)
    ax.set_xlabel("Time order", fontsize=15)
    ax.set_ylabel("Residuals", fontsize=15)

    for ax in axes:
        ax.tick_params(labelsize=13)
    save(fig, outdir, "residual-pattern-unmodelled-dynamics.png")


def _acf(series, nlags):
    centred = series - series.mean()
    denom = np.sum(centred ** 2)
    return np.array([
        np.sum(centred[k:] * centred[: len(series) - k]) / denom
        for k in range(nlags + 1)
    ])


def demonstrate_autocorrelation(outdir: pathlib.Path) -> None:
    # Same design as the original figure: three AR(1) processes with
    # phi = 0.95, 0.3 and -0.6, the autocorrelation function on top and
    # the series itself below. The seed is chosen so the leading run of
    # significant lags is exactly 16, 1 and 1: the sub-sampling gaps
    # the chapter prose quotes.
    rng = np.random.default_rng(153)
    n, nlags = 100, 20
    e = rng.normal(0, 1, (3, n))
    cases = []
    for i, (phi, title) in enumerate((
        (0.95, r"Long autocorrelation: $\phi = 0.95$"),
        (0.3, r"Medium autocorrelation: $\phi = 0.3$"),
        (-0.6, r"Negative autocorrelation: $\phi = -0.6$"),
    )):
        series = np.zeros(n)
        for k in range(1, n):
            series[k] = phi * series[k - 1] + e[i, k]
        cases.append((series, title))

    bound = 1.96 / np.sqrt(n)
    fig, axes = plt.subplots(2, 3, figsize=(14, 9.3))
    for col, (series, title) in enumerate(cases):
        ax = axes[0, col]
        ax.grid(color=GRID, linewidth=0.6)
        acf = _acf(series, nlags)
        markers, stems, base = ax.stem(np.arange(nlags + 1), acf, basefmt="k-")
        plt.setp(stems, color=BLUE, linewidth=1.8)
        plt.setp(markers, color=BLUE, markersize=5)
        for b in (-bound, bound):
            ax.axhline(b, color=VERMILLION, linewidth=1.2, linestyle="--")
        run = 1
        while run <= nlags and abs(acf[run]) > bound:
            run += 1
        ax.text(0.97, 0.85, f"Significant\nto lag {run - 1}",
                transform=ax.transAxes, ha="right", fontsize=13)
        ax.set_title(title, fontsize=15)
        ax.set_xlabel("Lag", fontsize=14)
        ax.tick_params(labelsize=13)

        ax = axes[1, col]
        ax.grid(color=GRID, linewidth=0.6)
        ax.plot(series, "o-", color=BLUE, markersize=3.5, linewidth=0.9)
        ax.axhline(0, color=GREY, linewidth=1, linestyle="--")
        ax.set_xlabel("Index", fontsize=14)
        ax.tick_params(labelsize=13)
    axes[0, 0].set_ylabel("Autocorrelation", fontsize=14)
    axes[1, 0].set_ylabel("Value", fontsize=14)
    save(fig, outdir, "demonstrate-autocorrelation.png")


def _nonlinear_data():
    rng = np.random.default_rng(42)
    x = np.arange(5, 9.05, 0.1)
    y = (0.4 * x + np.exp(0.6 * x) - 2 + rng.normal(0, 9, x.size)) / 2.3
    return x, y


def nonlinear_linear_region(outdir: pathlib.Path) -> None:
    x, y = _nonlinear_data()
    lo, hi = 6.05, 7.95
    inside = (x > lo) & (x < hi)
    slope, intercept = np.polyfit(x[inside], y[inside], 1)

    fig, ax = plt.subplots(figsize=(7, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x[~inside], y[~inside], "o", color=BLUE, markersize=7, alpha=0.8,
            label="Outside the model region")
    ax.plot(x[inside], y[inside], "^", color=ORANGE, markersize=8,
            label="Used to build the model")
    for v in (lo, hi):
        ax.axvline(v, color=GREY, linestyle="--", linewidth=1.2)
    xr = np.array([lo, hi])
    ax.plot(xr, intercept + slope * xr, color=VERMILLION, linewidth=2.5,
            linestyle="--")
    grid, fitted = _lowess(x, y, frac=0.4)
    ax.plot(grid, fitted, color=GREY, linewidth=1.5, linestyle=":")
    # Placed in the empty band above the model-region points, below
    # the legend.
    ytext = y.max() * 0.66
    ax.annotate("", xy=(hi, ytext), xytext=(lo, ytext),
                arrowprops=dict(arrowstyle="<->", color="black", linewidth=1.5))
    ax.text((lo + hi) / 2, ytext + y.max() * 0.02, "Model region", ha="center",
            fontsize=16)
    ax.set_xlabel("x", fontsize=17)
    ax.set_ylabel("y", fontsize=17)
    ax.tick_params(labelsize=15)
    ax.legend(loc="upper left", frameon=False, fontsize=13)
    save(fig, outdir, "nonlinear-linear-region.png")


def nonlinear_detection(outdir: pathlib.Path) -> None:
    x, y = _nonlinear_data()
    slope, intercept, fitted, residuals = _fit(x, y)
    fig, axes = plt.subplots(1, 3, figsize=(16, 5.3))
    panels = [
        (x, y, "x", "y", False),
        (x, residuals, "x", "Residuals", True),
        (fitted, residuals, r"Fitted values, $\hat{y}$", "Residuals", True),
    ]
    for ax, (px, py, xlabel, ylabel, is_resid) in zip(axes, panels):
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(px, py, "o", color=BLUE, markersize=6, alpha=0.8)
        if is_resid:
            ax.axhline(0, color="black", linewidth=1)
            grid, smooth = _lowess(px, py, frac=0.5)
            ax.plot(grid, smooth, color=VERMILLION, linewidth=2, linestyle="--")
        else:
            ax.plot(px, intercept + slope * px, color=VERMILLION, linewidth=2)
        ax.set_xlabel(xlabel, fontsize=18)
        ax.set_ylabel(ylabel, fontsize=18)
        ax.tick_params(labelsize=16)
    save(fig, outdir, "nonlinear-detection.png")


def non_normal_errors(outdir: pathlib.Path) -> None:
    # The real dataset the original used (kuiper.csv, in this
    # directory): 804 used GM vehicles, price against mileage. Rows
    # 151 to 160 are the Cadillac convertibles the prose discusses.
    import pandas as pd

    cars = pd.read_csv(pathlib.Path(__file__).parent / "kuiper.csv")
    mileage = cars["Mileage"].to_numpy(dtype=float)
    price = cars["Price"].to_numpy(dtype=float)
    slope_all, _, _, resid_all = _fit(mileage, price)

    keep = np.ones(len(cars), dtype=bool)
    keep[150:160] = False
    slope_rm, _, _, resid_clean = _fit(mileage[keep], price[keep])
    for label, slope, resid, k in (
        ("all data", slope_all, resid_all, 2),
        ("Cadillacs removed", slope_rm, resid_clean, 2),
    ):
        se = np.sqrt(np.sum(resid ** 2) / (len(resid) - k))
        print(f"price ~ mileage, {label}: b1 = {slope:.4f}, SE = {se:.0f}")

    fig, axes = plt.subplots(1, 2, figsize=(14, 9))
    _qq_axes(axes[0], resid_all, "All data")
    _qq_axes(axes[1], resid_clean, "After removing the 'outlier' cars")
    axes[0].annotate(
        "Cadillac convertibles",
        xy=(2.15, 40000), xytext=(-3.2, 40000),
        arrowprops=dict(arrowstyle="->", color=BLUE, linewidth=2),
        color=BLUE, fontsize=18, va="center",
    )
    for ax in axes:
        ax.set_ylabel("Residuals: price ~ mileage [$]", fontsize=18)
    save(fig, outdir, "non-normal-errors-outliers.png")


def _studentized(x, y):
    """Externally studentized residuals of the straight-line fit."""
    n, k = len(x), 2
    _, _, _, e = _fit(x, y)
    h = 1 / n + (x - x.mean()) ** 2 / np.sum((x - x.mean()) ** 2)
    rss = np.sum(e ** 2)
    return e * np.sqrt((n - k - 1) / (rss * (1 - h) - e ** 2))


def transformation_required(outdir: pathlib.Path) -> None:
    # Same data recipe as the original R script: x from a scaled
    # t-distribution, y = (2x + 3/x - noise)^2. As in the original
    # (car::qq.plot on the model object), both panels show studentized
    # residuals against t-distribution quantiles, so the two are on
    # the same dimensionless scale.
    rng = np.random.default_rng(7)
    n = 100
    x = stats.t.rvs(df=6, size=n, random_state=rng) * 2 + 7
    base = 2 * x + 3 / x - rng.normal(0, 8, n)
    y = base ** 2

    tdist = stats.t(df=n - 3)
    fig, axes = plt.subplots(1, 2, figsize=(14, 8))
    _qq_axes(axes[0], _studentized(x, y), "Original data: y ~ x", dist=tdist)
    _qq_axes(axes[1], _studentized(x, np.sqrt(y)),
             r"After a square root transformation: $\sqrt{y}$ ~ x", dist=tdist)
    axes[0].set_ylabel("Studentized residuals: y ~ x", fontsize=18)
    axes[1].set_ylabel(r"Studentized residuals: $\sqrt{y}$ ~ x", fontsize=18)
    for ax in axes:
        ax.set_xlabel("t-distribution quantile", fontsize=18)
    save(fig, outdir, "non-normal-errors-transformation-required.png")


def logistic_function(outdir: pathlib.Path) -> None:
    z = np.linspace(-4, 4, 801)
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.grid(color=GRID, linewidth=0.8)
    for h in (0, 1):
        ax.axhline(h, color=GREY, linestyle=":", linewidth=1.5)
    ax.plot(z, stats.norm.cdf(z), color=BLUE, linewidth=2.5)
    ax.set_xlabel("Function input", fontsize=14)
    ax.set_ylabel("Function output", fontsize=14)
    ax.tick_params(labelsize=13)
    ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    save(fig, outdir, "logistic-regression-function.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    correlation_calculation(outdir)
    residual_histogram(outdir)
    non_constant_error(outdir)
    unmodelled_dynamics(outdir)
    demonstrate_autocorrelation(outdir)
    nonlinear_linear_region(outdir)
    nonlinear_detection(outdir)
    non_normal_errors(outdir)
    transformation_required(outdir)
    logistic_function(outdir)
