"""Exercise figures for the process-monitoring chapter of the PID book.

Thirteen committed PNGs, replacing images previously generated by base-R
scripts (``aeration-rate-monitoring.R``, ``Kappa-number-monitoring.R``,
``CO2-question.R``, ``batch-yield-and-purity-recursive.R``,
``batch-yields-monitoring-assignment4-2010.R``,
``plastic-sheet-control-specification-limits.R``). These serve
``process-monitoring/process-monitoring-exercises.rst``:

- ``aeration-rate-raw-data.png``, ``aeration-CUSUM.png``,
  ``aeration-Shewhart-chart.png``: the aeration rate of a bioreactor
  (https://openmv.net/info/aeration-rate), shown raw, as a CUSUM about
  the phase I median, and as a Shewhart chart of subgroup means.
- ``Kappa-raw-data.png``, ``Kappa-phaseI-first-round.png``,
  ``Kappa-phaseI-second-round.png``, ``Kappa-phaseII-testing.png``: the
  Kappa number of pulp (https://openmv.net/info/kappa-number), with the
  first 2000 observations as phase I and the rest as phase II.
- ``CO2-raw-data.png``, ``CO2-phaseI-first-round.png``: carbon dioxide
  off a gas furnace (https://openmv.net/info/gas-furnace).
- ``batch-yield-phaseI-round-1-Yield.png``,
  ``batch-yield-phaseI-round-2-Yield.png``: two rounds of pruning the
  phase I limits for https://openmv.net/info/batch-yield-and-purity.
- ``batch-yields-monitoring.png``: a Shewhart chart of the bioreactor
  yields in https://openmv.net/info/batch-yields.
- ``plastic-sheet-control-specification-limits.png``: the distribution
  of a single measurement against the distribution of the subgroup mean,
  with the specification limits and the control limits marked, showing
  that the two kinds of limit answer different questions.

Two corrections to the originals:

- The aeration Shewhart chart hard-coded its control limits as 22.1 and
  25.8. They are computed here from the first 200 observations, the same
  window that sets the CUSUM target, and come out at 22.12 and 25.77.
- The Kappa figures were drawn with subgroups of 5, while the solution
  text says 6 and quotes limits (18.26 / 21.73 / 25.21, then
  18.24 / 21.71 / 25.19, from 333 phase I subgroups) that only size 6
  reproduces. These use 6, so the charts agree with the numbers beside
  them.

All datasets are fetched from openmv.net; a local CSV of the same name
next to this script is used as a fallback when offline. The script
prints the limits and counts quoted in the exercise solutions.

Usage
-----
    uv run --with numpy --with pandas --with scipy --with matplotlib python monitoring_exercise_figures.py [output_dir]

Writes the thirteen PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.special import gamma
from scipy.stats import norm

BLUE = "#0072B2"
GREEN = "#009E73"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
NEAR_BLACK = "#222222"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

# These charts are wide and short, so the labels sit a little smaller
# than in the taller main-body monitoring figures.
mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def fetch(name: str) -> pd.DataFrame:
    try:
        return pd.read_csv(f"https://openmv.net/file/{name}")
    except Exception:
        return pd.read_csv(HERE / name)


def a_n(n: int) -> float:
    """Unbiasing constant so that S / a_n estimates sigma without bias."""
    return float(np.sqrt(2) * gamma(n / 2) / (np.sqrt(n - 1) * gamma((n - 1) / 2)))


def subgroup_stats(values: np.ndarray, size: int) -> tuple[np.ndarray, np.ndarray]:
    """Mean and standard deviation within consecutive subgroups."""
    n_groups = len(values) // size
    grouped = values[: n_groups * size].reshape(n_groups, size)
    return grouped.mean(axis=1), grouped.std(axis=1, ddof=1)


def shewhart_limits(xbar, sd, size: int, n_sigma: float = 3.0):
    """Return (LCL, target, UCL) for a chart of subgroup means."""
    target = float(np.mean(xbar))
    half = n_sigma * float(np.mean(sd)) / (a_n(size) * np.sqrt(size))
    return target - half, target, target + half


def draw_limits(ax, lcl: float, target: float, ucl: float) -> None:
    ax.axhline(ucl, color=VERMILLION, linewidth=2)
    ax.axhline(lcl, color=VERMILLION, linewidth=2)
    ax.axhline(target, color=GREEN, linewidth=2)


def chart(outdir, name, x, y, xlabel, ylabel, *, style="-o", limits=None,
          figsize=(12, 5), markersize=4, ylim=None, linewidth=1.2):
    fig, ax = plt.subplots(figsize=figsize)
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, y, style, color=BLUE, markersize=markersize, linewidth=linewidth)
    if limits is not None:
        draw_limits(ax, *limits)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    if ylim is not None:
        ax.set_ylim(*ylim)
    save(fig, outdir, name)


# --------------------------------------------------------------------
# Aeration rate
# --------------------------------------------------------------------
def aeration(outdir: pathlib.Path) -> None:
    rate = fetch("aeration-rate.csv")["Aeration"].dropna().to_numpy(dtype=float)
    time = np.arange(1, len(rate) + 1)
    size = 5

    chart(outdir, "aeration-rate-raw-data.png", time, rate,
          "Time (min)", "Aeration rate (L/min)", style="-", figsize=(12, 4.5))

    # CUSUM about the median of the first 200 minutes.
    target = float(np.median(rate[:200]))
    cusum = np.cumsum(rate - target)
    detected = int(time[np.argmax(np.abs(cusum) > 0.5 * np.abs(cusum).max())])
    print(f"aeration: n {len(rate)}, CUSUM target {target:.2f}")

    fig, ax = plt.subplots(figsize=(12, 4.5))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(time, cusum, color=BLUE, linewidth=1.4)
    ax.axhline(0, color=GREY, linewidth=1.2)
    ax.set_xlabel("Time (min)")
    ax.set_ylabel("CUSUM cumulative deviations")
    save(fig, outdir, "aeration-CUSUM.png")

    # Shewhart chart of subgroup means. The limits come from the same
    # first 200 observations that set the CUSUM target.
    xbar, sd = subgroup_stats(rate, size)
    phase1 = 200 // size
    lcl, centre, ucl = shewhart_limits(xbar[:phase1], sd[:phase1], size)
    print(f"  Shewhart from first {phase1} subgroups: "
          f"LCL {lcl:.2f}, target {centre:.2f}, UCL {ucl:.2f}")

    order = np.arange(1, len(xbar) * size + 1, size)
    fig, ax = plt.subplots(figsize=(12, 4.5))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(order, xbar, "-s", color=BLUE, markersize=4, linewidth=0.9)
    draw_limits(ax, lcl, centre, ucl)
    # Leave room above and below the control limits. Autoscaling on the
    # data alone puts the limits hard against the frame, which reads as
    # though the chart has been cropped, and leaves the annotation
    # sitting on top of the upper limit.
    span = ucl - lcl
    ax.set_ylim(min(lcl, xbar.min()) - 0.35 * span,
                max(ucl, xbar.max()) + 0.35 * span)
    ax.axvline(275, color=ORANGE, linewidth=2)
    # The line stays orange, which separates it from the vermillion
    # control limits and the green target. The label is near-black: the
    # orange is light enough that text set in it is hard to read against
    # white, and it prints poorly in greyscale. The original set this
    # label in black too.
    ax.annotate("CUSUM detected the problem at t = 275", xy=(290, ucl),
                xytext=(0, 12), textcoords="offset points",
                ha="left", va="bottom", color=NEAR_BLACK, fontsize=15)
    ax.set_xlabel("Time order")
    ax.set_ylabel("Phase II subgroups")
    save(fig, outdir, "aeration-Shewhart-chart.png")


# --------------------------------------------------------------------
# Kappa number
# --------------------------------------------------------------------
def kappa(outdir: pathlib.Path) -> None:
    values = fetch("kappa-number.csv")["Kappa"].to_numpy(dtype=float)
    # The solution text says "I used subgroups of size 6", and the limits
    # it quotes (18.26 / 21.73 / 25.21, then 18.24 / 21.71 / 25.19, from
    # 333 phase I subgroups) only come out at size 6. The R script beside
    # these figures used 5, so the images disagreed with the numbers
    # printed next to them.
    size = 6
    n_phase1 = 2000
    print(f"kappa: n {len(values)}, phase I {n_phase1}, subgroup {size}")

    # 1. All the raw data, split into the two phases.
    fig, ax = plt.subplots(figsize=(12, 4.5))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(np.arange(1, len(values) + 1), values, ".", color=BLUE,
            markersize=2, alpha=0.6)
    ax.axvline(n_phase1, color=GREY, linewidth=1.5)
    low = ax.get_ylim()[0]
    # Near-black, for the same reason as the CUSUM label: orange text is
    # too light to read against white. Blue, which the original used,
    # would be lost among the data points here.
    ax.text(n_phase1 / 2, low + 1, "Phase I data", ha="center", color=NEAR_BLACK)
    ax.text(n_phase1 + (len(values) - n_phase1) / 2, low + 1, "Phase II data",
            ha="center", color=NEAR_BLACK)
    ax.set_xlabel("Sequence order")
    ax.set_ylabel("Kappa number: raw data")
    save(fig, outdir, "Kappa-raw-data.png")

    xbar, sd = subgroup_stats(values, size)
    phase1_end = n_phase1 // size

    # 2. Round 1: limits from every phase I subgroup.
    x1, s1 = xbar[:phase1_end], sd[:phase1_end]
    lcl, centre, ucl = shewhart_limits(x1, s1, size)
    outside = (x1 < lcl) | (x1 > ucl)
    print(f"  round 1: LCL {lcl:.2f}, target {centre:.2f}, UCL {ucl:.2f}; "
          f"{outside.sum()} of {len(x1)} subgroups outside")
    chart(outdir, "Kappa-phaseI-first-round.png",
          np.arange(1, len(x1) + 1), x1,
          "Sequence order", "Phase I subgroups: round 1",
          limits=(lcl, centre, ucl), figsize=(12, 4.5), markersize=3)

    # 3. Round 2: drop those subgroups and recompute.
    keep = ~outside
    x2, s2 = x1[keep], s1[keep]
    lcl, centre, ucl = shewhart_limits(x2, s2, size)
    still_out = ((x2 < lcl) | (x2 > ucl)).sum()
    print(f"  round 2: LCL {lcl:.2f}, target {centre:.2f}, UCL {ucl:.2f}; "
          f"{still_out} of {len(x2)} subgroups outside")
    chart(outdir, "Kappa-phaseI-second-round.png",
          np.arange(1, len(x2) + 1), x2,
          "Sequence order", "Phase I subgroups: round 2",
          limits=(lcl, centre, ucl), figsize=(12, 4.5), markersize=3)

    # 4. Phase II, using the phase I limits. The solution refers to
    # "sequence point 80 and 140", so phase II is numbered from 1.
    x_phase2 = xbar[phase1_end:]
    alarms = ((x_phase2 < lcl) | (x_phase2 > ucl)).sum()
    print(f"  phase II: {alarms} of {len(x_phase2)} subgroups outside the "
          f"limits ({100 * alarms / len(x_phase2):.1f}%)")
    chart(outdir, "Kappa-phaseII-testing.png",
          np.arange(1, len(x_phase2) + 1), x_phase2,
          "Sequence order", "Phase II subgroups: testing",
          limits=(lcl, centre, ucl), figsize=(12, 4.5), markersize=3)


# --------------------------------------------------------------------
# Gas furnace carbon dioxide
# --------------------------------------------------------------------
def carbon_dioxide(outdir: pathlib.Path) -> None:
    co2 = fetch("gas-furnace.csv")["CO2"].to_numpy(dtype=float)
    size = 6
    print(f"CO2: n {len(co2)}, subgroup {size}")

    chart(outdir, "CO2-raw-data.png", np.arange(1, len(co2) + 1), co2,
          "Sequence order", "CO$_2$: raw data", style=".",
          figsize=(12, 4.5), markersize=5, linewidth=0)

    xbar, sd = subgroup_stats(co2, size)
    lcl, centre, ucl = shewhart_limits(xbar, sd, size)
    outside = ((xbar < lcl) | (xbar > ucl)).sum()
    print(f"  round 1: LCL {lcl:.2f}, target {centre:.2f}, UCL {ucl:.2f}; "
          f"{outside} of {len(xbar)} subgroups outside")
    chart(outdir, "CO2-phaseI-first-round.png",
          np.arange(1, len(xbar) + 1), xbar,
          "Sequence order", "Phase I subgroups: round 1",
          limits=(lcl, centre, ucl), figsize=(12, 4.5), markersize=4)


# --------------------------------------------------------------------
# Batch yield and purity: two rounds of pruning
# --------------------------------------------------------------------
def batch_yield_and_purity(outdir: pathlib.Path) -> None:
    yields = fetch("batch-yield-and-purity.csv")["yield"].to_numpy(dtype=float)
    size = 3
    xbar, sd = subgroup_stats(yields, size)
    span = (xbar.min() - 5, xbar.max() + 5)
    print(f"batch yield and purity: n {len(yields)}, subgroup {size}")

    for round_number in (1, 2):
        lcl, centre, ucl = shewhart_limits(xbar, sd, size)
        outside = (xbar < lcl) | (xbar > ucl)
        print(f"  round {round_number}: LCL {lcl:.2f}, target {centre:.2f}, "
              f"UCL {ucl:.2f}; {outside.sum()} of {len(xbar)} outside")
        chart(outdir, f"batch-yield-phaseI-round-{round_number}-Yield.png",
              np.arange(1, len(xbar) + 1), xbar,
              "Sequence order", f"Phase I subgroups: round {round_number}",
              limits=(lcl, centre, ucl), figsize=(12, 4.5), markersize=4,
              ylim=span)
        xbar, sd = xbar[~outside], sd[~outside]


# --------------------------------------------------------------------
# Batch yields Shewhart chart
# --------------------------------------------------------------------
def batch_yields(outdir: pathlib.Path) -> None:
    yields = fetch("batch-yields.csv")["Yield"].to_numpy(dtype=float)
    size = 5
    xbar, sd = subgroup_stats(yields, size)
    lcl, centre, ucl = shewhart_limits(xbar, sd, size)
    print(f"batch yields: {len(xbar)} subgroups of {size}; "
          f"LCL {lcl:.2f}, target {centre:.2f}, UCL {ucl:.2f}")

    fig, ax = plt.subplots(figsize=(11, 6))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(np.arange(1, len(xbar) + 1), xbar, "o", color=BLUE, markersize=6)
    draw_limits(ax, lcl, centre, ucl)
    ax.set_title("Shewhart chart")
    ax.set_xlabel("Subgroup number")
    ax.set_ylabel("Subgroup means")
    ax.set_ylim(lcl - 5, ucl + 5)
    save(fig, outdir, "batch-yields-monitoring.png")


# --------------------------------------------------------------------
# Control limits are not specification limits
# --------------------------------------------------------------------
def control_versus_specification(outdir: pathlib.Path) -> None:
    size = 4
    capability = 1.7
    width = 0.8
    sigma = width / capability / 6
    centre = 2.0
    lsl, usl = centre - 0.4, centre + 0.4
    lcl = centre - 3 * sigma / np.sqrt(size)
    ucl = centre + 3 * sigma / np.sqrt(size)
    print(f"plastic sheet: sigma {sigma:.4f}, LCL {lcl:.3f}, UCL {ucl:.3f}, "
          f"LSL {lsl:.1f}, USL {usl:.1f}")

    x = np.linspace(lsl - 0.1 * width, usl + 0.1 * width, 1001)
    single = norm.pdf(x, loc=centre, scale=sigma)
    of_the_mean = norm.pdf(x, loc=centre, scale=sigma / np.sqrt(size))

    fig, ax = plt.subplots(figsize=(11, 7))
    ax.plot(x, of_the_mean, color=BLUE, linewidth=3,
            label="Distribution of the subgroup mean")
    ax.plot(x, single, color=GREY, linewidth=2,
            label="Distribution of a single measurement")
    ax.axvline(centre, color="black", linewidth=1)

    top = of_the_mean.max() * 0.8
    for bound, label, colour in ((lsl, "LSL", GREY), (usl, "USL", GREY),
                                 (lcl, "LCL", VERMILLION),
                                 (ucl, "UCL", VERMILLION)):
        ax.vlines(bound, 0, top, color=colour, linewidth=2)
        ax.text(bound, top, label, ha="center", va="bottom", color=colour,
                fontsize=17)

    # Mark each spread with a double-headed arrow at its own height.
    for spread, label in ((sigma, r"$\sigma$"),
                          (sigma / np.sqrt(size), r"$\sigma/\sqrt{n}$")):
        height = norm.pdf(centre + spread, loc=centre,
                          scale=spread if spread == sigma else sigma / np.sqrt(size))
        ax.annotate("", xy=(centre + spread, height), xytext=(centre, height),
                    arrowprops=dict(arrowstyle="<->", color="black", linewidth=1.8))
        ax.text(centre + spread * 1.06, height, f" {label}", ha="left",
                va="center", fontsize=19)

    ax.set_title(r"$\mu = 2.0$")
    ax.set_xlabel("$x$")
    ax.set_yticks([])
    ax.set_xlim(lsl, usl)
    ax.set_ylim(0, of_the_mean.max() * 1.12)
    ax.spines["left"].set_visible(False)
    ax.legend(loc="upper left", frameon=False, fontsize=14)
    save(fig, outdir, "plastic-sheet-control-specification-limits.png")


def monitoring_chart_cycling(outdir: pathlib.Path) -> None:
    """Feed weight that cycles, and a Shewhart chart that hides it.

    The measurements behind the original figure are not recoverable: the
    R script reads a CSV from a path on the author's laptop and writes a
    different filename. This is a seeded reconstruction of the series the
    question describes: 100 consecutive measurements one minute apart,
    cycling in a saw-tooth between roughly 1 and 3 kg/s about a target of
    2 kg/s. Substitute the recorded data here if it turns up.

    The control limits are computed from the series actually plotted,
    and are not tuned to reproduce the ones in the original image (which
    measure at 0.96, 1.94 and 2.91 against the 0.99, 1.91 and 2.83 here).
    Matching the picture would mean choosing the amplitude and noise to
    hit numbers read off a bitmap, which would make the chart agree with
    a figure whose data no longer exists while disagreeing with its own.
    The values are printed on the chart so a reader can check them
    against a run of this script.

    Subgroups are the twenty consecutive, non-overlapping groups of five
    that the solution text describes. For each, the mean and the standard
    deviation with one degree of freedom removed. The centre line is the
    mean of the twenty subgroup means; the limits are three standard
    errors either side, using the mean within-subgroup standard deviation
    corrected for bias, ``3 * mean(s) / (a_n * sqrt(n))``, with
    ``a_n = 0.9400`` at ``n = 5``.
    """
    rng = np.random.default_rng(4)
    n = 100
    size = 5
    target = 2.0
    time = np.arange(1, n + 1)
    # A saw-tooth whose period is close to the subgroup size, which is
    # what lets the subgroup means average the cycle away.
    period = 6.5
    phase = (time % period) / period
    feed = target + 0.85 * (2 * phase - 1) + rng.normal(scale=0.32, size=n)

    xbar, sd = subgroup_stats(feed, size)
    lcl, centre, ucl = shewhart_limits(xbar, sd, size)
    inside = ((xbar >= lcl) & (xbar <= ucl)).sum()
    print(f"cycling: LCL {lcl:.2f}, target {centre:.2f}, UCL {ucl:.2f}; "
          f"{inside} of {len(xbar)} subgroup means inside the limits")

    fig, axes = plt.subplots(2, 1, figsize=(13, 8))

    ax = axes[0]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(time, feed, "-o", color=BLUE, markersize=5, linewidth=1,
            markerfacecolor="none")
    ax.set_title("Raw data: weight of feed entering")
    ax.set_xlabel("Time-ordered samples")
    ax.set_ylabel("Feed [kg/s]")
    ax.set_ylim(0, 3.8)

    ax = axes[1]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(np.arange(1, len(xbar) + 1), xbar, "-s", color=BLUE, markersize=6,
            linewidth=1)
    draw_limits(ax, lcl, centre, ucl)
    # Show the values, not just the names: they come out of the data
    # plotted above, so a reader can reproduce them.
    ax.text(0.6, ucl, f" UCL = {ucl:.2f}", color=VERMILLION, va="bottom",
            fontsize=15)
    ax.text(0.6, lcl, f" LCL = {lcl:.2f}", color=VERMILLION, va="top",
            fontsize=15)
    ax.text(len(xbar) + 0.4, centre, f" {centre:.2f}", color=GREEN,
            va="center", fontsize=15)
    ax.set_title("Shewhart chart: weight of feed entering")
    ax.set_xlabel("Time order")
    ax.set_ylabel("Subgroup mean")
    ax.set_xticks(np.arange(2, len(xbar) + 1, 2))
    ax.set_ylim(lcl - 0.35, ucl + 0.35)
    save(fig, outdir, "monitoring-chart-cycling.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    aeration(outdir)
    kappa(outdir)
    carbon_dioxide(outdir)
    batch_yield_and_purity(outdir)
    batch_yields(outdir)
    control_versus_specification(outdir)
    monitoring_chart_cycling(outdir)
