"""Shewhart, weights, and capability figures for the process-monitoring chapter.

Five committed PNGs, replacing images previously generated by base-R
scripts (``explain-shewhart.R``, ``explain-weights-for-process-monitoring.R``,
``explain-PCR.R``, ``show-shift-typeII-error.R``):

- ``explain-shewhart.png``: raw-data distribution (sigma = 2) against
  the narrower distribution of subgroup means (n = 5), with the plus
  and minus 3-sigma-of-the-mean control limits.
- ``explain-weights-for-process-monitoring.png``: the weight each
  historical observation receives in the Shewhart, CUSUM, moving
  average (N = 5), and EWMA (lambda = 0.6) statistics.
- ``explain-PCR-half.png`` and ``explain-PCR-two.png``: a process with
  specification limits at 65 and 95 cP and centred at 80 cP, drawn for
  Cp = 0.5 and Cp = 2.0.
- ``show-shift-beta-error.png``: the original and shifted distributions
  of the subgroup mean, with the region of the shifted distribution
  still inside the control limits shaded (the type II error).

All quantities are deterministic (no random data). Font sizes match the
pixel height of the labels in the originals.

Usage
-----
    uv run --with numpy --with scipy --with matplotlib python shewhart_capability_figures.py [output_dir]
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

BLUE = "#0072B2"
ORANGE = "#E69F00"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300

mpl.rcParams.update(
    {
        "font.size": 17,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 20,
        "axes.labelsize": 21,
        "xtick.labelsize": 19,
        "ytick.labelsize": 19,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str, dpi: int = DPI) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=dpi)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def explain_shewhart(outdir: pathlib.Path) -> None:
    mean, sd, n = 6.0, 2.0, 5
    sd_xbar = sd / np.sqrt(n)
    x = np.linspace(0, 12, 601)
    fig, ax = plt.subplots(figsize=(10, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, stats.norm.pdf(x, mean, sd_xbar), color=BLUE, linewidth=3.5,
            label="Subgroup mean's distribution")
    ax.plot(x, stats.norm.pdf(x, mean, sd), color=GREY, linewidth=1.5,
            label=r"Raw data's distribution: $\sigma = 2$")
    ax.axvline(mean, color="black", linewidth=1)
    for v in (mean - 3 * sd_xbar, mean + 3 * sd_xbar):
        ax.axvline(v, color=VERMILLION, linewidth=2.5)
    ax.plot([], [], color=VERMILLION, linewidth=2.5, label="Control limits")
    ax.legend(loc="upper left", frameon=False)

    y = 0.35
    ax.annotate("", xy=(mean + 3 * sd_xbar, y), xytext=(mean, y),
                arrowprops=dict(arrowstyle="->", color="black", linewidth=1.5))
    ax.text(mean + 1.5 * sd_xbar, y + 0.008, r"$3\sigma_{\bar{x}}$",
            ha="center", fontsize=20)
    y = 0.122
    ax.annotate("", xy=(mean + sd, y), xytext=(mean, y),
                arrowprops=dict(arrowstyle="->", color="black", linewidth=1.5))
    ax.text(mean + 0.5 * sd, y + 0.008, r"$\sigma$", ha="center", fontsize=20)
    ax.text(1.4, 0.16, "Subgroup size, n = 5", ha="center", fontsize=17)
    ax.text(8.6, 0.23, r"$\sigma_{\bar{x}} = 2/\sqrt{5}$", fontsize=20)

    ax.set_xlabel("$x$")
    ax.set_ylabel("Probability density")
    ax.set_title("Shewhart chart: using theoretical (usually unknown) parameters")
    ax.set_xlim(0, 12)
    ax.set_yticks([0, 0.1, 0.2, 0.3, 0.4])
    save(fig, outdir, "explain-shewhart.png")


def explain_weights(outdir: pathlib.Path) -> None:
    N = 12
    shewhart = np.zeros(N)
    shewhart[-1] = 1.0
    cusum = np.full(N, 1 / N)
    ma = np.zeros(N)
    ma[-5:] = 0.2
    lam = 0.6
    ewma = np.array([lam * (1 - lam) ** (N - 1 - i) for i in range(N)])

    panels = [
        (shewhart, "Shewhart weights"),
        (cusum, f"CUSUM weights; each weight is {1 / N:.4f}"),
        (ma, "MA weights when N = 5"),
        (ewma, r"EWMA weights when $\lambda = 0.6$"),
    ]
    ticklabels = ["", "", "", "", "", "...", "", "t-4", "", "t-2", "", "t"]
    fig, axes = plt.subplots(2, 2, figsize=(9, 7), sharey=True)
    for ax, (weights, title) in zip(axes.flat, panels):
        ax.grid(color=GRID, linewidth=0.8)
        markers, stems, base = ax.stem(np.arange(N), weights, basefmt="k-")
        plt.setp(stems, color=BLUE, linewidth=2)
        plt.setp(markers, color=BLUE, markersize=7)
        plt.setp(base, linewidth=1)
        ax.set_title(title, fontsize=13)
        ax.set_xticks(np.arange(N), ticklabels, fontsize=12)
        ax.set_ylim(0, 1.05)
        ax.tick_params(axis="y", labelsize=12)
    save(fig, outdir, "explain-weights-for-process-monitoring.png")


def explain_pcr(outdir: pathlib.Path, cp: float, name: str) -> None:
    lsl, usl, mean = 65.0, 95.0, 80.0
    sd = (usl - lsl) / (6 * cp)
    x = np.linspace(20, 140, 961)
    fig, ax = plt.subplots(figsize=(13, 6.3))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, stats.norm.pdf(x, mean, sd), color=BLUE, linewidth=2.5)
    ax.axvline(mean, color=GREY, linewidth=1, linestyle=":")
    for v, label in ((lsl, "LSL = 65"), (usl, "USL = 95")):
        ax.axvline(v, color=VERMILLION, linewidth=2)
        ax.text(v, ax.get_ylim()[1] * 0.97, label, ha="center", va="bottom",
                color=VERMILLION, fontsize=18)
    ax.set_title(f"Process capability ratio = {cp:g}", fontsize=20)
    ax.set_xlabel("Viscosity [cP]")
    ax.set_ylabel("Probability density")
    ax.set_xlim(20, 140)
    save(fig, outdir, name)


def show_shift_beta_error(outdir: pathlib.Path) -> None:
    mean, sd, n, delta = 6.0, 1.0, 4, 1.0
    sd_xbar = sd / np.sqrt(n)
    lcl, ucl = mean - 3 * sd_xbar, mean + 3 * sd_xbar
    x = np.linspace(1, 11, 1001)
    original = stats.norm.pdf(x, mean, sd_xbar)
    shifted = stats.norm.pdf(x, mean + delta, sd_xbar)

    fig, ax = plt.subplots(figsize=(12.4, 6.1))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(x, original, color=BLUE, linewidth=2.5, label="Original distribution")
    ax.plot(x, shifted, color=VERMILLION, linewidth=2.5, linestyle="--",
            label="Shifted distribution")
    inside = (x >= lcl) & (x <= ucl)
    ax.fill_between(x[inside], shifted[inside], color=ORANGE, alpha=0.45,
                    label="Shifted values not detected (type II error)")
    for v in (lcl, mean, ucl):
        ax.axvline(v, color=GREY, linewidth=1)
    top = original.max()
    ax.annotate("", xy=(ucl, top * 1.12), xytext=(lcl, top * 1.12),
                arrowprops=dict(arrowstyle="<->", color="black", linewidth=1.5))
    ax.text(mean, top * 1.15, "From LCL to UCL", ha="center", fontsize=17)
    ax.annotate("", xy=(mean + delta, top * 1.02), xytext=(mean, top * 1.02),
                arrowprops=dict(arrowstyle="->", color="black", linewidth=1.5))
    ax.text(mean + delta / 2, top * 1.045, r"Shift $= \Delta\sigma$",
            ha="center", fontsize=17)
    ax.set_xlabel(r"$\bar{x}$")
    ax.set_ylabel("Probability density")
    ax.set_ylim(0, top * 1.25)
    ax.set_yticks([])
    ax.legend(loc="upper left", frameon=False)
    save(fig, outdir, "show-shift-beta-error.png", dpi=250)


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    explain_shewhart(outdir)
    explain_weights(outdir)
    explain_pcr(outdir, 0.5, "explain-PCR-half.png")
    explain_pcr(outdir, 2.0, "explain-PCR-two.png")
    show_shift_beta_error(outdir)
