"""Bar-plot figures for the data-visualization chapter of the PID book.

Two committed PNGs, replacing images previously generated by base-R
scripts (``quarterly-profit-barplot.R``, ``hatched-barplot.R``):

- ``quarterly-profit-barplot-vs-lineplot.png``: the same eight quarters
  of profit drawn as a bar plot and as a time-series (line) plot, the
  chapter's example of why time-ordered categories belong on a line
  plot. The numbers match the chapter's inline code.
- ``hatched-barplot.png``: the chapter's deliberately poor example of
  cross-hatching (the classic Death Rates in Virginia stacked bars).
  The hatching IS the point being criticised, so it stays; only the
  rendering is refreshed.

Usage
-----
    uv run --with numpy --with matplotlib python barplot_chapter_figures.py [output_dir]

Writes the two PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np

BLUE = "#0072B2"
GRID = "#DDDDDD"

DPI = 300

mpl.rcParams.update(
    {
        "font.size": 13,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 14,
        "axes.labelsize": 13,
        "axes.axisbelow": True,
    }
)

LABELS = ["2008 Q1", "Q2", "Q3", "Q4", "2009 Q1", "Q2", "Q3", "Q4"]
PROFIT = np.array([45, 32, 67, 23, 42, 56, 64, 92]) + 40

# The R VADeaths dataset: death rates per 1000 population per year,
# Virginia, 1940, by age group (rows) and population group (columns).
VA_AGE_GROUPS = ["50-54", "55-59", "60-64", "65-69", "70-74"]
VA_DEATHS = {
    "Rural Male": [11.7, 18.1, 26.9, 41.0, 66.0],
    "Rural Female": [8.7, 11.7, 20.3, 30.9, 54.3],
    "Urban Male": [15.4, 24.3, 37.0, 54.6, 71.1],
    "Urban Female": [8.4, 13.6, 19.3, 35.1, 50.0],
}


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def barplot_vs_lineplot(outdir: pathlib.Path) -> None:
    # Quarter labels repeat ("Q2" appears in both years), so plot against
    # numeric positions and label the ticks explicitly.
    x = np.arange(len(LABELS))
    fig, axes = plt.subplots(1, 2, figsize=(14, 7), sharey=False)

    ax = axes[0]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    bars = ax.bar(x, PROFIT, color=BLUE, width=0.65)
    ax.bar_label(bars, padding=3)
    ax.set_xticks(x, LABELS)
    ax.set_ylabel("Quarterly profit [$ '000]")
    ax.set_title("As a bar plot")

    ax = axes[1]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.plot(x, PROFIT, "o-", color=BLUE, linewidth=2, markersize=8)
    ax.set_xticks(x, LABELS)
    ax.set_ylabel("Quarterly profit [$ '000]")
    ax.set_title("As a time-series plot")
    save(fig, outdir, "quarterly-profit-barplot-vs-lineplot.png")


def hatched_barplot(outdir: pathlib.Path) -> None:
    # Deliberately busy: this figure illustrates the advice AGAINST
    # cross-hatching, so each age group keeps a distinct hatch pattern.
    hatches = ["////", "\\\\\\\\", "xxxx", "----", "++++"]
    fig, ax = plt.subplots(figsize=(7, 7))
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    x = np.arange(len(VA_DEATHS))
    bottom = np.zeros(len(VA_DEATHS))
    for age, hatch in zip(VA_AGE_GROUPS, hatches):
        heights = np.array([VA_DEATHS[group][VA_AGE_GROUPS.index(age)]
                            for group in VA_DEATHS])
        ax.bar(
            x, heights, bottom=bottom, width=0.7, label=age,
            facecolor="white", edgecolor="black", hatch=hatch, linewidth=0.8,
        )
        bottom += heights
    ax.set_xticks(x, list(VA_DEATHS), fontsize=11)
    ax.set_ylabel("Death rate per 1000 population per year")
    ax.set_title("Death rates in Virginia, 1940")
    ax.legend(title="Age group", fontsize=10, loc="upper left")
    save(fig, outdir, "hatched-barplot.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    barplot_vs_lineplot(outdir)
    hatched_barplot(outdir)
