"""Bar-plot figures for the data-visualization chapter of the PID book.

Four committed PNGs, replacing images previously generated by base-R
scripts (``quarterly-profit-barplot.R``, ``hatched-barplot.R``) and two
screenshots of an Apple Numbers spreadsheet:

- ``quarterly-profit-barplot-vs-lineplot.png``: the same eight quarters
  of profit drawn as a bar plot and as a time-series (line) plot, the
  chapter's example of why time-ordered categories belong on a line
  plot. The numbers match the chapter's inline code.
- ``hatched-barplot.png``: the chapter's deliberately poor example of
  cross-hatching (the classic Death Rates in Virginia stacked bars).
  The hatching IS the point being criticised, so it stays; only the
  rendering is refreshed.
- ``barplot-example-expenses.png``: a horizontal bar plot of household
  expenses with the category axis and the value axis called out, since
  the surrounding prose defines both terms.
- ``profit-by-region.png``: profit for six regions shown as a table next
  to the same numbers as a bar plot, the chapter's example of preferring
  a table when there are only a handful of data points.

The expense values were never published; they are measured off the
original screenshot against its 3000, 6000, 9000 and 12000 gridlines and
are accurate to about 10 units on a 0 to 12000 scale. They are
illustrative household expenses, not a real dataset.

Usage
-----
    uv run --with numpy --with matplotlib python barplot_chapter_figures.py [output_dir]

Writes the four PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np

BLUE = "#0072B2"
ORANGE = "#E69F00"
GRID = "#DDDDDD"

DPI = 300

# Font sizes match the pixel height of the labels in the base-R
# originals (pointsize 12-14 at the same DPI), slightly boosted.
mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 19,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 14,
        "axes.axisbelow": True,
    }
)

LABELS = ["2008 Q1", "Q2", "Q3", "Q4", "2009 Q1", "Q2", "Q3", "Q4"]
PROFIT = np.array([45, 32, 67, 23, 42, 56, 64, 92]) + 40

# The R VADeaths dataset: death rates per 1000 population per year,
# Virginia, 1940, by age group (rows) and population group (columns).
VA_AGE_GROUPS = ["50-54", "55-59", "60-64", "65-69", "70-74"]
VA_DEATHS = {
    "Rural Male": [11.7, 18.1, 26.9, 41.0, 66.0],
    "Rural Female": [8.7, 11.7, 20.3, 30.9, 54.3],
    "Urban Male": [15.4, 24.3, 37.0, 54.6, 71.1],
    "Urban Female": [8.4, 13.6, 19.3, 35.1, 50.0],
}


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def barplot_vs_lineplot(outdir: pathlib.Path) -> None:
    # Quarter labels repeat ("Q2" appears in both years), so plot against
    # numeric positions and label the ticks explicitly.
    x = np.arange(len(LABELS))
    fig, axes = plt.subplots(1, 2, figsize=(14, 7), sharey=False)

    ax = axes[0]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    bars = ax.bar(x, PROFIT, color=BLUE, width=0.65)
    ax.bar_label(bars, padding=3)
    ax.set_xticks(x, LABELS)
    ax.set_ylabel("Quarterly profit [$ '000]")
    ax.set_title("As a bar plot")

    ax = axes[1]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.plot(x, PROFIT, "o-", color=BLUE, linewidth=2, markersize=8)
    ax.set_xticks(x, LABELS)
    ax.set_ylabel("Quarterly profit [$ '000]")
    ax.set_title("As a time-series plot")
    save(fig, outdir, "quarterly-profit-barplot-vs-lineplot.png")


def hatched_barplot(outdir: pathlib.Path) -> None:
    # Deliberately busy: this figure illustrates the advice AGAINST
    # cross-hatching, so each age group keeps a distinct hatch pattern.
    hatches = ["////", "\\\\\\\\", "xxxx", "----", "++++"]
    fig, ax = plt.subplots(figsize=(7, 7))
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    x = np.arange(len(VA_DEATHS))
    bottom = np.zeros(len(VA_DEATHS))
    for age, hatch in zip(VA_AGE_GROUPS, hatches):
        heights = np.array([VA_DEATHS[group][VA_AGE_GROUPS.index(age)]
                            for group in VA_DEATHS])
        ax.bar(
            x, heights, bottom=bottom, width=0.7, label=age,
            facecolor="white", edgecolor="black", hatch=hatch, linewidth=0.8,
        )
        bottom += heights
    ax.set_xticks(x, list(VA_DEATHS), fontsize=11)
    ax.set_ylabel("Death rate per 1000 population per year")
    ax.set_title("Death rates in Virginia, 1940")
    ax.legend(title="Age group", fontsize=10, loc="upper left")
    save(fig, outdir, "hatched-barplot.png")


def expenses_barplot(outdir: pathlib.Path) -> None:
    # Smallest first, so the largest expense sits at the bottom, as in
    # the original.
    categories = [
        "Insurance", "Entertainment", "Electronic devices", "Healthcare",
        "Eating out", "Travel", "Personal items", "Groceries",
        "Investments", "Car expenses", "House expenses",
    ]
    amounts = [340, 710, 780, 1265, 1485, 2185, 2815, 4480, 6325, 8615, 10650]

    fig, ax = plt.subplots(figsize=(11, 6))
    ax.grid(axis="x", color=GRID, linewidth=0.8)
    ax.barh(categories, amounts, height=0.62, color=BLUE)
    ax.set_xlabel("Expense breakdown (2009, $)")
    ax.set_xlim(0, 13500)
    ax.set_xticks([0, 3000, 6000, 9000, 12000])

    # The two callouts are the reason this figure is in the chapter:
    # the prose defines the category axis and the value axis here.
    # Both arrows travel through the empty right-hand side of the plot,
    # below the long bars, so they do not cross any data.
    callout = dict(
        xycoords="axes fraction", textcoords="axes fraction",
        color=ORANGE, fontsize=17, va="center",
    )
    ax.annotate(
        "Category axis", xy=(-0.015, 0.50), xytext=(0.60, 0.44), **callout,
        arrowprops=dict(arrowstyle="->", color=ORANGE, linewidth=2,
                        connectionstyle="arc3,rad=-0.16"),
    )
    ax.annotate(
        "Value axis", xy=(0.82, -0.04), xytext=(0.58, 0.16), **callout,
        arrowprops=dict(arrowstyle="->", color=ORANGE, linewidth=2,
                        connectionstyle="arc3,rad=-0.22"),
    )
    save(fig, outdir, "barplot-example-expenses.png")


def profit_by_region(outdir: pathlib.Path) -> None:
    regions = ["Ontario", "Manitoba", "Quebec", "Nova Scotia", "Alberta",
               "British Columbia"]
    profit = [562, 423, 231, 181, 90, 82]
    # Two-word regions go on two lines so the tick labels do not touch.
    wrapped = [region.replace(" ", "\n") for region in regions]

    fig, axes = plt.subplots(1, 2, figsize=(13, 4.2), width_ratios=[1, 1.5])

    # Left: the same numbers as a table, which is what the chapter
    # recommends for a handful of data points.
    ax = axes[0]
    ax.axis("off")
    table = ax.table(
        cellText=[[f"{value}"] for value in profit],
        rowLabels=regions,
        colLabels=["Profit ($ '000)"],
        cellLoc="right",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(15)
    table.scale(1, 1.9)
    for (row, _), cell in table.get_celld().items():
        cell.set_edgecolor(GRID)
        if row == 0:
            cell.set_text_props(weight="bold")

    # Right: the same numbers as the bar plot they would replace.
    ax = axes[1]
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    ax.bar(wrapped, profit, width=0.6, color=BLUE)
    ax.set_ylabel("Profit ($ '000)")
    ax.set_ylim(0, 600)
    ax.set_yticks([0, 150, 300, 450, 600])
    ax.tick_params(axis="x", labelsize=13)
    save(fig, outdir, "profit-by-region.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(__file__).parent
    barplot_vs_lineplot(outdir)
    hatched_barplot(outdir)
    expenses_barplot(outdir)
    profit_by_region(outdir)
