"""Box-plot figures for the data-visualization chapter of the PID book.

Two committed PNGs, replacing images previously generated by base-R
scripts (``boxplot-for-boards.R``, ``boxplot-for-systematic-method-2014.R``):

- ``boxplot-for-two-by-six-100-boards.png``: thickness at the six
  measurement positions for the first 100 boards of the two-by-six
  board dataset (https://openmv.net/info/six-point-board-thickness).
- ``boxplot-for-systematic-method-used-2014.png``: final-exam grades
  split by whether a systematic problem-solving method was used
  (https://openmv.net/info/systematic-method).

Both datasets are fetched from openmv.net; a local CSV of the same name
next to this script is used as a fallback when offline.

Usage
-----
    uv run --with pandas --with matplotlib python boxplot_chapter_figures.py [output_dir]

Writes the two PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd

BLUE = "#0072B2"
BLUE_FILL = "#B3D4EA"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

# Font sizes match the pixel height of the labels in the base-R
# originals (pointsize 14 at the same DPI), slightly boosted.
mpl.rcParams.update(
    {
        "font.size": 15,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.labelsize": 17,
        "xtick.labelsize": 15,
        "ytick.labelsize": 15,
        "axes.axisbelow": True,
    }
)


def fetch(name: str) -> pd.DataFrame:
    try:
        return pd.read_csv(f"http://openmv.net/file/{name}")
    except Exception:
        return pd.read_csv(HERE / name)


def styled_boxplot(ax, data, labels):
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    box = ax.boxplot(
        data, tick_labels=labels, widths=0.6, patch_artist=True,
        medianprops=dict(color="black", linewidth=2),
        flierprops=dict(marker="o", markersize=4, markerfacecolor="none",
                        markeredgecolor=BLUE),
    )
    for patch in box["boxes"]:
        patch.set(facecolor=BLUE_FILL, edgecolor=BLUE, linewidth=1.5)
    for part in ("whiskers", "caps"):
        plt.setp(box[part], color=BLUE, linewidth=1.5)


def boards(outdir: pathlib.Path) -> None:
    all_boards = fetch("six-point-board-thickness.csv")
    first100 = all_boards.iloc[:100, 1:7]
    fig, ax = plt.subplots(figsize=(6, 5))
    styled_boxplot(ax, [first100[c] for c in first100.columns], first100.columns)
    ax.set_ylabel("Thickness [mils]")
    fig.tight_layout()
    fig.savefig(outdir / "boxplot-for-two-by-six-100-boards.png", dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / 'boxplot-for-two-by-six-100-boards.png'}")


def systematic_method(outdir: pathlib.Path) -> None:
    method = fetch("systematic-method.csv")
    columns = ["MethodUsed", "MethodNotUsed"]
    labels = ["Method used", "Method not used"]
    fig, ax = plt.subplots(figsize=(6, 5))
    styled_boxplot(ax, [method[c].dropna() for c in columns], labels)
    ax.set_ylabel("Grades [maximum available is 28 points]")
    ax.set_ylim(0, 30)
    fig.tight_layout()
    fig.savefig(outdir / "boxplot-for-systematic-method-used-2014.png", dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / 'boxplot-for-systematic-method-used-2014.png'}")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    boards(outdir)
    systematic_method(outdir)
