"""Exercise figures for the data-visualization chapter of the PID book.

Five committed PNGs, replacing images previously generated by base-R
scripts (``website-traffic-plots.R``, ``kidnappings.R``,
``scatterplotmatrix-food-data.R``) and one spreadsheet screenshot. These
serve ``data-visualization/data-visualization-exercises.rst``:

- ``course-website-visits.png``: daily visits to a course website over
  five weeks, as a time-series plot and again as a sparkline, which is
  the comparison the question asks the reader to make.
- ``scatterplotmatrix-food-data.png``: the five-variable scatter-plot
  matrix of https://openmv.net/info/food-texture. The R original was
  ``car::scatterplotMatrix``, which printed each variable name over the
  middle of its density curve and drew the regression lines in bright
  green; the names are now panel titles and the lines follow the
  chapter's palette.
- ``website-traffic-boxplot.png``: visits by day of the week, in the
  Saturday-first order the solution text uses.
- ``website-traffic-timeseries.png``: the same visits against a real
  date axis, June to December. Previously stored with a ``.jpg``
  extension despite holding PNG bytes, and titled ``web.visits`` by R.
- ``kidnap-mobile.png``: kidnappings against mobile-phone antennae in
  Colombia, 1996 to 2007, the scatter-plot answer to the question about
  the time-series plot. Also previously a ``.jpg`` holding PNG bytes.
  The first and last years are labelled, since the solution notes that
  connecting the points recovers the time ordering the scatter plot
  loses.

The website-traffic and food-texture data come from openmv.net, with a
local CSV of the same name next to this script used as a fallback when
offline. The course-website visits are read from the committed analytics
export in this directory, which is UTF-16 encoded with no header row.
The Colombia values are the ones printed in ``kidnappings.R``, read off
the original time-series plot by the question's author.

Usage
-----
    uv run --with numpy --with pandas --with matplotlib python data_visualization_exercise_figures.py [output_dir]

Writes the five PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

BLUE = "#0072B2"
BLUE_FILL = "#B3D4EA"
VERMILLION = "#D55E00"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

ANALYTICS = ("Analytics_stats4.eng.mcmaster.ca_20100101-20100206"
             "_(VisitorsOverviewReport).csv")

# Kidnappings per 100,000 residents and mobile-phone antennae in
# thousands, Colombia, 1996 to 2007.
KIDNAP = [4, 5, 6.5, 7.5, 8.75, 7, 7, 5, 3.25, 2, 1.5, 1.25]
MOBILE = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 2, 3.5, 4.25, 6.5, 7.25]
KIDNAP_YEARS = list(range(1996, 2008))

mpl.rcParams.update(
    {
        "font.size": 15,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 17,
        "axes.labelsize": 17,
        "xtick.labelsize": 15,
        "ytick.labelsize": 15,
        "legend.fontsize": 14,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


def fetch(name: str) -> pd.DataFrame:
    try:
        return pd.read_csv(f"https://openmv.net/file/{name}")
    except Exception:
        return pd.read_csv(HERE / name)


def website_traffic() -> pd.DataFrame:
    web = fetch("website-traffic.csv")
    when = pd.to_datetime(
        web["MonthDay"].str.strip() + " " + web["Year"].astype(str),
        format="%B %d %Y",
    )
    return web.assign(When=when).sort_values("When").reset_index(drop=True)


def course_website_visits(outdir: pathlib.Path) -> None:
    visits = pd.read_csv(
        HERE / ANALYTICS, encoding="utf-16", header=None,
        names=["DayOfWeek", "MonthDay", "Year", "Visits"],
        skipinitialspace=True,
    )
    when = pd.to_datetime(
        visits["MonthDay"] + " " + visits["Year"].astype(str),
        format="%B %d %Y",
    )
    visits = visits.assign(When=when)
    # The term starts on 4 January; the first three days are the tail of
    # the holiday and are not part of the picture the question asks about.
    visits = visits[visits["When"] >= "2010-01-04"].reset_index(drop=True)
    last = visits.iloc[-1]
    print(f"course website: {len(visits)} days, last value {last['Visits']:.0f}")

    fig, axes = plt.subplots(1, 2, figsize=(15, 3.2), width_ratios=[4, 1])

    ax = axes[0]
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(visits["When"], visits["Visits"], "-o", color=BLUE,
            linewidth=1.8, markersize=6)
    ax.set_ylabel("Visits")
    ax.set_ylim(0, 180)
    ax.set_yticks([0, 60, 120, 180])
    ax.xaxis.set_major_locator(mdates.WeekdayLocator(byweekday=mdates.MO))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b"))

    # The same five weeks as a sparkline: no axes at all, just the shape
    # and the latest reading.
    ax = axes[1]
    ax.plot(visits["When"], visits["Visits"], color=BLUE, linewidth=1.4)
    ax.plot(last["When"], last["Visits"], "o", color=VERMILLION, markersize=7)
    ax.annotate(
        f" {last['Visits']:.0f}", xy=(last["When"], last["Visits"]),
        ha="left", va="center", color=VERMILLION, fontsize=15,
    )
    ax.set_ylim(0, 180)
    ax.set_xlim(visits["When"].min(),
                visits["When"].max() + pd.Timedelta(days=7))
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_visible(False)
    ax.set_title("The same data as a sparkline", fontsize=15)
    save(fig, outdir, "course-website-visits.png")


def food_texture_matrix(outdir: pathlib.Path) -> None:
    food = fetch("food-texture.csv")
    columns = ["Oil", "Density", "Crispy", "Fracture", "Hardness"]
    print("food texture correlations:")
    print(food[columns].corr().round(2).to_string())

    n = len(columns)
    fig, axes = plt.subplots(n, n, figsize=(13, 13))
    for row, y_name in enumerate(columns):
        for col, x_name in enumerate(columns):
            ax = axes[row, col]
            ax.grid(color=GRID, linewidth=0.6)
            if row == col:
                ax.hist(food[x_name], bins=12, color=BLUE_FILL,
                        edgecolor=BLUE, linewidth=1.0)
            else:
                x = food[x_name].to_numpy(dtype=float)
                y = food[y_name].to_numpy(dtype=float)
                ax.plot(x, y, "o", color=BLUE, markersize=4,
                        markerfacecolor="none", markeredgewidth=1.0)
                slope, intercept = np.polyfit(x, y, 1)
                edge = np.array([x.min(), x.max()])
                ax.plot(edge, intercept + slope * edge, color=VERMILLION,
                        linewidth=1.8)
            # Variable names sit above their diagonal panel rather than
            # over the middle of it, which is what the R original did.
            if row == 0:
                ax.set_title(x_name)
            if col == 0:
                ax.set_ylabel(y_name)
            if row != n - 1:
                ax.set_xticklabels([])
            if col != 0 or row == col:
                ax.set_yticklabels([])
            ax.tick_params(labelsize=12)
    save(fig, outdir, "scatterplotmatrix-food-data.png")


def traffic_boxplot(outdir: pathlib.Path) -> None:
    web = website_traffic()
    # The solution reads the weekend first, so the days are ordered that
    # way rather than Monday first.
    days = ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday",
            "Thursday", "Friday"]
    groups = [web.loc[web["DayOfWeek"].str.strip() == day, "Visits"] for day in days]
    print("median visits: "
          + ", ".join(f"{day} {group.median():.0f}"
                      for day, group in zip(days, groups)))

    fig, ax = plt.subplots(figsize=(11, 6))
    ax.grid(axis="y", color=GRID, linewidth=0.8)
    box = ax.boxplot(
        groups, tick_labels=days, widths=0.6, patch_artist=True,
        medianprops=dict(color="black", linewidth=2),
        flierprops=dict(marker="o", markersize=5, markerfacecolor="none",
                        markeredgecolor=VERMILLION),
    )
    for patch in box["boxes"]:
        patch.set(facecolor=BLUE_FILL, edgecolor=BLUE, linewidth=1.5)
    for part in ("whiskers", "caps"):
        plt.setp(box[part], color=BLUE, linewidth=1.5)
    ax.set_ylabel("Number of visits")
    save(fig, outdir, "website-traffic-boxplot.png")


def traffic_timeseries(outdir: pathlib.Path) -> None:
    web = website_traffic()
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(web["When"], web["Visits"], color=BLUE, linewidth=1.6)
    ax.set_ylabel("Number of website visits")
    ax.set_xlim(web["When"].min(), web["When"].max())
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b"))
    save(fig, outdir, "website-traffic-timeseries.png")


def kidnappings(outdir: pathlib.Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 7))
    ax.grid(color=GRID, linewidth=0.8)
    ax.plot(MOBILE, KIDNAP, "o", color=BLUE, markersize=10,
            markerfacecolor="none", markeredgewidth=2)
    # The solution points out that the scatter plot loses the time
    # ordering, so the two end years are named.
    for index, offset, align in ((0, (0.15, 0.22), "left"),
                                 (-1, (0.0, 0.35), "center")):
        ax.annotate(
            f"{KIDNAP_YEARS[index]}",
            xy=(MOBILE[index], KIDNAP[index]),
            xytext=(MOBILE[index] + offset[0], KIDNAP[index] + offset[1]),
            ha=align, color=GREY, fontsize=15,
        )
    ax.set_xlabel("Mobile phone antennae [thousands]")
    ax.set_ylabel("Kidnappings per 100,000 residents")
    save(fig, outdir, "kidnap-mobile.png")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    course_website_visits(outdir)
    food_texture_matrix(outdir)
    traffic_boxplot(outdir)
    traffic_timeseries(outdir)
    kidnappings(outdir)
