"""Scatter-plot figures for the data-visualization chapter of the PID book.

Two committed PNGs, replacing images previously generated by the base-R
script ``scatterplot-figures.R`` (the second image was previously a
screenshot of R's ``car::scatterplot`` output):

- ``scatterplot-figures.png``: two side-by-side scatter plots. Left:
  tray temperature against product vapour pressure from the
  distillation-tower dataset (https://openmv.net/info/distillation-tower,
  columns Temp9 and VapourPressure), a causal relationship. Right:
  simulated number of white scalp hairs against bone mineral density,
  a correlation driven by the lurking variable age.
- ``scatterplot-figures-with-regression-lines.png``: the same two
  panels with least-squares regression lines added, and the axis
  frames trimmed to the extent of the data, as the prose suggests.

The white-hair data are seeded so the committed images regenerate
exactly; the distillation data are fetched from openmv.net with a local
CSV fallback (``distillation-tower.csv`` next to this script).

Usage
-----
    uv run --with numpy --with pandas --with matplotlib python scatterplot_chapter_figures.py [output_dir]

Writes the two PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

BLUE = "#0072B2"
VERMILLION = "#D55E00"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

mpl.rcParams.update(
    {
        "font.size": 12,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.labelsize": 12,
        "axes.axisbelow": True,
    }
)


def load_panels():
    try:
        tower = pd.read_csv("http://openmv.net/file/distillation-tower.csv")
    except Exception:
        tower = pd.read_csv(HERE / "distillation-tower.csv")
    temperature = tower["Temp9"].to_numpy()
    vapour_pressure = tower["VapourPressure"].to_numpy()

    rng = np.random.default_rng(21)
    white_hairs = np.round(rng.normal(loc=500, scale=250, size=50))
    white_hairs = np.clip(white_hairs, 20, None)
    bmd = -0.25 * white_hairs + 1550 + rng.normal(scale=25, size=50)
    return (temperature, vapour_pressure), (white_hairs, bmd)


def draw(outdir: pathlib.Path, with_regression: bool, name: str) -> None:
    (temperature, vapour_pressure), (white_hairs, bmd) = load_panels()
    panels = [
        (temperature, vapour_pressure,
         "Tray temperature [°F]", "Vapour pressure [kPa]"),
        (white_hairs, bmd,
         "Number of white hairs per square inch of scalp",
         "Bone mineral density [kg/m$^3$]"),
    ]
    fig, axes = plt.subplots(1, 2, figsize=(12, 6))
    for ax, (x, y, xlabel, ylabel) in zip(axes, panels):
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(x, y, "o", color=BLUE, markersize=5, alpha=0.65)
        if with_regression:
            slope, intercept = np.polyfit(x, y, 1)
            xr = np.array([x.min(), x.max()])
            ax.plot(xr, intercept + slope * xr, color=VERMILLION, linewidth=2)
            # Frames only as far as the data extend.
            ax.spines["left"].set_bounds(y.min(), y.max())
            ax.spines["bottom"].set_bounds(x.min(), x.max())
        ax.set_xlabel(xlabel)
        ax.set_ylabel(ylabel)
    fig.tight_layout()
    fig.savefig(outdir / name, dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / name}")


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    draw(outdir, with_regression=False, name="scatterplot-figures.png")
    draw(outdir, with_regression=True,
         name="scatterplot-figures-with-regression-lines.png")
