"""Time-series figures for the data-visualization chapter of the PID book.

One committed PNG, replacing an image previously generated by base R
(``stock-prices.R``, using the ``xts`` plotting methods):

- ``AAPL-stock-prices.png``: four panels of Apple's daily closing price,
  each showing more history than the one before it, to make the point in
  ``data-visualization/time-series-plots.rst`` that a trend can only be
  read in context. Panels 2, 3 and 4 mark the window shown in panel 1
  with a pair of vertical rules.

Data: ``AAPL-stock-prices.csv`` next to this script, daily closes from
2 January 1985 to 31 December 2009, fetched once from Yahoo Finance and
committed so the figure does not depend on a live service. Yahoo reports
closes adjusted for the 7:1 split of 2014 and the 4:1 split of 2020,
neither of which had happened when the original figure was drawn, so the
committed values are multiplied by 28 to put them back on the price
scale this book has always shown: about $11 in early 1991 and about $211
at the end of 2009.

Usage
-----
    uv run --with pandas --with matplotlib python timeseries_chapter_figures.py [output_dir]

Writes the PNG into ``output_dir`` (default: this script's own
directory), refreshing the committed image in place.
"""

from __future__ import annotations

import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd

BLUE = "#0072B2"
VERMILLION = "#D55E00"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

# The window the reader is first shown, and which the wider panels mark.
FOCUS = ("1991-01-02", "1991-03-28")

PANELS = [
    ("1. Got to buy some of this stock!", "1991-01-02", "1991-03-28", "%d %b", False),
    ("2. But, here is some more context", "1990-01-02", "1991-12-31", "%b %Y", True),
    ("3. And, even further context", "1988-01-04", "1993-12-31", "%Y", True),
    ("4. To finish: all available data", "1985-01-02", "2009-12-31", "%Y", True),
]

mpl.rcParams.update(
    {
        "font.size": 15,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 18,
        "axes.labelsize": 16,
        "xtick.labelsize": 14,
        "ytick.labelsize": 14,
        "axes.axisbelow": True,
    }
)


def load() -> pd.DataFrame:
    prices = pd.read_csv(HERE / "AAPL-stock-prices.csv", parse_dates=["Date"])
    return prices.sort_values("Date").reset_index(drop=True)


def main(outdir: pathlib.Path) -> None:
    prices = load()
    focus = pd.to_datetime(list(FOCUS))

    fig, axes = plt.subplots(2, 2, figsize=(14, 9))
    for ax, (title, start, end, fmt, mark) in zip(axes.flat, PANELS):
        window = prices[(prices["Date"] >= start) & (prices["Date"] <= end)]
        ax.grid(color=GRID, linewidth=0.8)
        ax.plot(window["Date"], window["Close"], color=BLUE, linewidth=1.4)
        if mark:
            for edge in focus:
                ax.axvline(edge, color=VERMILLION, linewidth=1.8)
        ax.set_title(title)
        ax.set_ylabel("Stock price [$]")
        ax.set_xlim(pd.Timestamp(start), pd.Timestamp(end))
        ax.xaxis.set_major_formatter(mdates.DateFormatter(fmt))
        ax.xaxis.set_major_locator(mdates.AutoDateLocator(minticks=4, maxticks=6))
        print(
            f"{title}: {window['Close'].min():.2f} to {window['Close'].max():.2f}"
        )

    fig.tight_layout()
    fig.savefig(outdir / "AAPL-stock-prices.png", dpi=DPI)
    plt.close(fig)
    print(f"wrote {outdir / 'AAPL-stock-prices.png'}")


if __name__ == "__main__":
    main(pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE)
