"""Response-surface and Pareto figures for the designed-experiments chapter.

Four committed PNGs, replacing images previously generated by base-R and
lattice scripts (``factorial-two-level-surface-example.R``,
``factorial-two-level-surface-with-interaction.R``,
``bioreactor-case-improved.R``, ``fractional-factorial-question.R``):

- ``factorial-two-level-surface-example-cropped.png``: the true response
  surface over a two-level factorial region, showing the slight curvature
  that a two-level design cannot see.
- ``factorial-two-level-surface-with-interaction-cropped.png``: a system
  with a real temperature-by-substrate interaction, with the fitted
  least-squares plane drawn below the true surface.
- ``bioreactor-pareto-plot.png``: the magnitude of every effect in the
  bioreactor 2^4 factorial, sorted, so the reader can see which effects
  stand out.
- ``fractional-factorial-question.png``: the same plot for the eight-run
  saturated fractional factorial (7 factors, D = AB, E = AC, F = BC,
  G = ABC) in the exercises.

The two surfaces are the analytic functions the lattice scripts used, drawn
from the same viewpoint (lattice's default screen, with the vertical axis
compressed to half the horizontal scale, as ``aspect = c(0.9, 0.5)`` did).
The two Pareto plots are fitted from the response values printed in the
chapter: sixteen for the bioreactor, eight for the fractional factorial.

Defects in the originals corrected here:

- The R misspelled the y axis as "Subtrate concentration" in both surface
  figures; it is "Substrate" here.
- The R wrote uncropped images that had to be cropped by hand afterwards,
  which is why the committed filenames end in ``-cropped``. These are
  produced at the right size directly; the names are kept so the chapter
  does not have to change.
- ``fractional-factorial-question.png`` is drawn with a colourblind-safe
  fill instead of R's unfilled bars, and the bioreactor plot keeps the
  original's convention of colouring each bar by the sign of its
  coefficient, now with an explicit legend rather than an unexplained
  colour difference.

Usage
-----
    uv run --with numpy --with matplotlib python doe_surface_and_pareto_figures.py [output_dir]

Writes the four PNGs into ``output_dir`` (default: this script's own
directory), refreshing the committed images in place.
"""

from __future__ import annotations

import itertools
import pathlib
import sys

import matplotlib as mpl

mpl.use("Agg")

import matplotlib.pyplot as plt
import numpy as np

BLUE = "#0072B2"
BLUE_FILL = "#B3D4EA"
ORANGE = "#E69F00"
ORANGE_FILL = "#F5D28B"
GREY = "#666666"
GRID = "#DDDDDD"

DPI = 300
HERE = pathlib.Path(__file__).parent

# Lattice's default viewpoint, expressed for matplotlib: the near corner is
# (low temperature, low substrate), temperature runs to the lower right and
# substrate to the lower left, with the response on the left-hand axis.
ELEV, AZIM = 30, -160
# aspect = c(0.9, 0.5) in the R: y is 0.9 of x, z is half of x.
BOX_ASPECT = (1.0, 0.9, 0.5)

# Bioreactor 2^4 factorial: the sixteen yields printed in the exercise.
BIOREACTOR_Y = [60, 59, 63, 61, 69, 61, 94, 93, 56, 63, 70, 65, 44, 45, 78, 77]
# Eight-run saturated design in the exercise: 7 factors in 8 runs.
FRACTIONAL_Y = [14.0, 16.8, 15.0, 15.4, 27.6, 24.0, 27.4, 22.6]

mpl.rcParams.update(
    {
        "font.size": 16,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.titlesize": 18,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 15,
        "axes.axisbelow": True,
    }
)


def save(fig, outdir: pathlib.Path, name: str) -> None:
    fig.savefig(outdir / name, dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {outdir / name}")


def curved_surface(t, s):
    """The true conversion surface used in the two-level factorial example."""
    ts = (t - 320.0) / 20.0
    return 18 * ts + 10 * s + 60.5 - 7 * ts**2 - 4 * s**2 - 7.5 * ts * s


def interaction_surface(t, s):
    """A system whose response has a real temperature-by-substrate interaction."""
    ts = (t - 360.0) / 20.0
    return 30 * ts + 16 * s - 10 * ts**2 - 20 * s**2 + 16 * ts * s + 40.1


def fitted_plane(t, s):
    """The two-level model fitted inside the factorial region."""
    ts = (t - 395.0) / 5.0
    ss = (s - 0.875) / 0.375
    return 2.5 * ts + 3.5 * ss + 1.5 * ts * ss + 81.5


def trim(value: float) -> str:
    """Format a tick value without trailing zeros: 1.25, 1.5, 0.875."""
    return f"{value:g}"


def dress(ax, xticks, yticks, zticks) -> None:
    """Apply the shared 3D axis styling: light box, no shaded panes."""
    ax.set_xlabel("Temperature, T [K]", labelpad=18)
    ax.set_ylabel("Substrate concentration\nS [g/L]", labelpad=24)
    ax.set_zlabel("Conversion", labelpad=12)
    ax.set_xticks(xticks, [trim(v) for v in xticks])
    ax.set_yticks(yticks, [trim(v) for v in yticks])
    ax.set_zticks(zticks, [trim(v) for v in zticks])
    ax.view_init(elev=ELEV, azim=AZIM)
    ax.set_box_aspect(BOX_ASPECT)
    for axis in (ax.xaxis, ax.yaxis, ax.zaxis):
        axis.pane.set_facecolor("white")
        axis.pane.set_edgecolor(GRID)
        axis._axinfo["grid"]["color"] = GRID
        axis._axinfo["grid"]["linewidth"] = 0.6


def surface_example(outdir: pathlib.Path) -> None:
    t = np.linspace(338, 354, 15)
    s = np.linspace(1.25, 1.75, 15)
    grid_t, grid_s = np.meshgrid(t, s)
    conversion = curved_surface(grid_t, grid_s)
    print(f"factorial surface: conversion spans {conversion.min():.1f} to {conversion.max():.1f}")

    fig = plt.figure(figsize=(8.5, 6.5))
    ax = fig.add_subplot(projection="3d")
    ax.plot_wireframe(grid_t, grid_s, conversion, color=BLUE, linewidth=0.8)
    dress(ax, [338, 346, 354], [1.25, 1.50, 1.75], [53, 61, 69])
    save(fig, outdir, "factorial-two-level-surface-example-cropped.png")


def surface_with_interaction(outdir: pathlib.Path) -> None:
    t = np.linspace(390, 400, 40)
    s = np.linspace(0.5, 1.25, 40)
    grid_t, grid_s = np.meshgrid(t, s)
    true = interaction_surface(grid_t, grid_s)
    plane = fitted_plane(grid_t, grid_s)
    print(
        f"interaction surface: true spans {true.min():.1f} to {true.max():.1f}; "
        f"fitted plane spans {plane.min():.1f} to {plane.max():.1f}"
    )

    fig = plt.figure(figsize=(8.5, 6.5))
    ax = fig.add_subplot(projection="3d")
    # The plane and the true surface agree at the corners of the region; the
    # true surface bulges above the plane in between, which is what the
    # section is pointing out.
    ax.plot_wireframe(grid_t, grid_s, plane, color=ORANGE, linewidth=0.6,
                      rstride=4, cstride=4)
    ax.plot_surface(grid_t, grid_s, true, color=BLUE, alpha=0.85, linewidth=0,
                    antialiased=True, shade=True)
    dress(ax, [390, 395, 400], [0.5, 0.875, 1.25], [77, 88])
    handles = [
        mpl.lines.Line2D([], [], color=ORANGE, linewidth=1.5, label="Least squares plane"),
        mpl.patches.Patch(facecolor=BLUE, label="True response surface"),
    ]
    ax.legend(handles=handles, loc="upper left", frameon=False, bbox_to_anchor=(-0.02, 0.97))
    save(fig, outdir, "factorial-two-level-surface-with-interaction-cropped.png")


def full_factorial_columns(k: int) -> np.ndarray:
    """The 2^k design matrix in standard order (first factor cycling fastest)."""
    return np.array(list(itertools.product([-1, 1], repeat=k)))[:, ::-1]


def coefficients(columns: np.ndarray, y) -> np.ndarray:
    """Least squares coefficients for a saturated design, intercept dropped."""
    design = np.column_stack([np.ones(len(y)), columns])
    fitted, *_ = np.linalg.lstsq(design, np.asarray(y, float), rcond=None)
    return fitted[1:]


def bioreactor_effects() -> tuple[list[str], np.ndarray]:
    """Every main effect and interaction of the bioreactor 2^4 factorial."""
    names = ["A", "B", "C", "D"]
    runs = full_factorial_columns(4)
    columns, labels = [], []
    for order in range(1, 5):
        for combination in itertools.combinations(range(4), order):
            columns.append(np.prod(runs[:, combination], axis=1))
            labels.append(":".join(names[i] for i in combination))
    return labels, coefficients(np.column_stack(columns), BIOREACTOR_Y)


def fractional_effects() -> tuple[list[str], np.ndarray]:
    """The seven main effects of the saturated eight-run design.

    Four extra factors are placed on the interaction columns of a 2^3:
    D = AB, E = AC, F = BC and G = ABC, so all seven are estimable from
    eight runs, and nothing is left over for the interactions.
    """
    runs = full_factorial_columns(3)
    a, b, c = runs[:, 0], runs[:, 1], runs[:, 2]
    columns = np.column_stack([a, b, c, a * b, a * c, b * c, a * b * c])
    return ["A", "B", "C", "D", "E", "F", "G"], coefficients(columns, FRACTIONAL_Y)


def pareto(outdir: pathlib.Path, labels, values, name: str, figsize) -> None:
    """Sorted bar chart of effect magnitude, coloured by the sign of the effect."""
    order = np.argsort(np.abs(values))
    labels = [labels[i] for i in order]
    values = values[order]
    magnitude = np.abs(values)
    print(
        f"{name}: largest effects "
        + ", ".join(f"{lab} {val:+.2f}" for lab, val in zip(labels[::-1][:4], values[::-1][:4]))
    )

    fig, ax = plt.subplots(figsize=figsize)
    ax.grid(axis="x", color=GRID, linewidth=0.8)
    fills = [ORANGE_FILL if value > 0 else BLUE_FILL for value in values]
    edges = [ORANGE if value > 0 else BLUE for value in values]
    ax.barh(labels, magnitude, height=0.7, color=fills, edgecolor=edges, linewidth=1.4)
    ax.set_xlabel("Magnitude of effect")
    ax.set_ylabel("Effect")
    handles = [
        mpl.patches.Patch(facecolor=ORANGE_FILL, edgecolor=ORANGE, label="Positive coefficient"),
        mpl.patches.Patch(facecolor=BLUE_FILL, edgecolor=BLUE, label="Negative coefficient"),
    ]
    ax.legend(handles=handles, loc="lower right", frameon=False)
    save(fig, outdir, name)


if __name__ == "__main__":
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else HERE
    surface_example(outdir)
    surface_with_interaction(outdir)
    pareto(outdir, *bioreactor_effects(), "bioreactor-pareto-plot.png", (8, 8))
    pareto(outdir, *fractional_effects(), "fractional-factorial-question.png", (7.5, 5.5))
